const fs = require('fs');
let content = fs.readFileSync('src/data/support-catalog.ts', 'utf8');

// Find the closing }; of SUPPORT_CATALOG_DATA
const closingIdx = content.lastIndexOf('\n};');
if (closingIdx === -1) { console.log('ERROR: Cannot find closing };'); process.exit(1); }

// New substances to add (TypeScript object format, not JSON)
const newSubstances = `
  coq10: {
    id: 'coq10', name: 'CoQ10 (Ubiquinol)', nameRu: 'Коэнзим Q10 (Убихинол)',
    tier: 'core', category: ['antioxidant', 'cardioprotector', 'mitochondrial'],
    forms: [
      { id: 'coq10', name: 'Ubiquinol 200mg', nameRu: 'Убихинол 200 мг', dose: '200 мг с едой', best: true },
      { id: 'AO_COQ10_UBIQUINONE', name: 'Ubiquinone', nameRu: 'Убихинон 200 мг', dose: '200 мг с едой', best: false, notes: 'Менее биодоступен' },
      { id: 'AO_COQ10_MQ10', name: 'MitoQ', nameRu: 'MitoQ 10 мг', dose: '10 мг', best: false, notes: 'Целевая доставка в митохондрии' },
    ],
    organs: ['HEART', 'KIDNEYS', 'LIVER', 'MUSCLES'],
    systems: ['cardio', 'renal', 'hepatic'],
    mechanisms: ['ELECTRON_TRANSPORT_CHAIN', 'ANTIOXIDANT', 'ATP_PRODUCTION', 'MEMBRANE_STABILIZATION'],
    description: 'Коэнзим Q10 — ключевой компонент дыхательной цепи митохондрий. Защищает сердце от окислительного стресса, поддерживает продукцию АТФ. Обязателен при приёме ААС.',
    synergies: [
      { with: 'selenium', effect: 'Защита митохондрий', mechanism: 'Se — кофактор GPx', severity: 'MEDIUM' },
      { with: 'alpha_lipoic', effect: 'Регенерация CoQ10', mechanism: 'АЛЬК регенерирует окисленный CoQ10', severity: 'HIGH' },
      { with: 'omega3', effect: 'Кардиопротекция', mechanism: 'Разные механизмы защиты миокарда', severity: 'MEDIUM' },
    ],
    conflicts: [
      { with: 'warfarin', effect: 'Снижение антикоагулянтного эффекта', mechanism: 'CoQ10 структурно похож на витамин K', severity: 'MEDIUM' },
    ],
    monitoring: [
      { what: 'CoQ10 сыворотки', when: 'Каждые 12 нед', targetRange: '>0.5 мкг/мл' },
    ],
    contraindications: ['Приём варфарина (конфликт)', 'Гипотония (с осторожностью)'],
    sideEffects: ['Редко: тошнота при приёме натощак', 'Редко: бессонница при вечернем приёме'],
    dosage: { mg: 200, timing: 'с едой (убихинол)', form: 'убихинол' },
    bestForCourse: true,
  },
  vitamin_d3: {
    id: 'vitamin_d3', name: 'Vitamin D3', nameRu: 'Витамин D3',
    tier: 'core', category: ['vitamin', 'hormonal', 'immunomodulator'],
    forms: [
      { id: 'vitamin_d3', name: 'Vitamin D3 5000 IU', nameRu: 'Витамин D3 5000 МЕ', dose: '5000 МЕ с едой', best: true },
      { id: 'VIT_D3_LIP', name: 'Vitamin D3 Liposomal', nameRu: 'Липосомальный D3 5000 МЕ', dose: '5000 МЕ', best: false, notes: 'Лучшая биодоступность' },
    ],
    organs: ['BONES', 'IMMUNE_SYSTEM', 'THYROID', 'REPRODUCTIVE'],
    systems: ['endocrine', 'hepatic', 'hematologic'],
    mechanisms: ['VDR_RECEPTOR_ACTIVATION', 'CALCIUM_REGULATION', 'IMMUNE_MODULATION', 'TESTOSTERONE_SYNTHESIS'],
    description: 'Витамин D3 — прогормон, регулирующий кальций, иммунитет и гормональный баланс. 80% населения в дефиците. Критически важен на курсе ААС.',
    synergies: [
      { with: 'vitamin_k2', effect: 'Направление Ca в кости', mechanism: 'K2 активирует остеокальцин', severity: 'HIGH' },
      { with: 'magnesium', effect: 'Активация D3', mechanism: 'Mg необходим для конвертации D3 в 25-OH-D', severity: 'HIGH' },
      { with: 'zinc', effect: 'Усиление иммунитета', mechanism: 'Синергичная модуляция иммунного ответа', severity: 'MEDIUM' },
    ],
    conflicts: [
      { with: 'calcium_high', effect: 'Гиперкальциемия', mechanism: 'D3 увеличивает абсорбцию Ca', severity: 'LOW' },
    ],
    monitoring: [
      { what: '25(OH)D', when: 'Каждые 8 нед', targetRange: '50-80 нг/мл' },
      { what: 'Кальций общий', when: 'Каждые 12 нед', targetRange: '2.1-2.55 ммоль/л' },
    ],
    contraindications: ['Гиперкальциемия', 'Саркоидоз', 'Гиперпаратиреоз'],
    sideEffects: ['Гиперкальциемия при передозировке', 'Тошнота при высоких дозах'],
    dosage: { mg: 5000, timing: 'с едой (МЕ)', form: 'капсулы' },
    bestForCourse: true,
  },
  zinc: {
    id: 'zinc', name: 'Zinc', nameRu: 'Цинк',
    tier: 'core', category: ['mineral', 'immunomodulator', 'hormonal'],
    forms: [
      { id: 'zinc', name: 'Zinc Picolinate 30mg', nameRu: 'Цинк пиколинат 30 мг', dose: '30 мг на ночь', best: true },
      { id: 'MIN_ZN_BISGLYCINATE', name: 'Zinc Bisglycinate', nameRu: 'Цинк бисглицинат 30 мг', dose: '30 мг', best: false },
      { id: 'MIN_ZN_CITRATE', name: 'Zinc Citrate', nameRu: 'Цинк цитрат 30 мг', dose: '30 мг', best: false },
    ],
    organs: ['REPRODUCTIVE', 'IMMUNE_SYSTEM', 'SKIN', 'PROSTATE'],
    systems: ['reproductive', 'endocrine', 'hematologic'],
    mechanisms: ['TESTOSTERONE_SYNTHESIS', 'AR_RECEPTOR_MODULATION', 'IMMUNE_CELL_PROLIFERATION', 'WOUND_HEALING'],
    description: 'Цинк — эссенциальный микроэлемент для синтеза тестостерона, иммунитета и репродукции. Пиколинат — лучшая форма для усвоения.',
    synergies: [
      { with: 'vitamin_c', effect: 'Улучшение всасывания', mechanism: 'Витамин C усиливает абсорбцию цинка', severity: 'MEDIUM' },
      { with: 'vitamin_d3', effect: 'Усиление иммунитета', mechanism: 'Синергичная модуляция иммунного ответа', severity: 'MEDIUM' },
      { with: 'selenium', effect: 'Защита простаты', mechanism: 'Zn + Se = защита от окислительного стресса', severity: 'MEDIUM' },
    ],
    conflicts: [
      { with: 'copper', effect: 'Дисбаланс Zn/Cu', mechanism: 'Высокий Zn истощает медь при длительном приёме', severity: 'MEDIUM' },
      { with: 'iron', effect: 'Конкуренция за всасывание', mechanism: 'Zn и Fe конкурируют за DMT1', severity: 'LOW' },
    ],
    monitoring: [
      { what: 'Цинк сыворотки', when: 'Каждые 8 нед', targetRange: '11-18 мкмоль/л' },
      { what: 'Медь сыворотки', when: 'Каждые 12 нед', targetRange: '11-22 мкмоль/л' },
    ],
    contraindications: ['Болезнь Вильсона (медь)', 'Приём медьсодержащих препаратов'],
    sideEffects: ['Тошнота натощак', 'Металлический привкус', 'Дефицит меди при длительном приёме'],
    dosage: { mg: 30, timing: 'на ночь (пиколинат)', form: 'пиколинат' },
    bestForCourse: true,
  },
  selenium: {
    id: 'selenium', name: 'Selenium', nameRu: 'Селен',
    tier: 'core', category: ['mineral', 'antioxidant', 'thyroid'],
    forms: [
      { id: 'selenium', name: 'Selenium Methionine 200mcg', nameRu: 'Селен метионин 200 мкг', dose: '200 мкг с едой', best: true },
      { id: 'MIN_SE_YEAST', name: 'Selenium Yeast', nameRu: 'Селен дрожжевой 200 мкг', dose: '200 мкг', best: false },
    ],
    organs: ['THYROID', 'LIVER', 'IMMUNE_SYSTEM', 'REPRODUCTIVE'],
    systems: ['endocrine', 'hepatic', 'hematologic'],
    mechanisms: ['GPX_SYNTHESIS', 'THYROID_HORMONE_ACTIVATION', 'ANTIOXIDANT', 'DNA_REPAIR'],
    description: 'Селен — кофактор глутатионпероксидазы и дейодиназы щитовидной железы. Критически важен для антиоксидантной защиты и мужской фертильности.',
    synergies: [
      { with: 'vitamin_e', effect: 'Антиоксидантная синергия', mechanism: 'Se (GPx) + вит. E = двойная защита мембран', severity: 'HIGH' },
      { with: 'nac', effect: 'Глутатионовая система', mechanism: 'Se = GPx, NAC = предшественник глутатиона', severity: 'HIGH' },
    ],
    conflicts: [],
    monitoring: [
      { what: 'Селен сыворотки', when: 'Каждые 12 нед', targetRange: '70-150 нг/мл' },
    ],
    contraindications: ['Гипертиреоз (с осторожностью)', 'Приём других селен-содержащих добавок'],
    sideEffects: ['Запах чеснока при передозировке', 'Выпадение волос при >400 мкг/д'],
    dosage: { mg: 200, timing: 'с едой (мкг)', form: 'метионин' },
    bestForCourse: true,
  },
  milk_thistle: {
    id: 'milk_thistle', name: 'Milk Thistle (Silymarin)', nameRu: 'Расторопша (Силимарин)',
    tier: 'core', category: ['hepatoprotector', 'antioxidant', 'herb'],
    forms: [
      { id: 'milk_thistle', name: 'Silymarin 600mg', nameRu: 'Силимарин 600 мг', dose: '600 мг с едой 2x/д', best: true },
      { id: 'AO_SILYMARIN_PHOSPHO', name: 'Silymarin + Phospholipids', nameRu: 'Силимарин + фосфолипиды 300 мг 2x/д', dose: '300 мг 2x/д', best: false, notes: 'Лучшая биодоступность' },
    ],
    organs: ['LIVER', 'GALLBLADDER'],
    systems: ['hepatic'],
    mechanisms: ['MEMBRANE_STABILIZATION', 'ANTIOXIDANT', 'PROTEIN_SYNTHESIS_STIMULATION', 'ANTIFIBROTIC'],
    description: 'Расторопша (силимарин) — стандартизированный экстракт. Стабилизирует мембраны гепатоцитов, подавляет фиброз. Один из основных гепатопротекторов.',
    synergies: [
      { with: 'nac', effect: 'Комплексная гепатопротекция', mechanism: 'NAC = глутатион, силимарин = мембраны', severity: 'HIGH' },
      { with: 'tudca', effect: 'Максимальная гепатопротекция', mechanism: 'TUDCA + силимарин = полный охват', severity: 'HIGH' },
    ],
    conflicts: [],
    monitoring: [
      { what: 'АЛТ/АСТ', when: 'Каждые 4 нед', targetRange: '<40 Ед/л' },
    ],
    contraindications: ['Желчнокаменная болезнь (с осторожностью)', 'Аллергия на астровые'],
    sideEffects: ['Редко: диарея', 'Редко: аллергия'],
    dosage: { mg: 600, timing: 'с едой, 2x/д', form: 'капсулы' },
    bestForCourse: true,
  },
  curcumin: {
    id: 'curcumin', name: 'Curcumin + Piperine', nameRu: 'Куркумин + Пиперин',
    tier: 'core', category: ['polyphenol', 'antiinflammatory', 'antioxidant'],
    forms: [
      { id: 'curcumin', name: 'Curcumin + Piperine 1000mg', nameRu: 'Куркумин + Пиперин 1000 мг', dose: '1000 мг с пиперином, с едой', best: true },
      { id: 'PP_CURCUMIN_MERIVA', name: 'Curcumin Meriva (фитосомы)', nameRu: 'Куркумин Мерива 500 мг', dose: '500 мг', best: false, notes: 'Лучшая биодоступность' },
      { id: 'PP_CURCUMIN_THERACURMIN', name: 'Theracurmin', nameRu: 'Теракурмин 300 мг', dose: '300 мг', best: false, notes: 'Максимальная биодоступность' },
    ],
    organs: ['LIVER', 'JOINTS', 'BRAIN', 'INTESTINES'],
    systems: ['hepatic', 'musculoskeletal', 'neuro'],
    mechanisms: ['NF_KB_INHIBITION', 'COX2_INHIBITION', 'ANTIOXIDANT', 'ANTI_FIBROTIC', 'BDNF_INCREASE'],
    description: 'Куркумин — мощный противовоспалительный агент. Ингибирует NF-kB и COX-2. Пиперин увеличивает биодоступность на 2000%. Обязателен для печени и суставов.',
    synergies: [
      { with: 'omega3', effect: 'Противовоспалительная синергия', mechanism: 'COX-2 + резольвины', severity: 'MEDIUM' },
      { with: 'boswellia', effect: 'Суставная синергия', mechanism: '5-LOX + COX-2 = полный путь воспаления', severity: 'MEDIUM' },
      { with: 'vitamin_c', effect: 'Синтез коллагена', mechanism: 'Куркумин подавляет MMP, вит. C стимулирует коллаген', severity: 'LOW' },
    ],
    conflicts: [
      { with: 'anticoagulants', effect: 'Усиление антикоагуляции', mechanism: 'Ингибирование агрегации тромбоцитов', severity: 'MEDIUM' },
      { with: 'piperine_high', effect: 'Взаимодействие с лекарствами', mechanism: 'Пиперин ингибирует CYP3A4', severity: 'HIGH' },
    ],
    monitoring: [
      { what: 'АЛТ/АСТ', when: 'Каждые 6 нед', targetRange: '<40 Ед/л' },
      { what: 'СРБ', when: 'Каждые 8 нед', targetRange: '<5 мг/л' },
    ],
    contraindications: ['Желчнокаменная болезнь', 'Приём антикоагулянтов', 'Беременность'],
    sideEffects: ['Диарея при высоких дозах', 'Редко: аллергия'],
    dosage: { mg: 1000, timing: 'с пиперином, с едой', form: 'капсулы + пиперин' },
    bestForCourse: true,
  },
  ashwagandha: {
    id: 'ashwagandha', name: 'Ashwagandha KSM-66', nameRu: 'Ашваганда KSM-66',
    tier: 'core', category: ['adaptogen', 'antiinflammatory', 'hormonal'],
    forms: [
      { id: 'ashwagandha', name: 'Ashwagandha KSM-66 600mg', nameRu: 'Ашваганда KSM-66 600 мг', dose: '600 мг вечером', best: true },
      { id: 'AD_ASHWAGANDHA_SENSORIL', name: 'Ashwagandha Sensoril 250mg', nameRu: 'Ашваганда Sensoril 250 мг', dose: '250 мг', best: false, notes: 'Больше расслабления' },
    ],
    organs: ['ADRENALS', 'BRAIN', 'THYROID', 'REPRODUCTIVE'],
    systems: ['neuro', 'endocrine', 'reproductive'],
    mechanisms: ['CORTISOL_REDUCTION', 'GABA_RECEPTOR_AGONISM', 'THYROID_T3_INCREASE', 'TESTOSTERONE_SUPPORT'],
    description: 'Ашваганда KSM-66 — адаптоген, снижающий кортизол на 30%, повышающий тестостерон, улучшающий сон.',
    synergies: [
      { with: 'magnesium', effect: 'Синергия кортизол/расслабление', mechanism: 'Максимальное снижение кортизола', severity: 'HIGH' },
      { with: 'taurine', effect: 'Расслабление + кардиопротекция', mechanism: 'Снижение давления и кортизола', severity: 'MEDIUM' },
    ],
    conflicts: [
      { with: 'thyroid_medication', effect: 'Усиление действия гормонов щитовидной', mechanism: 'Ашваганда повышает T3/T4', severity: 'MEDIUM' },
    ],
    monitoring: [
      { what: 'Кортизол утренний', when: 'Каждые 8 нед', targetRange: '6-23 мкг/дл' },
      { what: 'ТТГ', when: 'Каждые 12 нед', targetRange: '0.4-4.0 мМЕ/л' },
    ],
    contraindications: ['Гипертиреоз', 'Аутоиммунные заболевания (с осторожностью)'],
    sideEffects: ['Сонливость в начале приёма', 'Редко: ЖК-дискомфорт'],
    dosage: { mg: 600, timing: 'вечер (KSM-66)', form: 'KSM-66' },
    bestForCourse: true,
  },
  vitamin_c: {
    id: 'vitamin_c', name: 'Vitamin C', nameRu: 'Витамин C (Аскорбиновая кислота)',
    tier: 'core', category: ['vitamin', 'antioxidant', 'immunomodulator'],
    forms: [
      { id: 'vitamin_c', name: 'Vitamin C 1000mg', nameRu: 'Витамин C 1000 мг', dose: '1000 мг натощак', best: true },
      { id: 'VIT_C_LIP', name: 'Liposomal Vitamin C', nameRu: 'Липосомальный витамин C 1000 мг', dose: '1000 мг', best: false, notes: 'Лучшая биодоступность' },
    ],
    organs: ['IMMUNE_SYSTEM', 'SKIN', 'BLOOD', 'ADRENALS'],
    systems: ['hematologic', 'hepatic', 'immune'],
    mechanisms: ['COLLAGEN_SYNTHESIS', 'ANTIOXIDANT', 'IMMUNE_CELL_FUNCTION', 'IRON_ABSORPTION', 'GLUTATHIONE_REGENERATION'],
    description: 'Витамин C — водорастворимый антиоксидант, необходимый для синтеза коллагена, иммунитета и регенерации глутатиона.',
    synergies: [
      { with: 'iron', effect: 'Усиление всасывания железа', mechanism: 'Витамин C восстанавливает Fe3+ в Fe2+', severity: 'HIGH' },
      { with: 'zinc', effect: 'Улучшение всасывания цинка', mechanism: 'Витамин C усиливает абсорбцию', severity: 'MEDIUM' },
      { with: 'collagen', effect: 'Синтез коллагена', mechanism: 'Витамин C — кофактор гидроксилирования пролина', severity: 'HIGH' },
      { with: 'nac', effect: 'Регенерация глутатиона', mechanism: 'Витамин C восстанавливает окисленный глутатион', severity: 'HIGH' },
    ],
    conflicts: [
      { with: 'copper', effect: 'Снижение меди при высоких дозах', mechanism: 'Высокие дозы вит. C истощают медь', severity: 'LOW' },
    ],
    monitoring: [],
    contraindications: ['Гемохроматоз (с осторожностью)', 'Оксалатные камни почек'],
    sideEffects: ['Диарея при дозах >2000 мг', 'Риск камней при склонности'],
    dosage: { mg: 1000, timing: 'натощак', form: 'порошок/таблетки' },
    bestForCourse: true,
  },
  taurine: {
    id: 'taurine', name: 'Taurine', nameRu: 'Таурин',
    tier: 'core', category: ['amino', 'cardioprotector', 'neuroprotector'],
    forms: [
      { id: 'taurine', name: 'Taurine 2000mg', nameRu: 'Таурин 2000 мг', dose: '2000 мг натощак', best: true },
    ],
    organs: ['HEART', 'BRAIN', 'LIVER', 'KIDNEYS'],
    systems: ['cardio', 'neuro', 'hepatic', 'renal'],
    mechanisms: ['OSMOREGULATION', 'ANTIOXIDANT', 'CALCIUM_REGULATION', 'GABA_RECEPTOR_MODULATION', 'BILE_ACID_CONJUGATION'],
    description: 'Таурин — условно-заменимая аминокислота. Кардиопротектор, нейропротектор, антиоксидант. Снижает давление, улучшает сократимость миокарда.',
    synergies: [
      { with: 'magnesium', effect: 'Кардиопротекция и расслабление', mechanism: 'Таурин + Mg = максимальная защита сердца', severity: 'MEDIUM' },
      { with: 'caffeine', effect: 'Сглаживание стимуляции', mechanism: 'Таурин уменьшает тревожность от кофеина', severity: 'LOW' },
    ],
    conflicts: [],
    monitoring: [],
    contraindications: ['Тяжёлая почечная недостаточность'],
    sideEffects: ['Редко: диарея при высоких дозах'],
    dosage: { mg: 2000, timing: 'натощак', form: 'порошок' },
    bestForCourse: true,
  },
  alpha_lipoic: {
    id: 'alpha_lipoic', name: 'Alpha-Lipoic Acid (R-ALA)', nameRu: 'АЛЬК R-форма',
    tier: 'core', category: ['antioxidant', 'neuroprotector', 'metabolic'],
    forms: [
      { id: 'alpha_lipoic', name: 'R-ALA 300mg', nameRu: 'АЛЬК R-форма 300 мг', dose: '300 мг натощак', best: true },
      { id: 'VIT_LIPOIC_R', name: 'R-Lipoic Acid 100mg', nameRu: 'R-липоевая кислота 100 мг', dose: '100 мг натощак', best: false, notes: 'R-форма более биодоступна' },
    ],
    organs: ['LIVER', 'BRAIN', 'NERVES', 'KIDNEYS'],
    systems: ['neuro', 'hepatic', 'renal'],
    mechanisms: ['ANTIOXIDANT_NETWORK', 'GLUTATHIONE_REGENERATION', 'MITOCHONDRIAL_FUNCTION', 'INSULIN_SENSITIVITY'],
    description: 'АЛЬК R-форма — универсальный антиоксидант. Регенерирует витамин C, E и глутатион. Улучшает инсулиновую чувствительность и нейропатию.',
    synergies: [
      { with: 'nac', effect: 'Усиление антиоксидантной сети', mechanism: 'АЛЬК регенерирует глутатион и вит. C', severity: 'HIGH' },
      { with: 'coq10', effect: 'Регенерация CoQ10', mechanism: 'АЛЬК восстанавливает окисленный CoQ10', severity: 'MEDIUM' },
      { with: 'vitamin_c', effect: 'Регенерация витамина E', mechanism: 'АЛЬК → вит. C → вит. E', severity: 'MEDIUM' },
    ],
    conflicts: [],
    monitoring: [],
    contraindications: ['Тяжёлая почечная недостаточность', 'Беременность'],
    sideEffects: ['Тошнота натощак', 'Редко: кожная сыпь', 'Редко: гипогликемия'],
    dosage: { mg: 300, timing: 'натощак (R-форма)', form: 'R-форма' },
    bestForCourse: true,
  },
  berberine: {
    id: 'berberine', name: 'Berberine', nameRu: 'Берберин',
    tier: 'core', category: ['antioxidant', 'metabolic', 'cardioprotector'],
    forms: [
      { id: 'berberine', name: 'Berberine HCl 500mg', nameRu: 'Берберин HCl 500 мг', dose: '500 мг с едой 2x/д', best: true },
    ],
    organs: ['LIVER', 'PANCREAS', 'INTESTINES', 'HEART'],
    systems: ['endocrine', 'hepatic', 'cardio'],
    mechanisms: ['AMPK_ACTIVATION', 'INSULIN_SENSITIVITY', 'CYP3A4_INHIBITION', 'NF_KB_INHIBITION', 'CHOLESTEROL_REDUCTION'],
    description: 'Берберин — алкалоид с мощной АМПК-активацией. Снижает сахар и триглицериды. Ингибирует CYP3A4 — осторожно с лекарствами.',
    synergies: [
      { with: 'milk_thistle', effect: 'Гепатопротекция + метаболизм', mechanism: 'Разные механизмы защиты печени', severity: 'MEDIUM' },
    ],
    conflicts: [
      { with: 'cyp3a4_substrates', effect: 'Взаимодействие с лекарствами', mechanism: 'Ингибирует CYP3A4', severity: 'HIGH' },
    ],
    monitoring: [
      { what: 'Глюкоза натощак', when: 'Каждые 4 нед', targetRange: '3.9-5.5 ммоль/л' },
      { what: 'АЛТ/АСТ', when: 'Каждые 6 нед', targetRange: '<40 Ед/л' },
    ],
    contraindications: ['Приём CYP3A4-субстратов', 'Беременность', 'Тяжёлая печёночная недостаточность'],
    sideEffects: ['Запор', 'Тошнота при высоких дозах', 'Взаимодействие с лекарствами (CYP3A4)'],
    dosage: { mg: 500, timing: 'с едой, 2x/д', form: 'HCl' },
    bestForCourse: true,
  },
  vitamin_k2: {
    id: 'vitamin_k2', name: 'Vitamin K2 (MK-7)', nameRu: 'Витамин K2 (МК-7)',
    tier: 'core', category: ['vitamin', 'cardioprotector', 'bone'],
    forms: [
      { id: 'vitamin_k2', name: 'Vitamin K2 MK-7 200mcg', nameRu: 'Витамин K2 МК-7 200 мкг', dose: '200 мкг с едой', best: true },
      { id: 'VIT_K2_MK4', name: 'Vitamin K2 MK-4 45mg', nameRu: 'Витамин K2 МК-4 45 мг', dose: '45 мг (частый приём)', best: false, notes: 'Короткий период полувыведения' },
    ],
    organs: ['BONES', 'HEART', 'VESSELS'],
    systems: ['cardio', 'hematologic'],
    mechanisms: ['OSTEOCALCIN_ACTIVATION', 'MATRIX_GLA_PROTEIN_ACTIVATION', 'CALCIUM_DISTRIBUTION'],
    description: 'Витамин K2 (МК-7) — активатор остеокальцина и MGP. Направляет кальций из сосудов в кости. Критически важен с витамином D3.',
    synergies: [
      { with: 'vitamin_d3', effect: 'Направление Ca в кости', mechanism: 'D3 увеличивает всасывание Ca, K2 направляет в кости', severity: 'HIGH' },
    ],
    conflicts: [
      { with: 'warfarin', effect: 'Антагонизм', mechanism: 'K2 конкурирует с варфарином', severity: 'HIGH' },
    ],
    monitoring: [],
    contraindications: ['Приём варфарина/антикоагулянтов', 'Тромбофилия'],
    sideEffects: ['Редко при передозировке'],
    dosage: { mg: 200, timing: 'с едой (мкг)', form: 'МК-7' },
    bestForCourse: true,
  },
  probiotics: {
    id: 'probiotics', name: 'Probiotics', nameRu: 'Пробиотики',
    tier: 'standard', category: ['probiotic', 'immunomodulator', 'hepatoprotector'],
    forms: [
      { id: 'probiotics', name: 'Multi-Strain Probiotic 20B CFU', nameRu: 'Мультиштаммовый пробиотик 20 млрд КОЕ', dose: '20 млрд КОЕ натощак', best: true },
      { id: 'PRO_L_RHAMNOSUS', name: 'L. Rhamnosus GG', nameRu: 'Л. Рамнозус GG', dose: '10 млрд КОЕ', best: false },
      { id: 'PRO_B_BIFIDUM', name: 'B. Bifidum', nameRu: 'Б. Бифидум', dose: '5 млрд КОЕ', best: false },
      { id: 'PRO_SACCHAROMYCES', name: 'S. Boulardii', nameRu: 'С. Буларди', dose: '5 млрд КОЕ', best: false, notes: 'Дрожжевой пробиотик, не уничтожается антибиотиками' },
    ],
    organs: ['INTESTINES', 'LIVER', 'IMMUNE_SYSTEM'],
    systems: ['hepatic', 'immune', 'hematologic'],
    mechanisms: ['GUT_MICROBIOME_MODULATION', 'IMMUNE_REGULATION', 'GUT_BARRIER_INTEGRITY', 'SHORT_CHAIN_FATTY_ACID_PRODUCTION', 'PATHOGEN_EXCLUSION'],
    description: 'Пробиотики — живые микроорганизмы, улучшающие микробиом кишечника. Укрепляют кишечный барьер, модулируют иммунитет, подавляют патогенную флору. Обязательны на курсе ААС.',
    synergies: [
      { with: 'prebiotics', effect: 'Синергия пребиотик + пробиотик', mechanism: 'Пребиотики обеспечивают питание для пробиотиков', severity: 'HIGH' },
      { with: 'milk_thistle', effect: 'Кишечно-печёночная ось', mechanism: 'Пробиотики улучшают всасывание силимарина', severity: 'LOW' },
      { with: 'vitamin_d3', effect: 'Усиление иммунитета', mechanism: 'Пробиотики + D3 = синергичная иммунная модуляция', severity: 'MEDIUM' },
    ],
    conflicts: [],
    monitoring: [],
    contraindications: ['Тяжёлый иммунодефицит', 'Центральный венозный катетер (риск бактериемии)'],
    sideEffects: ['Вздутие в начале приёма', 'Редко: диарея', 'Редко: аллергия на штамм'],
    dosage: { mg: 20, timing: 'натощак (млрд КОЕ)', form: 'капсулы' },
    bestForCourse: true,
  },
  collagen: {
    id: 'collagen', name: 'Collagen Hydrolysate', nameRu: 'Коллаген гидролизат',
    tier: 'standard', category: ['amino', 'joint', 'beauty'],
    forms: [
      { id: 'collagen', name: 'Collagen Hydrolysate 10g', nameRu: 'Коллаген гидролизат 10 г', dose: '10 г с едой', best: true },
      { id: 'AA_COLLAGEN_AMINO', name: 'Collagen Peptides', nameRu: 'Коллагеновые пептиды 10 г', dose: '10 г', best: false },
    ],
    organs: ['JOINTS', 'SKIN', 'BONES', 'MUSCLES'],
    systems: ['musculoskeletal'],
    mechanisms: ['COLLAGEN_SYNTHESIS', 'CARTILAGE_REPAIR', 'SKIN_ELASTICITY', 'TENDON_STRENGTH'],
    description: 'Гидролизованный коллаген — источник аминокислот для восстановления хрящей, сухожилий и кожи. Синергичен с витамином C для синтеза нового коллагена.',
    synergies: [
      { with: 'vitamin_c', effect: 'Синтез коллагена', mechanism: 'Витамин C — кофактор гидроксилирования пролина в коллагене', severity: 'HIGH' },
      { with: 'glucosamine', effect: 'Суставная синергия', mechanism: 'Коллаген + глюкозамин = восстановление хрящей', severity: 'MEDIUM' },
      { with: 'msm', effect: 'Сера для коллагена', mechanism: 'MSM поставляет серу для дисульфидных связей', severity: 'MEDIUM' },
    ],
    conflicts: [],
    monitoring: [],
    contraindications: [],
    sideEffects: ['Редко: тяжесть в желудке при приёме натощак'],
    dosage: { mg: 10000, timing: 'с едой (мг, гидролизат)', form: 'гидролизат' },
    bestForCourse: true,
  },
  glucosamine: {
    id: 'glucosamine', name: 'Glucosamine', nameRu: 'Глюкозамин',
    tier: 'standard', category: ['amino', 'joint'],
    forms: [
      { id: 'glucosamine', name: 'Glucosamine Sulfate 1500mg', nameRu: 'Глюкозамин сульфат 1500 мг', dose: '1500 мг с едой', best: true },
    ],
    organs: ['JOINTS', 'BONES'],
    systems: ['musculoskeletal'],
    mechanisms: ['CARTILAGE_REPAIR', 'SYNOVIAL_FLUID_PRODUCTION', 'ANTI_INFLAMMATORY'],
    description: 'Глюкозамин — строительный блок хрящевой ткани. Улучшает продукцию синовиальной жидкости и замедляет дегенерацию суставов.',
    synergies: [
      { with: 'chondroitin', effect: 'Суставная синергия', mechanism: 'Глюкозамин строит хрящ, хондроитин удерживает воду', severity: 'HIGH' },
      { with: 'msm', effect: 'Противовоспалительная синергия', mechanism: 'MSM снижает воспаление + глюкозамин восстанавливает хрящ', severity: 'MEDIUM' },
      { with: 'collagen', effect: 'Восстановление суставов', mechanism: 'Коллаген + глюкозамин = полный набор для хряща', severity: 'MEDIUM' },
    ],
    conflicts: [],
    monitoring: [],
    contraindications: ['Аллергия на моллюсков (для хондроитина из моллюсков)', 'С осторожностью при диабете'],
    sideEffects: ['Редко: дискомфорт в ЖКТ', 'Редко: аллергия'],
    dosage: { mg: 1500, timing: 'с едой', form: 'сульфат' },
    bestForCourse: false,
  },
  telmisartan: {
    id: 'telmisartan', name: 'Telmisartan', nameRu: 'Тельмисартан',
    tier: 'specialty', category: ['pharma', 'cardioprotector', 'metabolic'],
    forms: [
      { id: 'telmisartan', name: 'Telmisartan 40mg', nameRu: 'Тельмисартан 40 мг', dose: '40 мг утром (КАД контроль!)', best: true },
    ],
    organs: ['HEART', 'VESSELS', 'KIDNEYS'],
    systems: ['cardio', 'renal', 'endocrine'],
    mechanisms: ['ANGIOTENSIN_RECEPTOR_BLOCKADE', 'PPAR_GAMMA_ACTIVATION', 'BP_REDUCTION', 'RENOPROTECTION'],
    description: 'Тельмисартан — сартан с уникальным PPAR-γ эффектом. Снижает давление, защищает почки, улучшает инсулиновую чувствительность. Препарат выбора на курсе ААС для контроля давления.',
    synergies: [
      { with: 'omega3', effect: 'Кардиопротекция', mechanism: 'Разные механизмы снижения давления и воспаления', severity: 'MEDIUM' },
      { with: 'nebivolol', effect: 'Максимальный контроль давления и ЧСС', mechanism: 'Сартан + бета-блокатор = аддитивный эффект', severity: 'MEDIUM' },
    ],
    conflicts: [
      { with: 'ace_inhibitors', effect: 'Риск гиперкалиемии', mechanism: 'Двойная блокада РААС', severity: 'HIGH' },
      { with: 'potassium_supplements', effect: 'Гиперкалиемия', mechanism: 'Сартаны снижают экскрецию калия', severity: 'MEDIUM' },
    ],
    monitoring: [
      { what: 'АД', when: 'Ежедневно', targetRange: '<130/85 мм рт.ст.' },
      { what: 'Калий', when: 'Каждые 4 нед', targetRange: '3.5-5.0 ммоль/л' },
      { what: 'Креатинин', when: 'Каждые 8 нед', targetRange: '<110 мкмоль/л' },
    ],
    contraindications: ['Беременность', 'Двусторонний стеноз почечных артерий', 'Тяжёлая печёночная недостаточность'],
    sideEffects: ['Головокружение при первом приёме', 'Редко: гипотония', 'Гиперкалиемия при комбинировании с калийсберегающими'],
    dosage: { mg: 40, timing: 'утро (КАД контроль!)', form: 'таблетки' },
    bestForCourse: true,
  },
  nebivolol: {
    id: 'nebivolol', name: 'Nebivolol', nameRu: 'Небиволол',
    tier: 'specialty', category: ['pharma', 'cardioprotector'],
    forms: [
      { id: 'nebivolol', name: 'Nebivolol 5mg', nameRu: 'Небиволол 5 мг', dose: '5 мг утром (ЧСС контроль!)', best: true },
    ],
    organs: ['HEART', 'VESSELS'],
    systems: ['cardio'],
    mechanisms: ['BETA1_BLOCKADE', 'NO_RELEASE', 'HR_REDUCTION', 'BP_REDUCTION'],
    description: 'Небиволол — кардиоселективный бета-блокатор с уникальным NO-модулирующим эффектом. Снижает ЧСС и давление, улучшает эндотелиальную функцию. Препарат выбора для контроля ЧСС на курсе ААС.',
    synergies: [
      { with: 'telmisartan', effect: 'Контроль давления и ЧСС', mechanism: 'Бета-блокатор + сартан = аддитивный эффект', severity: 'MEDIUM' },
      { with: 'taurine', effect: 'Кардиопротекция', mechanism: 'Таурин + небиволол = максимальная защита миокарда', severity: 'LOW' },
    ],
    conflicts: [
      { with: 'beta_agonists', effect: 'Антагонизм', mechanism: 'Бета-блокаторы блокируют бета-агонисты', severity: 'MEDIUM' },
      { with: 'verapamil', effect: 'Риск брадикардии', mechanism: 'Аддитивное замедление AV-проводимости', severity: 'HIGH' },
    ],
    monitoring: [
      { what: 'ЧСС', when: 'Ежедневно', targetRange: '55-70 уд/мин' },
      { what: 'АД', when: 'Ежедневно', targetRange: '<130/85 мм рт.ст.' },
    ],
    contraindications: ['Бронхиальная астма (с осторожностью)', 'AV-блокада 2-3 степени', 'Брадикардия <50'],
    sideEffects: ['Брадикардия', 'Усталость', 'Редко: эректильная дисфункция', 'Редко: бронхоспазм'],
    dosage: { mg: 5, timing: 'утро (ЧСС контроль!)', form: 'таблетки' },
    bestForCourse: true,
  },
`;

// Insert new substances before the closing };
content = content.slice(0, closingIdx) + newSubstances + '\n' + content.slice(closingIdx);

fs.writeFileSync('src/data/support-catalog.ts', content, 'utf8');
console.log('Added substances to catalog');
