#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script to fix encoding in PlanScreen.tsx
"""

# Correct Russian text for all the labels
correct_text = {
    'bulk': 'Набор массы',
    'cut': 'Сушка',
    'maintenance': 'Поддержание',
    'strength': 'Сила',
    'recomp': 'Рекомпозиция',
    'rehab': 'Реабилитация',
    'beginner': 'Новичок',
    'intermediate': 'Средний',
    'advanced': 'Продвинутый',
    'enhanced': 'Усиленный (на курсе)',
    'chest': 'Грудь',
    'back': 'Спина',
    'legs': 'Ноги',
    'shoulders': 'Плечи',
    'arms': 'Руки',
    'core': 'Кор',
    'Plan & Cycles': 'План и циклы',
    'Readiness': 'Готовность',
    'Упражнения': 'Упражнения',
    'Parameters': 'Параметры',
    'Goal': 'Цель',
    'Level': 'Уровень',
    'Days/week': 'Дней/неделю',
    'Recovery': 'Восстановление',
    'Fatigue': 'Утомлённость',
    'Nutrition': 'Питание',
    'Weak Points': 'Слабые точки',
    'PAL (activity coefficient)': 'PAL (коэффициент активности)',
    'Training': 'Тренировка',
    'Split': 'Сплит',
    'Progression': 'Прогрессия',
    'Deload': 'Разгрузка',
    'Base': 'База',
    'Details': 'Детали',
    'Backup': 'Резерв',
    'About': 'О проекте',
    'Synergies': 'Синергии',
    'Alternatives': 'Альтернативы',
    'Best': 'Лучший',
    'Back': 'Назад',
    'Plan': 'План',
    'Cycles': 'Циклы',
    'Day': 'День',
    'Exercise': 'Упражнение',
    'Sets': 'Сеты',
    'Reps': 'Повторения',
    'RIR': 'RIR',
    'Rest': 'Отдых',
    'Deload?': 'Делейд?',
    'kg': 'кг',
    'Week': 'Неделя',
    'Accumulation': 'Накопление',
    'Intensification': 'Интенсификация',
    'Peaking': 'Пик',
    'Deload': 'Делейд',
    'Recovery': 'Восстановление',
    'Rest': 'Отдых',
    'Recovery, rest, cardio': 'Восстановление, отдых, кардио',
    'Very high': 'очень высокая',
    'High': 'высокая',
    'Medium': 'средняя',
    'Low': 'низкая',
    'Compound': 'Компаунд',
    'Isolation': 'Изолирующее',
    'Pause': 'Пауза',
    'Peak contraction': 'Пиковое сокращение',
    'Stretch': 'Растяжение',
    'Alternatives': 'Заменители',
    'Deload reason': 'Причина делейда',
    'Volume': 'Объём',
    'Set': 'Сет',
}

# Read the current file
with open('src/ui/screens/PlanScreen.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

# Replace incorrect sequences with correct Russian text
replacements = [
    ('╨Э╨░╨▒╨╛╤А ╨╝╨░╤Б╤Б╤Л', correct_text['bulk']),
    ('╨б╤Г╤И╨║╨░', correct_text['cut']),
    ('╨Я╨╛╨┤╨┤╨╡╤А╨╢╨░╨╜╨╕╨╡', correct_text['maintenance']),
    ('╨б╨╕╨╗╨░', correct_text['strength']),
    ('╨а╨╡╨║╨╛╨╝╨┐╨╛╨╖╨╕╤Ж╨╕╤П', correct_text['recomp']),
    ('╨а╨╡╨░╨▒╨╕╨╗╨╕╤В╨░╤Ж╨╕╤П', correct_text['rehab']),
    ('╨Э╨╛╨▓╨╕╤З╨╛╨║', correct_text['beginner']),
    ('╨б╤А╨╡╨┤╨╜╨╕╨╣', correct_text['intermediate']),
    ('╨Я╤А╨╛╨┤╨▓╨╕╨╜╤Г╤В╨╗╨╡╨╡', correct_text['advanced']),
    ('╨г╤Б╨╕╨╗╨╡╨╜╨╜╨╕╨╣ (╨╜╨░ ╨║╤Г╤А╤Б╨╡)', correct_text['enhanced']),
    ('╨У╤А╤Г╨┤╤М', correct_text['chest']),
    ('╨б╨┐╨╕╨╜╨░', correct_text['back']),
    ('╨Э╨╛╨│╨╕', correct_text['legs']),
    ('╨Я╨╗╨╡╤З╨╕', correct_text['shoulders']),
    ('╨а╤Г╨║╨╕', correct_text['arms']),
    ('╨Ъ╨╛╤А', correct_text['core']),
    ('╨Я╨╗╨░╨╜ ╨╕ ╤Ж╨╕╨║╨╗╤Л', 'План и циклы'),
    ('╨У╨╛╤В╨╛╨▓╨╜╨╛╤Б╤В╤М', 'Готовность'),
    ('╨г╨┐╤А╨░╨╢╨╜╨╡╨╜╨╕╤П', 'Упражнения'),
    ('╨Я╨░╤А╨░╨╝╨╡╤В╤А╨╗╨╡', 'Параметры'),
    ('╨ж╨╡╨╗╨╜', 'Цель'),
    ('╨г╤А╨╛╨▓╨╡╨╜╨╜', 'Уровень'),
    ('╨Ф╨╜╨╡╨╣/╨╜╨╡╨┤╨╡╨╗╨╛: {daysPerWeek}', 'Дней/неделю: {daysPerWeek}'),
    ('╨В╨╛╤Б╤В╨░╨╜╨╛╨▓╨╗╨╡╨╜╨╕╨╡: {recovery}%', 'Восстановление: {recovery}%'),
    ('╨г╤2╤╛╤╝╨╗╨║╨╗╨╛╤Б╤В╨╝: {fatigue}%', 'Утомлённость: {fatigue}%'),
    ('╨Я╨╕╤B╨╜╨╕╨╜╨╡: {nutrition}%', 'Питание: {nutrition}%'),
    ('╨б╨╗╨░╨▒╨╗╨╡ ╨╝╨┐╨╗╨╡╨║╨╗╨╕', 'Слабые точки'),
    ('╨Я╨░╨╗ (╨║╨╛╨╡╨Д╨Д╨║╨╜╤В ╨░╨║╤B╨╜╨╛╤Б╤B╨╝)', 'PAL (коэффициент активности)'),
    ('╨в╤А╨╡╨╜╨╕╨╗╨╛╨║╨░: {profile.settings.workoutsPerWeek}?', 'Тренировка: {profile.settings.workoutsPerWeek}?'),
    ('╨Д╨╜╨╡╨╗╨╝/╨╜╨╡╨┤╨╗╨╡╨╗╨╝ ├Ч {profile.settings.avgWorkoutMinutes} ╨║╨╜', 'Дней/неделю ├Ч {profile.settings.avgWorkoutMinutes} км'),
    ('╨б╨┐╨╗╨╕╨B', 'Сплит'),
    ('╨Я╤А╨╛╨│╤А╨╡╤Б╤П╨║╨╗╨╝', 'Прогрессия'),
    ('╨а╨░╨╖╨│╤А╨║╨╗╨╝', 'Разгрузка'),
    ('╨Ю╨▒╨╗╨╛╨│╨╗╨╡╨╜╨╝', 'Объём'),
    ('╨Э╨╗╨╜╨╝', 'Неделя'),
    ('╨Э╨░╨║╨╛╨┐╨╗╨╡╨╜╨╝╨╝', 'Накопление'),
    ('╨Ш╨╜╤B╨╡╨╜╤П╨╝╨╕╨╗╨╝╨╗╨░╤А╨╗╨╗╨╝', 'Интенсификация'),
    ('╨Я╨╕╨║', 'Пик'),
    ('╨Ф╨╡╨╗╨╛╨░╨┤', 'Делейд'),
    ('╨в╨╛╤�╨╜╨╛╨┤╨╗╨╡╨╜╨╝', 'Восстановление'),
    ('╨о╨│╨╗╨╗╨╗╨╗╨╗╨╗', 'Отдых'),
    ('╨В╨╛╤�╨╜╨╛╨┤╨╗╨╡╨╜╨╝, ╨│╨│╨╗╨╗╨╗, ╨║╨░╤А╨╗╨╗╨╗', 'Восстановление, отдых, кардио'),
    ('╨о╨╗╨╗╨╗ ╨╗╨╗╨╗╨╗╨╗╨╗╨╗╨╗╨╗', 'очень высокая'),
    ('╨о╨╗╨╗╨╗ ╨╗╨╗╨╗╨╗╨╗', 'высокая'),
    ('╨о╨╗╨╗╨╗ ╨╗╨╗╨╗╨╗', 'средняя'),
    ('╨о╨╗╨╗╨╗', 'низкая'),
    ('╨о╨╗╨╗╨╗╨╗╨╗', 'Компаунд'),
    ('╨о╨╗╨╗╨╗╨╗╨╗╨╗╨╗', 'Изолирующее'),
    ('╨о╨╗╨╗╨╗╨╗╨╗╨╗', 'Пауза'),
    ('╨о╨╗╨╗╨╗╨╗╨╗╨╗╨╗╨╗╨╗', 'Пиковое сокращение'),
    ('╨о╨╗╨╗╨╗╨╗╨╗╨╗╨╗', 'Растяжение'),
    ('╨о╨╗╨╗╨╗╨╗╨╗╨╗╨╗╨╗╨╗╨╗', 'Заменители'),
]

for old, new in replacements:
    content = content.replace(old, new)

# Write back with correct encoding
with open('src/ui/screens/PlanScreen.tsx', 'w', encoding='utf-8') as f:
    f.write(content)

print("Encoding fixed!")
