/**
 * Controlled-mechanism vocabulary normalizer for BioStack synergy detection.
 *
 * The catalog `mechanisms` field uses ~1100 free-text UPPER_SNAKE tokens with
 * many near-duplicate spellings (ANTIOXIDANT vs ANTIOXIDANT_DEFENSE,
 * NRF2_ACTIVATION vs NRF2_UPREGULATION, GLUTATHIONE_SYNTHESIS vs
 * GLUTATHIONE_PRECURSOR/UP/CONJUGATION, etc.). SynergyEngine compares tokens
 * by exact string match, so these spelling variants silently under-detect
 * synergies. This module collapses them to canonical concepts (preserving
 * direction where it matters) so shared-mechanism detection is consistent.
 */

const SYNONYM_MAP: Record<string, string> = {
  // ── Antioxidant family ──
  ANTIOXIDANT_DEFENSE: 'ANTIOXIDANT',
  ANTIOXIDANT_ENZYME: 'ANTIOXIDANT',
  ANTIOXIDANT_ENZYME_INDUCTION: 'ANTIOXIDANT',
  ROS_SCAVENGING: 'ANTIOXIDANT',
  HIGH_ORAC: 'ANTIOXIDANT',
  FULLERENE_ANTIOXIDANT: 'ANTIOXIDANT',
  MELANIN_ANTIOXIDANT: 'ANTIOXIDANT',
  SINGLET_OXYGEN_QUENCH: 'ANTIOXIDANT',
  LIPID_PEROXIDATION_INHIBITION: 'ANTIOXIDANT',
  LIPID_PEROXIDATION: 'ANTIOXIDANT',

  // ── Anti-inflammatory ──
  ANTI_INFLAMMATORY: 'ANTIINFLAMMATORY',

  // ── Anti-catabolic ──
  ANTICATABOLIC: 'ANTICATABOLIC',
  ANTI_CATABOLIC: 'ANTICATABOLIC',
  ANTICATABOLIC_MUSCLE: 'ANTICATABOLIC',
  MUSCLE_BREAKDOWN_PREVENTION: 'ANTICATABOLIC',

  // ── Anti-androgen ──
  ANTI_ANDROGEN: 'ANTIANDROGEN',
  ANTI_ANDROGENIC: 'ANTIANDROGEN',

  // ── NRF2 / NF-kB ──
  NRF2_UPREGULATION: 'NRF2_ACTIVATION',
  NF_KB_INHIBITION: 'NFKB_INHIBITION',

  // ── Glutathione family ──
  GLUTATHIONE_PRECURSOR: 'GLUTATHIONE_SYNTHESIS',
  GLUTATHIONE_CONJUGATION: 'GLUTATHIONE_SYNTHESIS',
  GLUTATHIONE_RECYCLING: 'GLUTATHIONE_SYNTHESIS',
  GLUTATHIONE_PEROXIDASE: 'GLUTATHIONE_SYNTHESIS',
  GLUTATHIONE_UP: 'GLUTATHIONE_SYNTHESIS',

  // ── Membrane ──
  MEMBRANE_SYNTHESIS: 'MEMBRANE_STABILIZATION',
  MEMBRANE_PHOSPHOLIPID: 'MEMBRANE_STABILIZATION',
  CELL_MEMBRANE_SYNTHESIS: 'MEMBRANE_STABILIZATION',

  // ── Blood pressure ──
  BLOOD_PRESSURE_LOWERING: 'BP_REDUCTION',
  BLOOD_PRESSURE_REGULATION: 'BP_REDUCTION',

  // ── Nitric-oxide family ──
  NITRIC_OXIDE_PRODUCTION: 'NO_RELEASE',
  NO_PRODUCTION: 'NO_RELEASE',
  NO_SYNTHESIS: 'NO_RELEASE',
  NO_UP: 'NO_RELEASE',
  NO_UPREGULATION: 'NO_RELEASE',
  NO_ENHANCEMENT: 'NO_RELEASE',
  NO_MODULATION: 'NO_RELEASE',
  NO_PATHWAY: 'NO_RELEASE',
  ENOS_ACTIVATION: 'NO_RELEASE',
  ENOS_COUPLING: 'NO_RELEASE',
  NOS_STIMULATION: 'NO_RELEASE',

  // ── ER stress ──
  ENDOPLASMIC_RETICULUM_STABILIZATION: 'ER_STRESS_REDUCTION',

  // ── AMPK ──
  AMPK_UP: 'AMPK_ACTIVATION',

  // ── Joint ──
  JOINT_SUPPORT: 'JOINT_PROTECTION',
  JOINT_FUNCTION: 'JOINT_PROTECTION',

  // ── Gut barrier / microbiome ──
  GUT_BARRIER_INTEGRITY: 'GUT_BARRIER',
  GUT_BARRIER_PROTECTION: 'GUT_BARRIER',
  GUT_BARRIER_STRENGTHENING: 'GUT_BARRIER',
  GUT_LINING_PROTECTION: 'GUT_BARRIER',
  GUT_MICROBIOME_SUPPORT: 'GUT_MICROBIOME_MODULATION',

  // ── Immune ──
  IMMUNE_STIMULATION: 'IMMUNE_MODULATION',
  IMMUNE_SUPPORT: 'IMMUNE_MODULATION',
  IMMUNE_REGULATION: 'IMMUNE_MODULATION',
  IMMUNE_FUNCTION: 'IMMUNE_MODULATION',

  // ── Cognitive ──
  COGNITIVE_ENHANCEMENT: 'COGNITION_ENHANCEMENT',
  COGNITIVE_FUNCTION: 'COGNITION_ENHANCEMENT',
  COGNITION_SUPPORT: 'COGNITION_ENHANCEMENT',

  // ── Sleep ──
  SLEEP_PROMOTION: 'SLEEP_IMPROVEMENT',
  SLEEP_QUALITY: 'SLEEP_IMPROVEMENT',
  SLEEP_REGULATION: 'SLEEP_IMPROVEMENT',

  // ── Testosterone ──
  TESTOSTERONE_BOOST: 'TESTOSTERONE_SYNTHESIS',
  TESTOSTERONE_PRODUCTION: 'TESTOSTERONE_SYNTHESIS',
  TESTOSTERONE_SUPPORT: 'TESTOSTERONE_SYNTHESIS',
  TESTOSTERONE_RESTORE: 'TESTOSTERONE_SYNTHESIS',
  TESTOSTERONE_UP: 'TESTOSTERONE_SYNTHESIS',
  TESTOSTERONE_REGULATION: 'TESTOSTERONE_SYNTHESIS',

  // ── Insulin sensitivity ──
  INSULIN_SIGNALING: 'INSULIN_SENSITIVITY',
  GLUCOSE_UPTAKE: 'INSULIN_SENSITIVITY',
  GLUT4_TRANSLOCATION: 'INSULIN_SENSITIVITY',

  // ── Lipid lowering ──
  CHOLESTEROL_LOWERING: 'LIPID_LOWERING',
  CHOLESTEROL_REDUCTION: 'LIPID_LOWERING',
  TRIGLYCERIDE_LOWERING: 'LIPID_LOWERING',
  LIPID_REDUCTION: 'LIPID_LOWERING',
  LIPID_IMPROVEMENT: 'LIPID_LOWERING',

  // ── Mitochondrial ──
  MITOCHONDRIAL_ENHANCEMENT: 'MITOCHONDRIAL_FUNCTION',
  MITOCHONDRIAL_SUPPORT: 'MITOCHONDRIAL_FUNCTION',
  MITOCHONDRIAL_PROTECTION: 'MITOCHONDRIAL_FUNCTION',
  MITOCHONDRIAL_MODULATION: 'MITOCHONDRIAL_FUNCTION',

  // ── GABA ──
  GABA_AGONIST: 'GABA_MODULATION',
  GABA_AGONISM: 'GABA_MODULATION',
  GABA_BOOST: 'GABA_MODULATION',
  GABA_A_AGONIST: 'GABA_MODULATION',
  GABA_B_AGONIST: 'GABA_MODULATION',
  GABA_RECEPTOR_AGONISM: 'GABA_MODULATION',
  GABA_SYNTHESIS: 'GABA_MODULATION',
  GABA_PRECURSOR: 'GABA_MODULATION',
  ANXIOLYTIC_GABA: 'GABA_MODULATION',

  // ── Anticoagulant ──
  ANTICOAGULATION: 'ANTICOAGULANT',
  ANTI_COAGULANT: 'ANTICOAGULANT',

  // ── Fibrinolysis ──
  FIBRINOLYTIC: 'FIBRINOLYSIS',
  FIBRIN_DEGRADATION: 'FIBRINOLYSIS',
  THROMBUS_RESOLUTION: 'FIBRINOLYSIS',

  // ── Cortisol ──
  CORTISOL_DOWN: 'CORTISOL_REDUCTION',
  CORTISOL_MODULATION: 'CORTISOL_REDUCTION',
  CORTISOL_BALANCE: 'CORTISOL_REDUCTION',

  // ── Dopamine ──
  DOPAMINE_AGONIST: 'DOPAMINE_MODULATION',
  DOPAMINE_SYNTHESIS: 'DOPAMINE_MODULATION',
  DOPAMINE_REGULATION: 'DOPAMINE_MODULATION',
  DOPAMINE_PRECURSOR: 'DOPAMINE_MODULATION',
  DOPAMINE_PROTECTION: 'DOPAMINE_MODULATION',

  // ── Serotonin ──
  SEROTONIN_SYNTHESIS: 'SEROTONIN_MODULATION',
  SEROTONIN_PRECURSOR: 'SEROTONIN_MODULATION',
  SEROTONIN_REUPTAKE_ENHANCEMENT: 'SEROTONIN_MODULATION',

  // ── Vitamin C synergy ──
  VITAMIN_C_SYNERGY: 'VITAMIN_C_POTENTIATION',
  VITAMIN_C_STABILIZATION: 'VITAMIN_C_POTENTIATION',

  // ── Bile flow ──
  BILE_FLOW: 'BILE_FLOW_STIMULATION',
  BILE_SECRETION: 'BILE_FLOW_STIMULATION',
  CHOLERETIC: 'BILE_FLOW_STIMULATION',

  // ── Collagen ──
  COLLAGEN_PRODUCTION: 'COLLAGEN_SYNTHESIS',
  COLLAGEN_PROTECTION: 'COLLAGEN_SYNTHESIS',
  COLLAGEN_STABILIZATION: 'COLLAGEN_SYNTHESIS',
};

export function normalizeMechanisms(mechanisms: string[] | undefined | null): string[] {
  if (!mechanisms || !mechanisms.length) return [];
  const out: string[] = [];
  const seen = new Set<string>();
  for (const raw of mechanisms) {
    if (!raw || typeof raw !== 'string') continue;
    const token = raw.trim().toUpperCase();
    if (!token) continue;
    const canon = SYNONYM_MAP[token] || token;
    if (!seen.has(canon)) {
      seen.add(canon);
      out.push(canon);
    }
  }
  return out;
}
