import type { TrainingDirection } from './training-methodology.engine';

/**
 * Map of direction → recommended methodology names.
 * Used by constructors to highlight relevant methods when a cycle/split is selected.
 */
export const DIRECTION_METHOD_MAP: Record<TrainingDirection, string[]> = {
  strength: [
    'Линейная периодизация (Linear Periodization)',
    'Блочная периодизация (Block Periodization)',
    'Сопряжённый метод (Conjugate / Westside)',
    '5/3/1 (Wendler)',
    'Метод максимальных усилий (Max Effort Method)',
    'Метод динамических усилий (Dynamic Effort Method)',
    'Кластерный метод (Cluster Sets)',
    'RPE-based Autoregulation',
    'Progressive Overload (базовый принцип)',
    'RTS Emerging Strategies (RPE-программирование по Tuchscherer)',
    'Westside Conjugate: структура ME/DE дней',
    'Cluster 5×5 (для 2×/нед)',
    'Негативы (Эксцентрические повторения)',
    'Wave Loading (Волны нагрузки)',
    'Squat Every Day (высокочастотный)',
    'Силовой цикл 2×/нед (ПЛ)',
    'Болгарский метод (Bulgarian Method / Daily Max)',
    'Пауза в нижней точке (Bottom Pause)',
    'Paused Reps (вариации для 2×/нед)',
    'Жимовое троеборье (Bench-only блочная периодизация)',
    'Приседательное троеборье (Squat-центричная периодизация)',
    'Тяговое троеборье (Deadlift-центричная периодизация)',
    'Темп "Силовой" (2-1-1-0)',
    'Темп "Взрывной" (1-0-0-0)',
    'Темп "Скоростной / CAT" (1-0-0-0)',
  ],
  bodybuilding: [
    'Волновая периодизация (Daily Undulating Periodization — DUP)',
    'Метод повторных усилий (Repeated Effort Method)',
    'Rest-Pause Training',
    'Drop Sets (Дроп-сеты)',
    'Myo-Reps',
    'Blood Flow Restriction (BFR)',
    'Pre-Exhaust (Предварительное утомление)',
    'German Volume Training (GVT / 10×10)',
    'FST-7 (Fascia Stretch Training)',
    'Gironda 8×8',
    'Суперсеты (Antagonist Supersets)',
    'Трисеты / Гигантские сеты',
    'Форсированные повторения (Forced Reps)',
    'Двойная прогрессия (Double Progression)',
    'Тройная прогрессия (Triple Progression)',
    'Drop-Set 4/8/12 (метод 50)',
    'Antagonist Superset 2×/нед (Грудь/Спина)',
    'Метаболический тренинг (Giant Sets для жиросжигания)',
    '1.5 повторения',
    'Темп "Гипертрофичный" (3-1-1-0)',
    'Темп "TUL-максимум" (4-2-1-1)',
    'Темп "Изометрия в растяжении" (2-3-1-0)',
    'Tempo для гипертрофии (3-1-1-0)',
    'Volume Landmarks (MEV/MAV/MRV)',
    'High-Frequency Hypertrophy (2×/нед на группу)',
    'Volume Progression RP (мезо 2×/нед)',
    'GVT 2×/нед (10×10 на группу)',
    'HIT (High-Intensity Training / Mentzer)',
    'PPL 6× (2×/нед на группу)',
    'Массонабор груди (Грудная специализация)',
    'Массонабор спины (Спинная специализация)',
    'Массонабор ног (Ножная специализация)',
    'Акцент на плечи (Дельтовидная специализация)',
    'Акцент на руки (Бицепс+Трицепс специализация)',
    'Кор и пресс (Core-специализация)',
    'Верхняя грудь (специализация)',
    'Средняя грудь (специализация)',
    'Нижняя грудь (специализация)',
    'Широчайшие (Ширина спины)',
    'Толщина спины (Средняя часть)',
    'Поясница (Разгибатели спины)',
    'Квадрицепс (специализация)',
    'Бицепс бедра (специализация)',
    'Ягодицы (специализация)',
    'Икры (специализация)',
    'Средняя дельта (Ширина плеч)',
    'Задняя дельта (специализация)',
    'Бицепс (специализация)',
    'Трицепс (специализация)',
    'Передняя дельта (специализация)',
    'Предплечье (специализация хвата)',
  ],
  both: [
    'Линейная периодизация (Linear Periodization)',
    'Волновая периодизация (Daily Undulating Periodization — DUP)',
    'Блочная периодизация (Block Periodization)',
    'Progressive Overload (базовый принцип)',
    'RPE-based Autoregulation',
    'Emom (Every Minute on the Minute)',
    '2×/нед на группу (база)',
    'Верх/Низ 4× (2×/нед на группу)',
    'Full Body 3× (группа ~3×/нед)',
    'Негативы (Эксцентрические повторения)',
    'Wave Loading (Волны нагрузки)',
  ],
};

export function getRecommendedMethods(direction: TrainingDirection): string[] {
  const dirs: TrainingDirection[] = direction === 'both' ? ['strength', 'bodybuilding', 'both'] : [direction];
  return [...new Set(dirs.flatMap(d => DIRECTION_METHOD_MAP[d] || []))];
}

export const SPLIT_METHOD_MAP: Record<string, string[]> = {
  fullbody_3: ['Двойная прогрессия (Double Progression)', 'Progressive Overload (базовый принцип)', 'RPE-based Autoregulation'],
  fullbody_2: ['Двойная прогрессия (Double Progression)', 'Progressive Overload (базовый принцип)', 'RPE-based Autoregulation'],
  fullbody_4: ['Volume Progression RP (мезо 2×/нед)', 'Двойная прогрессия (Double Progression)', 'Метаболический тренинг (Giant Sets для жиросжигания)'],
  upper_lower_4: ['Двойная прогрессия (Double Progression)', 'Volume Landmarks (MEV/MAV/MRV)', 'Суперсеты (Antagonist Supersets)'],
  upper_lower_3: ['Двойная прогрессия (Double Progression)', '2×/нед на группу (база)', 'Верх/Низ 4× (2×/нед на группу)'],
  ppl_6: ['Volume Progression RP (мезо 2×/нед)', 'Drop Sets (Дроп-сеты)', 'Myo-Reps', 'FST-7 (Fascia Stretch Training)'],
  rolling_3_1_3_1: ['Volume Progression RP (мезо 2×/нед)', 'Метаболический тренинг (Giant Sets для жиросжигания)', 'Drop Sets (Дроп-сеты)'],
  rolling_4_1: ['Двойная прогрессия (Double Progression)', 'Суперсеты (Antagonist Supersets)', 'Volume Landmarks (MEV/MAV/MRV)'],
  tpt_o_ttp: ['Volume Progression RP (мезо 2×/нед)', 'Метаболический тренинг (Giant Sets для жиросжигания)', 'FST-7 (Fascia Stretch Training)'],
  arnold_6: ['Суперсеты (Antagonist Supersets)', 'Трисеты / Гигантские сеты', 'Pre-Exhaust (Предварительное утомление)'],
  bro_5: ['Drop Sets (Дроп-сеты)', 'Myo-Reps', 'FST-7 (Fascia Stretch Training)', 'Gironda 8×8', '1.5 повторения'],
  phul_4: ['Двойная прогрессия (Double Progression)', 'Метод максимальных усилий (Max Effort Method)', 'Метод повторных усилий (Repeated Effort Method)'],
  push_pull_2: ['Двойная прогрессия (Double Progression)', 'Суперсеты (Antagonist Supersets)', '2×/нед на группу (база)'],
  torso_limb_4: ['Суперсеты (Antagonist Supersets)', 'Pre-Exhaust (Предварительное утомление)', 'Темп "Гипертрофичный" (3-1-1-0)'],
  strength_4: ['Линейная периодизация (Linear Periodization)', 'Метод максимальных усилий (Max Effort Method)', 'Кластерный метод (Cluster Sets)', 'Пауза в нижней точке (Bottom Pause)'],
};

export function getRecommendedMethodsForSplit(splitId: string): string[] {
  return SPLIT_METHOD_MAP[splitId] || [];
}
