import type { SymptomCategory } from './symptom-solver.types';
// Реэкспорт констант из types.ts для удобства импорта
export { SYMPTOM_CATEGORY_LABELS, SYMPTOM_CATEGORY_ICONS, PROBABILITY_LABELS, PROBABILITY_COLORS, EVIDENCE_LABELS, EVIDENCE_COLORS, URGENCY_LABELS, URGENCY_COLORS, URGENCY_ICONS } from './symptom-solver.types';
export const DRUG_LABELS: Record<string, string> = {
  testosterone: 'Тестостерон',
  reduce_dose: 'Снижение дозы',
  reduce_gh_dose: 'Снижение дозы GH',
  stop_gh: 'Прекращение GH',
  stop_finasteride: 'Отмена финастерида',
  reduce_melatonin: 'Снижение дозы мелатонина',
  reduce_diuretic: 'Отмена диуретика',
  reduce_insulin: 'Коррекция инсулина',
  reduce_ai: 'Отмена AI',
  glucose_urgent: 'Глюкоза (быстрые УД)',
  site_rotation: 'Ротация мест',
  night_splint: 'Ночной ортез',
  nsaids: 'НПВС (диклофенак)',
  astaxanthin: 'Астаксантин',
  enclomiphene: 'Энкломифен',
  metformin_mr: 'Метформин пролонг',
  avoid_alcohol: 'Отказ от алкоголя',
  therapy: 'Психотерапия',
  trenbolone: 'Тренболон',
  nandrolone: 'Нандролон (Дека)',
  methandienone: 'Метандиенон (Дианобол)',
  oxymetholone: 'Оксиметолон (Анадрол)',
  stanozolol: 'Станозолол (Винстрол)',
  oxandrolone: 'Оксандролон (Анавар)',
  masteron: 'Мастерон (Дростанолон)',
  boldenone: 'Болденон (Эквипойз)',
  turinabol: 'Туринабол',
  gh: 'Гормон роста (GH)',
  insulin: 'Инсулин',
  igf1: 'IGF-1',
  clenbuterol: 'Кленбутерол',
  t3: 'T3 (трийодтиронин)',
  t4: 'T4 (тироксин)',
  ai: 'Ингибиторы ароматазы (AI)',
  serm: 'SERM (тамоксифен/кломифен)',
  hcg: 'hCG',
  all_orals: 'Все 17α-алкилированные ААС',
  all_19nor: 'Все 19-нор-производные',
  all_aas: 'Все ААС',
  equipoise: 'Болденон (Эквипойз)',
  anadrol: 'Оксиметолон (Анадрол)',
  winstrol: 'Станозолол (Винстрол)',
  anavar: 'Оксандролон (Анавар)',
  deca: 'Нандролон (Дека)',
  clomid: 'Кломифен (Clomid)',
  nolvadex: 'Тамоксифен (Nolvadex)',
  rad140: 'RAD-140 (Testolone)',
  lgd4033: 'LGD-4033 (Ligandrol)',
  ostarine: 'Ostarine (MK-2866)',
  bpc157: 'BPC-157',
  tb500: 'TB-500',
  finasteride: 'Финастерид',
  dutasteride: 'Дутастерид',
  cabergoline: 'Каберголин',
  metformin: 'Метформин',
  telmisartan: 'Телмисартан',
  isotretinoin: 'Изотретиноин',
  ssri: 'SSRI (антидепрессанты)',
  diuretics: 'Диуретики',
  aspirin: 'Аспирин',
  omega3: 'Омега-3',
  calcium_supplements: 'Препараты кальция',
  estrogen_blockers: 'Блокаторы эстрогена',
  test_enan: 'Тестостерон энантат',
  test_cyp: 'Тестостерон ципионат',
  test_prop: 'Тестостерон пропионат',
  proviron: 'Местеролон (Провирон)',
  primobolan: 'Примоболан (Метенолон)',
  parabolan: 'Тренболон гексагидробензилкарбонат',
  npp: 'Нандролон фенилпропионат (NPP)',
  superdrol: 'Супердрол (Метилдростанолон)',
  halotestin: 'Флюоксиместерон (Галотестин)',
  ment: 'MENT (Тренболон ацетат)',
  insulin_rapid: 'Инсулин быстродействующий',
  lantus: 'Инсулин гларгин (Лантус)',
  mgf: 'MGF (Mechano Growth Factor)',
  peg_mgf: 'PEG-MGF',
  cjc1295: 'CJC-1295',
  ipamorelin: 'Ипаморелин',
  ghrp2: 'GHRP-2',
  ghrp6: 'GHRP-6',
  hexarelin: 'Гексарелин',
  semorelin: 'Семорелин',
  melanotan2: 'Меланотан II',
  pt141: 'PT-141 (Бремеланотид)',
  tesamorelin: 'Тесаморелин',
};

export const DRUG_CATEGORIES: Record<string, string> = {
  reduce_dose: 'Lifestyle',
  reduce_gh_dose: 'Lifestyle',
  reduce_melatonin: 'Lifestyle',
  reduce_diuretic: 'Lifestyle',
  reduce_insulin: 'Lifestyle',
  reduce_ai: 'Lifestyle',
  stop_gh: 'Lifestyle',
  stop_finasteride: 'Lifestyle',
  glucose_urgent: 'Lifestyle',
  site_rotation: 'Lifestyle',
  night_splint: 'Lifestyle',
  nsaids: 'Вспом.',
  astaxanthin: 'Вспом.',
  enclomiphene: 'SERM',
  metformin_mr: 'Вспом.',
  avoid_alcohol: 'Lifestyle',
  therapy: 'Lifestyle',
  testosterone: 'AAS',
  trenbolone: 'AAS',
  nandrolone: 'AAS',
  methandienone: 'AAS',
  oxymetholone: 'AAS',
  stanozolol: 'AAS',
  oxandrolone: 'AAS',
  masteron: 'AAS',
  boldenone: 'AAS',
  turinabol: 'AAS',
  gh: 'GH',
  insulin: 'Инсулин',
  igf1: 'Пептид',
  clenbuterol: 'Стим.',
  t3: 'Тиреоид',
  t4: 'Тиреоид',
  ai: 'Вспом.',
  serm: 'Вспом.',
  hcg: 'Вспом.',
  all_orals: 'Группа',
  all_19nor: 'Группа',
  all_aas: 'Группа',
  equipoise: 'AAS',
  anadrol: 'AAS',
  winstrol: 'AAS',
  anavar: 'AAS',
  deca: 'AAS',
  clomid: 'SERM',
  nolvadex: 'SERM',
  rad140: 'SARM',
  lgd4033: 'SARM',
  ostarine: 'SARM',
  bpc157: 'Пептид',
  tb500: 'Пептид',
  finasteride: 'Вспом.',
  dutasteride: 'Вспом.',
  cabergoline: 'Вспом.',
  metformin: 'Вспом.',
  telmisartan: 'Вспом.',
  isotretinoin: 'Вспом.',
  ssri: 'Вспом.',
  diuretics: 'Вспом.',
  aspirin: 'Вспом.',
  omega3: 'Вспом.',
  calcium_supplements: 'Вспом.',
  estrogen_blockers: 'Вспом.',
  test_enan: 'AAS',
  test_cyp: 'AAS',
  test_prop: 'AAS',
  proviron: 'AAS',
  primobolan: 'AAS',
  parabolan: 'AAS',
  npp: 'AAS',
  superdrol: 'AAS',
  halotestin: 'AAS',
  ment: 'AAS',
  insulin_rapid: 'Инсулин',
  lantus: 'Инсулин',
  mgf: 'Пептид',
  peg_mgf: 'Пептид',
  cjc1295: 'Пептид',
  ipamorelin: 'Пептид',
  ghrp2: 'Пептид',
  ghrp6: 'Пептид',
  hexarelin: 'Пептид',
  semorelin: 'Пептид',
  melanotan2: 'Пептид',
  pt141: 'Пептид',
  tesamorelin: 'Пептид',
};

export const DRUG_CAT_COLORS: Record<string, string> = {
  'AAS': '#e91e63',
  'GH': '#00bcd4',
  'Инсулин': '#ff5722',
  'Пептид': '#9c27b0',
  'Стим.': '#ff9800',
  'Тиреоид': '#4caf50',
  'Вспом.': '#607d8b',
  'Группа': '#795548',
  'SARM': '#3f51b5',
  'SERM': '#009688',
};

/** ПОЛНАЯ БАЗА СИМПТОМОВ */