// ========================================================
// SUPPORT SCREEN DATA — extracted constants
// ========================================================

import React from 'react';
import { MECHANISM_LABELS } from '../../../data/support-database';

export const INTERACTION_TYPE_LABELS: Record<string, { label: string; emoji: string; color: string }> = {
  synergy: { label: 'Синергия', emoji: '🔗', color: '#22c55e' },
  conflict: { label: 'Конфликт', emoji: '⚠️', color: '#ef4444' },
  caution: { label: 'Предупреждение', emoji: 'ℹ️', color: '#f59e0b' },
};

export const EFFECT_LABELS: Record<string, string> = {
  SMOOTH_FOCUS:'Плавная фокусировка — кофеин стимулирует, теанин сглаживает',
  OVERSTIMULATION:'Перевозбуждение — суммарная стимуляция ЦНС',
  HEART_STRAIN:'Нагрузка на сердце — риск тахикардии и гипертензии',
  ANXIETY_SPIKE:'Резкая тревога — выброс норадреналина и адреналина',
  IRON_ABSORB_UP:'Усиление всасывания железа',
  IRON_ABSORB_DOWN:'Снижение всасывания железа',
  MINERAL_COMPETE:'Конкуренция минералов за транспорт',
  COPPER_DEPLETION:'Истощение меди при высоком цинке',
  ABSORB_COMPETE:'Конкуренция за всасывание',
  BONE_SUPPORT:'Поддержка костной ткани — кальций + D3',
  CALCIUM_TARGETING:'Направление кальция в кости (К2)',
  VITD_ACTIVATION:'Активация витамина D магнием',
  IMMUNE_BALANCE:'Баланс иммунного ответа',
  COAGULATION_SHIFT:'Сдвиг свёртываемости крови',
  BLEED_RISK:'Повышенный риск кровотечений',
  ANTIINFLAMMATION_UP:'Усиление противовоспалительного эффекта',
  IMMUNE_MOD:'Иммуномодуляция',
  SLEEP_UP:'Улучшение качества сна',
  CALMING:'Успокаивающий эффект',
  HEART_MOD:'Модуляция сердечного ритма',
  SEROTONIN_SYNDROME:'Риск серотонинового синдрома',
  SEROTONIN_EXCESS:'Избыток серотонина',
  SEROTONIN_CRISIS:'Серотониновый криз',
  DRUG_CLEARANCE_UP:'Ускорение клиренса лекарств',
  ANTICOAG_DOWN:'Снижение антикоагулянтного эффекта',
  LIVER_PROTECT:'Защита печени — глутатион',
  ANTIOX_INTERFERE:'Интерференция с антиоксидантной терапией',
  NO_UP:'Повышение оксида азота',
  ABSORB_MOD:'Изменение всасывания',
  LIPIDS_UP:'Улучшение липидного профиля',
  BUGS_KILLED:'Уничтожение пробиотиков антибиотиками',
  MICROBIOME_UP:'Улучшение микробиома',
  SURVIVAL_UP:'Повышение выживаемости пробиотиков',
  ABSORB_DOWN:'Снижение всасывания',
  SEDATION_UP:'Усиление седации',
  SLEEP_ARCH_DISRUPT:'Нарушение архитектуры сна',
  LIVER_TOX:'Гепатотоксичность — токсические метаболиты',
  CNS_DEPRESSION:'Угнетение ЦНС',
  MOOD_INSTABILITY:'Нестабильность настроения',
  DRUG_EFFECT_DOWN:'Снижение эффекта препарата',
};

export const INTERACTION_SEVERITY_LABELS: Record<string, { label: string; color: string }> = {
  LOW: { label: 'Низкая', color: '#84cc16' },
  MEDIUM: { label: 'Средняя', color: '#f59e0b' },
  HIGH: { label: 'Высокая', color: '#ef4444' },
};

export const CATEGORY_LABELS: Record<string, { label: string; emoji: string }> = {
  vitamin: { label: 'Витамины', emoji: '🧪' },
  vitamins: { label: 'Витамины', emoji: '🧪' },
  minerals: { label: 'Минералы', emoji: '⚡' },
  mineral: { label: 'Минералы', emoji: '⚡' },
  amino: { label: 'Аминокислоты', emoji: '🧬' },
  aminoacid: { label: 'Аминокислоты', emoji: '🧬' },
  amino_acids: { label: 'Аминокислоты', emoji: '🧬' },
  peptide: { label: 'Пептиды', emoji: '🔬' },
  peptides: { label: 'Пептиды', emoji: '🔬' },
  antioxidant: { label: 'Антиоксиданты', emoji: '🛡' },
  antioxidants: { label: 'Антиоксиданты', emoji: '🛡' },
  immune: { label: 'Иммунитет', emoji: '🛡' },
  hormone: { label: 'Гормоны', emoji: '⚕️' },
  hormones: { label: 'Гормоны', emoji: '⚕️' },
  hormonal: { label: 'Гормоны', emoji: '⚕️' },
  fatty_acid: { label: 'Жирные кислоты', emoji: '💧' },
  fatty_acids: { label: 'Жирные кислоты', emoji: '💧' },
  lipids: { label: 'Липиды', emoji: '💧' },
  nootropic: { label: 'Ноотропы', emoji: '🧠' },
  neuro: { label: 'Нервная система', emoji: '🧠' },
  brain: { label: 'Мозг', emoji: '🧠' },
  cardio: { label: 'Сердечно-сосудистая', emoji: '❤️' },
  heart: { label: 'Сердце', emoji: '❤️' },
  vascular: { label: 'Сосуды', emoji: '🩸' },
  VESSELS: { label: 'Сосуды', emoji: '🩸' },
  GI: { label: 'ЖКТ', emoji: '🫃' },
  liver: { label: 'Печень', emoji: '🍃' },
  kidney: { label: 'Почки', emoji: '🫘' },
  mitochondria: { label: 'Митохондрии', emoji: '🔋' },
  energy: { label: 'Энергия', emoji: '⚡' },
  adaptogen: { label: 'Адаптогены', emoji: '🌿' },
  fungi: { label: 'Грибы', emoji: '🍄' },
  probiotic: { label: 'Пробиотики', emoji: '🦠' },
  prebiotic: { label: 'Пребиотики', emoji: '🦠' },
  postbiotic: { label: 'Постбиотики', emoji: '🦠' },
  skin: { label: 'Кожа', emoji: '✨' },
  bone: { label: 'Кости и суставы', emoji: '🦴' },
  joint: { label: 'Суставы', emoji: '🦴' },
  joints: { label: 'Суставы', emoji: '🦴' },
  blood: { label: 'Кровь', emoji: '💉' },
  detox: { label: 'Детокс', emoji: '🧹' },
  antiaging: { label: 'Антивозраст', emoji: '⏳' },
  epigenetic: { label: 'Эпигенетика', emoji: '🧬' },
  methylation: { label: 'Метилирование', emoji: '🔄' },
  DNA: { label: 'ДНК', emoji: '🧬' },
  pharma: { label: 'Фармацевтика', emoji: '💊' },
  polyphenol: { label: 'Полифенолы', emoji: '🍃' },
  sleep: { label: 'Сон', emoji: '😴' },
  calming: { label: 'Успокаивающие', emoji: '🧘' },
  anxiolytic: { label: 'Противотревожные', emoji: '🧘' },
  antiinflammatory: { label: 'Противовоспалительные', emoji: '🔥' },
  anti_inflammatory: { label: 'Противовоспалительные', emoji: '🔥' },
  antiviral: { label: 'Противовирусные', emoji: '🦠' },
  antimicrobial: { label: 'Антимикробные', emoji: '🦠' },
  antibiotic: { label: 'Антибиотики', emoji: '💊' },
  thyroid: { label: 'Щитовидная железа', emoji: '🦋' },
  hair: { label: 'Волосы', emoji: '💇' },
  lung: { label: 'Лёгкие', emoji: '🫁' },
  LUNGS: { label: 'Лёгкие', emoji: '🫁' },
  electrolyte: { label: 'Электролиты', emoji: '⚡' },
  trace: { label: 'Микроэлементы', emoji: '⚡' },
  eye: { label: 'Зрение', emoji: '👁️' },
  vision: { label: 'Зрение', emoji: '👁️' },
  oral: { label: 'Полость рта', emoji: '🦷' },
  male: { label: 'Мужское здоровье', emoji: '♂️' },
  female: { label: 'Женское здоровье', emoji: '♀️' },
  prostate: { label: 'Простата', emoji: '🫘' },
  pain: { label: 'Обезболивающие', emoji: '💊' },
  analgesic: { label: 'Анальгетики', emoji: '💊' },
  insulin: { label: 'Инсулин', emoji: '💉' },
  glucose: { label: 'Глюкоза', emoji: '🍬' },
  metabolism: { label: 'Метаболизм', emoji: '⚡' },
  METABOLIC: { label: 'Метаболизм', emoji: '⚡' },
  repair: { label: 'Регенерация', emoji: '🔄' },
  regeneration: { label: 'Регенерация', emoji: '🔄' },
  cell: { label: 'Клеточное здоровье', emoji: '🧫' },
  hydration: { label: 'Гидратация', emoji: '💧' },
  collagen: { label: 'Коллаген', emoji: '🧶' },
  stress: { label: 'Стресс', emoji: '😰' },
  mood: { label: 'Настроение', emoji: '😊' },
  testosterone: { label: 'Тестостерон', emoji: '💪' },
  HPG: { label: 'Гипоталамус-гипофиз-гонады', emoji: '🧬' },
  HPT: { label: 'Гипоталамус-гипофиз-тиреоид', emoji: '🦋' },
  HPA: { label: 'Гипоталамус-гипофиз-надпочечники', emoji: '🧬' },
  nerve: { label: 'Нервы', emoji: '🧠' },
  tendon: { label: 'Сухожилия', emoji: '🦵' },
  muscle: { label: 'Мышцы', emoji: '💪' },
  anabolic: { label: 'Анаболики', emoji: '💪' },
  fat_loss: { label: 'Жиросжигание', emoji: '🔥' },
  performance: { label: 'Производительность', emoji: '🏃' },
  recovery: { label: 'Восстановление', emoji: '😴' },
  anti_glycation: { label: 'Антигликация', emoji: '🍬' },
  enzyme: { label: 'Ферменты', emoji: '🧪' },
  enzymes: { label: 'Ферменты', emoji: '🧪' },
  herbs: { label: 'Растения и травы', emoji: '🌿' },
  nootropics: { label: 'Ноотропы', emoji: '🧠' },
  adaptogens: { label: 'Адаптогены', emoji: '🌿' },
  probiotics: { label: 'Пробиотики', emoji: '🦠' },
  mushrooms: { label: 'Грибы', emoji: '🍄' },
  electrolytes: { label: 'Электролиты', emoji: '⚡' },
  other: { label: 'Другое', emoji: '📦' },
};

export const MECH_TRANSLATIONS_RU: Record<string, string> = {
  'antioxidant': 'Антиоксидант', 'anti_inflammatory': 'Противовоспалительное', 'hepatoprotective': 'Гепатопротектор',
  'nephroprotective': 'Нефропротектор', 'cardioprotective': 'Кардиопротектор', 'neuroprotective': 'Нейропротектор',
  'immunomodulator': 'Иммуномодулятор', 'adaptogen': 'Адаптоген', 'nootropic': 'Ноотроп',
  'vasodilator': 'Вазодилататор', 'antiplatelet': 'Антиагрегант', 'hypolipidemic': 'Гиполипидемическое',
  'hypoglycemic': 'Гипогликемическое', 'anabolic': 'Анаболическое', 'anticatabolic': 'Антикатаболическое',
  'ergogenic': 'Эргогенное', 'lipotropic': 'Липотропное', 'thermogenic': 'Термогенное',
  'estrogenic': 'Эстрогенное', 'antiestrogenic': 'Антиэстрогенное', 'androgenic': 'Андрогенное',
  'antiandrogenic': 'Антиандрогенное', 'progestogenic': 'Прогестогенное', 'antioxidant_enzymatic': 'Ферментативный антиоксидант',
  'mitochondrial': 'Митохондриальное', 'neurotransmitter': 'Нейротрансмиттер', 'hormone_precursor': 'Предшественник гормонов',
  'collagen_synthesis': 'Синтез коллагена', 'bone_mineralization': 'Минерализация костей',
  'insulin_sensitizer': 'Сенситизатор инсулина', 'cortisol_modulator': 'Модулятор кортизола',
  'sleep_aid': 'Снотворное', 'anxiolytic': 'Анксиолитик', 'antidepressant': 'Антидепрессант',
  'analgesic': 'Анальгетик', 'anti_spasmodic': 'Спазмолитик', 'digestive': 'Пищеварительное',
  'probiotic': 'Пробиотик', 'prebiotic': 'Пребиотик', 'enzyme': 'Фермент',
  'electrolyte': 'Электролит', 'diuretic': 'Диуретик', 'detox': 'Детокс',
  'chelator': 'Хелатор', 'methylation': 'Метилирование', 'energy_production': 'Производство энергии',
  'protein_synthesis': 'Синтез белка', 'glucose_metabolism': 'Метаболизм глюкозы', 'lipid_metabolism': 'Метаболизм липидов',
  'calcium_metabolism': 'Метаболизм кальция', 'thyroid_function': 'Функция щитовидной',
  'adrenal_support': 'Поддержка надпочечников', 'pituitary_support': 'Поддержка гипофиза',
  'cofactor': 'Кофактор', 'coenzyme': 'Коэнзим', 'electron_transport': 'Транспорт электронов',
  'oxygen_transport': 'Транспорт кислорода', 'wound_healing': 'Заживление ран',
  'tissue_repair': 'Регенерация тканей', 'anti_fibrotic': 'Антифибротическое',
  // Phase 6+: expanded mechanism translations
  'anti_aging': 'Антивозрастное', 'DNA_repair': 'Репарация ДНК', 'telomere_protection': 'Защита теломер',
  'stem_cell_activation': 'Активация стволовых клеток', 'autophagy': 'Аутофагия', 'senolytic': 'Сенолитик',
  'sirtuin_activation': 'Активация сиртуинов', 'NAD_booster': 'Повышение NAD+', 'AMPK_activation': 'Активация AMPK',
  'mTOR_inhibition': 'Ингибирование mTOR', 'mitochondrial_biogenesis': 'Биогенез митохондрий',
  'cognitive_enhancer': 'Улучшение когнитивных функций', 'memory_enhancer': 'Улучшение памяти',
  'focus_enhancer': 'Улучшение концентрации', 'BDNF_booster': 'Повышение BDNF',
  'NGF_booster': 'Повышение NGF', 'acetylcholine_precursor': 'Предшественник ацетилхолина',
  'dopamine_modulator': 'Модулятор дофамина', 'serotonin_modulator': 'Модулятор серотонина',
  'GABA_modulator': 'Модулятор ГАМК', 'glutamate_modulator': 'Модулятор глутамата',
  'blood_sugar_control': 'Контроль сахара', 'insulin_sensitivity': 'Чувствительность к инсулину',
  'carb_blocker': 'Блокатор углеводов', 'fat_blocker': 'Блокатор жиров',
  'appetite_suppressant': 'Подавление аппетита', 'metabolic_booster': 'Ускорение метаболизма',
  'thyroid_support': 'Поддержка щитовидной', 'testosterone_booster': 'Повышение тестостерона',
  'estrogen_modulator': 'Модулятор эстрогена', 'DHT_blocker': 'Блокатор ДГТ',
  'prolactin_modulator': 'Модулятор пролактина', 'SHBG_modulator': 'Модулятор ГСПГ',
  'libido_enhancer': 'Усиление либидо', 'fertility_support': 'Поддержка фертильности',
  'sperm_quality': 'Качество спермы', 'prostate_health': 'Здоровье простаты',
  'joint_protection': 'Защита суставов', 'cartilage_repair': 'Восстановление хряща',
  'bone_density': 'Плотность костей', 'muscle_protein_synthesis': 'Синтез мышечного белка',
  'muscle_recovery': 'Восстановление мышц', 'endurance_enhancer': 'Повышение выносливости',
  'strength_enhancer': 'Повышение силы', 'VO2_max': 'МПК (VO2max)',
  'lactate_buffer': 'Буфер лактата', 'nitric_oxide_booster': 'Повышение оксида азота',
  'blood_flow': 'Улучшение кровотока', 'vasodilation': 'Расширение сосудов',
  'blood_pressure_lowering': 'Снижение давления', 'cholesterol_lowering': 'Снижение холестерина',
  'triglyceride_lowering': 'Снижение триглицеридов', 'HDL_increase': 'Повышение ЛПВП',
  'LDL_lowering': 'Снижение ЛПНП', 'homocysteine_lowering': 'Снижение гомоцистеина',
  'liver_detox': 'Детокс печени', 'liver_regeneration': 'Регенерация печени',
  'bile_flow': 'Отток желчи', 'gallbladder_support': 'Поддержка желчного',
  'glutathione_synthesis': 'Синтез глутатиона', 'heavy_metal_detox': 'Детокс тяжёлых металлов',
  'kidney_protection': 'Защита почек', 'uric_acid_lowering': 'Снижение мочевой кислоты',
  'diuretic_natural': 'Природный диуретик', 'gut_health': 'Здоровье кишечника',
  'microbiome_support': 'Поддержка микробиома', 'digestive_enzyme': 'Пищеварительный фермент',
  'gut_barrier': 'Кишечный барьер', 'IBS_relief': 'Облегчение СРК',
  'antimicrobial': 'Антимикробное', 'antibacterial': 'Антибактериальное',
  'antiviral': 'Противовирусное', 'antifungal': 'Противогрибковое',
  'antiparasitic': 'Противопаразитарное', 'immune_booster': 'Усиление иммунитета',
  'anti_allergic': 'Противоаллергическое', 'antihistamine': 'Антигистаминное',
  'mast_cell_stabilizer': 'Стабилизатор тучных клеток', 'anti_cancer': 'Противораковое',
  'skin_health': 'Здоровье кожи', 'hair_growth': 'Рост волос',
  'nail_strength': 'Укрепление ногтей', 'hydration': 'Гидратация',
  'UV_protection': 'Защита от УФ', 'acne_treatment': 'Лечение акне',
  'eye_health': 'Здоровье глаз', 'vision_support': 'Поддержка зрения',
  'macular_protection': 'Защита макулы', 'cataract_prevention': 'Профилактика катаракты',
  'stress_reduction': 'Снижение стресса', 'anxiety_relief': 'Облегчение тревоги',
  'mood_stabilizer': 'Стабилизация настроения', 'sleep_quality': 'Качество сна',
  'circadian_rhythm': 'Циркадный ритм', 'melatonin_precursor': 'Предшественник мелатонина',
  'general': 'Общее действие', 'other': 'Прочее', 'energy': 'Энергия',
};

export const ORGAN_MECHANISMS: Record<string, string[]> = {
  cardio: ['cardioprotective', 'vasodilator', 'antiplatelet', 'hypolipidemic', 'electrolyte', 'oxygen_transport', 'anticoagulant'],
  liver: ['hepatoprotective', 'detox', 'antioxidant', 'antioxidant_enzymatic', 'lipid_metabolism', 'glucose_metabolism', 'insulin_sensitizer', 'anti_fibrotic', 'lipotropic'],
  kidney: ['nephroprotective', 'diuretic', 'electrolyte', 'detox', 'chelator', 'anti_fibrotic'],
  lung: ['anti_inflammatory', 'antioxidant', 'vasodilator', 'anti_spasmodic'],
  brain: ['neuroprotective', 'nootropic', 'neurotransmitter', 'antidepressant', 'anxiolytic', 'sleep_aid', 'analgesic', 'anti_spasmodic'],
  bones: ['bone_mineralization', 'collagen_synthesis', 'calcium_metabolism', 'tissue_repair', 'anti_inflammatory'],
  skin: ['collagen_synthesis', 'antioxidant', 'wound_healing', 'tissue_repair', 'anti_inflammatory'],
  thyroid: ['thyroid_function', 'hormone_precursor', 'energy_production', 'metabolic'],
  pancreas: ['hypoglycemic', 'insulin_sensitizer', 'glucose_metabolism', 'anti_inflammatory'],
  blood: ['oxygen_transport', 'antiplatelet', 'hypolipidemic', 'methylation', 'cofactor'],
  immune: ['immunomodulator', 'antioxidant', 'anti_inflammatory', 'probiotic', 'prebiotic'],
  gi: ['digestive', 'probiotic', 'prebiotic', 'enzyme', 'anti_inflammatory', 'hepatoprotective'],
  hormones: ['hormone_precursor', 'estrogenic', 'antiestrogenic', 'androgenic', 'antiandrogenic', 'progestogenic', 'adrenal_support', 'pituitary_support', 'cortisol_modulator'],
  male: ['androgenic', 'antiestrogenic', 'anabolic', 'protein_synthesis', 'hormone_precursor'],
  female: ['estrogenic', 'progestogenic', 'antiandrogenic', 'antiestrogenic', 'bone_mineralization', 'calcium_metabolism'],
  antiaging: ['mitochondrial', 'antioxidant', 'antioxidant_enzymatic', 'collagen_synthesis', 'methylation', 'energy_production'],
  energy: ['energy_production', 'ergogenic', 'thermogenic', 'mitochondrial', 'electron_transport', 'lipid_metabolism', 'glucose_metabolism'],
  recovery: ['tissue_repair', 'wound_healing', 'collagen_synthesis', 'anti_inflammatory', 'protein_synthesis', 'anticatabolic', 'anabolic'],
};

export const getCategoryInfo = (cat: string): { label: string; emoji: string } => {
  const safeCat = cat || 'Без категории';
  const TYPE_LABELS: Record<string, { label: string; emoji: string }> = {
    vitamin: { label: '💊 Витамины', emoji: '💊' },
    mineral: { label: '🧂 Минералы', emoji: '🧂' },
    amino_acid: { label: '🧬 Аминокислоты', emoji: '🧬' },
    herb: { label: '🌿 Травы и растения', emoji: '🌿' },
    hormone: { label: '⚖️ Гормоны', emoji: '⚖️' },
    peptide: { label: '🧬 Пептиды', emoji: '🧬' },
    antioxidant: { label: '🛡️ Антиоксиданты', emoji: '🛡️' },
    enzyme: { label: '⚙️ Ферменты', emoji: '⚙️' },
    probiotic: { label: '🦠 Пробиотики', emoji: '🦠' },
    fatty_acid: { label: '🐟 Жирные кислоты', emoji: '🐟' },
    nootropic: { label: '🧠 Ноотропы', emoji: '🧠' },
    adaptogen: { label: '🌿 Адаптогены', emoji: '🌿' },
    mineral_complex: { label: '🧂 Минеральные комплексы', emoji: '🧂' },
    vitamin_mineral: { label: '💊 Витаминно-минеральные', emoji: '💊' },
    mushroom: { label: '🍄 Грибы', emoji: '🍄' },
    polyphenol: { label: '🫐 Полифенолы', emoji: '🫐' },
    antimicrobial: { label: '🦠 Антимикробные', emoji: '🦠' },
    pharma: { label: '💊 Фармакология', emoji: '💊' },
    supplement: { label: '💪 Добавки', emoji: '💪' },
    no_organ: { label: '📦 Другое', emoji: '📦' },
  };
  const GROUP_LABELS: Record<string, { label: string; emoji: string }> = {
    liver: { label: '🫁 Печень', emoji: '🫁' },
    cardio: { label: '❤️ Сердце и сосуды', emoji: '❤️' },
    neuro: { label: '🧠 Нервная система', emoji: '🧠' },
    immune: { label: '🛡️ Иммунитет', emoji: '🛡️' },
    kidney: { label: '🫘 Почки', emoji: '🫘' },
    joints: { label: '🦴 Суставы', emoji: '🦴' },
    bone: { label: '🦴 Кости', emoji: '🦴' },
    skin: { label: '🧴 Кожа', emoji: '🧴' },
    lung: { label: '🫁 Лёгкие', emoji: '🫁' },
    eye: { label: '👁 Глаза', emoji: '👁' },
    blood: { label: '🩸 Кровь', emoji: '🩸' },
    thyroid: { label: '🦋 Щитовидная железа', emoji: '🦋' },
    muscle: { label: '💪 Мышцы', emoji: '💪' },
    recovery: { label: '🔄 Восстановление', emoji: '🔄' },
    gi: { label: '🫃 ЖКТ', emoji: '🫃' },
    vitamins: { label: '💊 Витамины', emoji: '💊' },
    minerals: { label: '🧂 Минералы', emoji: '🧂' },
    amino_acids: { label: '🧬 Аминокислоты', emoji: '🧬' },
    herbs: { label: '🌿 Травы', emoji: '🌿' },
    peptides: { label: '🧬 Пептиды', emoji: '🧬' },
    nootropics: { label: '🧠 Ноотропы', emoji: '🧠' },
    adaptogens: { label: '🌿 Адаптогены', emoji: '🌿' },
    hormones: { label: '⚖️ Гормоны', emoji: '⚖️' },
    enzymes: { label: '⚙️ Ферменты', emoji: '⚙️' },
    probiotics: { label: '🦠 Пробиотики', emoji: '🦠' },
    fatty_acids: { label: '🐟 Жирные кислоты', emoji: '🐟' },
    mushrooms: { label: '🍄 Грибы', emoji: '🍄' },
    electrolytes: { label: '⚡ Электролиты', emoji: '⚡' },
    antioxidants: { label: '🛡️ Антиоксиданты', emoji: '🛡️' },
    antiinflammatory: { label: '🔥 Противовоспалительное', emoji: '🔥' },
    anxiolytic: { label: '😌 Противотревожное', emoji: '😌' },
    antiaging: { label: '🕰 Антивозрастное', emoji: '🕰' },
    metabolism: { label: '⚡ Метаболизм', emoji: '⚡' },
    mood: { label: '😊 Настроение', emoji: '😊' },
    analgesic: { label: '💊 Обезболивающее', emoji: '💊' },
    other: { label: '📦 Другое', emoji: '📦' },
  };
  return CATEGORY_LABELS[safeCat] || TYPE_LABELS[safeCat] || GROUP_LABELS[safeCat] || (TYPE_LABELS_RU[safeCat] ? { label: TYPE_LABELS_RU[safeCat], emoji: '📦' } : { label: safeCat, emoji: '📦' });
};

export const TYPE_LABELS_RU: Record<string, string> = {
  vitamin: 'Витамины', mineral: 'Минералы', minerals: 'Минералы', amino_acid: 'Аминокислоты', amino: 'Аминокислоты',
  herb: 'Растения и травы', hormone: 'Гормоны', peptide: 'Пептиды',
  antioxidant: 'Антиоксиданты', enzyme: 'Ферменты', probiotic: 'Пробиотики',
  fatty_acid: 'Жирные кислоты', nootropic: 'Ноотропы', adaptogen: 'Адаптогены',
  joint: 'Суставы и кости', liver: 'Защита печени', kidney: 'Защита почек',
  heart: 'Сердце и сосуды', immune: 'Иммунитет', energy: 'Энергия',
  sleep: 'Сон', antiaging: 'Антивозраст', male: 'Мужское здоровье',
  female: 'Женское здоровье', sports: 'Спорт', digestion: 'Пищеварение',
  other: 'Другое', supplement: 'Добавки',
  polyphenol: 'Полифенолы', fungi: 'Грибы', metabiotic: 'Метабиотики',
  paraprobiotic: 'Парапробиотики', postbiotic: 'Постбиотики', prebiotic: 'Пребиотики',
  symbiotic: 'Симбиотики',   pharma: 'Фармакологические препараты', complex: 'Комплексы',
  brand: 'Бренды', calcium: 'Кальций', magnesium: 'Магний', zinc: 'Цинк',
  iron: 'Железо', potassium: 'Калий', sodium: 'Натрий', selenium: 'Селен',
  iodine: 'Йод', chromium: 'Хром', manganese: 'Марганец', copper: 'Медь',
  boron: 'Бор', molybdenum: 'Молибден', electrolyte: 'Электролиты',
  protein: 'Белки', carbohydrate: 'Углеводы', fat: 'Жиры',
  DIRECT: 'Направленное', GLOBAL: 'Общее', SYSTEMIC: 'Системное',
  AXIS: 'Гормональные оси', SYSTEM: 'Системы', ORGAN: 'Органы',
  SUBSTANCE: 'Вещества', INTERACTION: 'Взаимодействия', MECHANISM: 'Механизмы',
  RISK: 'Риски', caution: 'Предупреждения', conflict: 'Конфликты', synergy: 'Синергии',
  gut: 'ЖКТ', hepatoprotector: 'Защита печени', metabolic: 'Метаболизм',
  gastrointestinal: 'ЖКТ и пищеварение', cardioprotector: 'Сердце и сосуды',
  anti_aging: 'Антивозраст', stimulant: 'Стимуляторы', immunomodulator: 'Иммунитет',
  neuroprotector: 'Нейропротекторы', antiinflammatory: 'Противовоспалительные',
  anti_inflammatory: 'Противовоспалительные', antimicrobial: 'Антимикробные',
  anxiolytic: 'Противотревожные', antidepressant: 'Антидепрессанты',
  anticoagulant: 'Антикоагулянты', urinary_protector: 'Урологические',
  eye_protector: 'Защита глаз', respiratory: 'Дыхательная система',
  bone: 'Кости и суставы', recovery: 'Восстановление', anabolic: 'Анаболические',
  lipid: 'Липидные', beauty: 'Красота', multivitamin: 'Мультивитамины', marker: 'Маркеры',
  bile_acid: 'Желчные кислоты',
  choleretic: 'Желчегонные', thyroid: 'Щитовидная железа',
  mitochondrial: 'Митохондриальные', hematologic: 'Гематология',
};

// Class base-name grouping for catalog badges
export const CLASS_BASE_NAMES: Record<string, { label: string; emoji: string; match: RegExp }> = {
  magnesium: { label: 'Магний', emoji: '⚡', match: /magnesium|магний/i },
  zinc: { label: 'Цинк', emoji: '🛡', match: /zinc|цинк/i },
  vitamin_d: { label: 'Витамин D', emoji: '☀️', match: /vitamin\s*d|витамин\s*d|cholecalciferol|кальциферол/i },
  omega: { label: 'Омега-3/6/9', emoji: '🐟', match: /omega|омега|epa|dha|ala/i },
  creatine: { label: 'Креатин', emoji: '💪', match: /creatine|креатин/i },
  collagen: { label: 'Коллаген', emoji: '🧶', match: /collagen|коллаген/i },
  ashwagandha: { label: 'Ашваганда', emoji: '🌿', match: /ashwagandha|ашваганд/i },
  curcumin: { label: 'Куркумин', emoji: '🟡', match: /curcumin|куркум|turmeric/i },
  coq10: { label: 'Коэнзим Q10', emoji: '🔋', match: /coq10|коэнзим|убихинон|ubiquinone|ubiquinol/i },
  vitamin_c: { label: 'Витамин C', emoji: '🍊', match: /vitamin\s*c|витамин\s*c|ascorb|аскорб/i },
  vitamin_b: { label: 'Витамины B', emoji: '🧪', match: /vitamin\s*b[123569]|b12|b6|b3|b1|b2|b5|b9|b7|thiamine|riboflavin|niacin|pyridoxine|folate|cobalamin|тиамин|рибофлавин|ниацин|пантотен|пиридоксин|фолат|биотин|кобаламин/i },
  iron: { label: 'Железо', emoji: '🩸', match: /iron|желез|ferrous|ferric|ferrum/i },
  calcium: { label: 'Кальций', emoji: '🦴', match: /calcium|кальци/i },
  melatonin: { label: 'Мелатонин', emoji: '😴', match: /melatonin|мелатонин/i },
  berberine: { label: 'Берберин', emoji: '🌿', match: /berberine|берберин/i },
  ginseng: { label: 'Женьшень', emoji: '🌱', match: /ginseng|женьшен/i },
  vitamin_e: { label: 'Витамин E', emoji: '🧴', match: /vitamin\s*e|витамин\s*e|tocopherol|токоферол/i },
  vitamin_a: { label: 'Витамин A', emoji: '👁', match: /vitamin\s*a|витамин\s*a|retinol|ретинол|carotenoid|каротиноид/i },
  vitamin_k: { label: 'Витамин K', emoji: '🩸', match: /vitamin\s*k|витамин\s*k|phylloquinone|menaquinone|филлохинон/i },
  selenium: { label: 'Селен', emoji: '🛡', match: /selenium|селен|selenomethionine/i },
  potassium: { label: 'Калий', emoji: '🍌', match: /potassium|кали/i },
  sodium: { label: 'Натрий', emoji: '🧂', match: /sodium|натри/i },
  iodine: { label: 'Йод', emoji: '🦋', match: /iodine|йод|iodide/i },
  chromium: { label: 'Хром', emoji: '🍬', match: /chromium|хром|picolinate/i },
  probiotics: { label: 'Пробиотики', emoji: '🦠', match: /probiotic|пробиотик|lactobacillus|bifido/i },
  nac: { label: 'NAC', emoji: '🫁', match: /nac|acetylcysteine|ацетилцистеин/i },
  ala: { label: 'Альфа-липоевая к-та', emoji: '⚡', match: /lipoic|липоев/i },
  carnitine: { label: 'L-Карнитин', emoji: '🔥', match: /carnitine|карнитин|alcar/i },
  theanine: { label: 'L-Теанин', emoji: '☕', match: /theanine|теанин/i },
  beta_alanine: { label: 'Бета-аланин', emoji: '💪', match: /beta.alanine|бета.аланин|carnosine|карнозин/i },
  citrulline: { label: 'Цитруллин', emoji: '💉', match: /citrulline|цитруллин/i },
  arginine: { label: 'Аргинин', emoji: '🔴', match: /arginine|аргинин/i },
  taurine: { label: 'Таурин', emoji: '⚡', match: /taurine|таурин/i },
  tyrosine: { label: 'L-Тирозин', emoji: '🧠', match: /tyrosine|тирозин/i },
  gaba: { label: 'GABA', emoji: '😌', match: /gaba|габа/i },
  milk_thistle: { label: 'Расторопша', emoji: '🫁', match: /milk.thistle|расторопш|silymarin|силимарин/i },
  ginger: { label: 'Имбирь', emoji: '🫚', match: /ginger|имбир|zingiber/i },
  garlic: { label: 'Чеснок', emoji: '🧄', match: /garlic|чеснок|allicin|аллицин/i },
  cinnamon: { label: 'Корица', emoji: '🟤', match: /cinnamon|кориц/i },
  saw_palmetto: { label: 'Пальма сереноа', emoji: '🌴', match: /saw.palmetto|пальма|сереноа/i },
  rhodiola: { label: 'Родиола', emoji: '🌹', match: /rhodiola|родиол/i },
  maca: { label: 'Мака', emoji: '🥔', match: /maca|мака/i },
  tribulus: { label: 'Трибулус', emoji: '💪', match: /tribulus|трибулус/i },
  tongkat_ali: { label: 'Тонгкат Али', emoji: '🌳', match: /tongkat|тонкат/i },
  dhea: { label: 'DHEA', emoji: '⚡', match: /dhea|дегидроэпиандростерон/i },
  pregnenolone: { label: 'Прегненолон', emoji: '🧬', match: /pregnenolone|прегненолон/i },
  htp: { label: '5-HTP', emoji: '😊', match: /5.htp|hydroxytryptophan|гидрокситриптофан/i },
  glycine: { label: 'Глицин', emoji: '💤', match: /glycine|глицин/i },
  glutamine: { label: 'Глютамин', emoji: '🔄', match: /glutamine|глютамин/i },
  lysine: { label: 'Лизин', emoji: '🛡', match: /lysine|лизин/i },
  hyaluronic: { label: 'Гиалуроновая к-та', emoji: '💧', match: /hyaluronic|гиалурон/i },
  glucosamine: { label: 'Глюкозамин', emoji: '🦴', match: /glucosamine|глюкозамин/i },
  chondroitin: { label: 'Хондроитин', emoji: '🦴', match: /chondroitin|хондроитин/i },
  msm: { label: 'MSM', emoji: '🔧', match: /msm|метилсульфонилметан/i },
  quercetin: { label: 'Кверцетин', emoji: '🧅', match: /quercetin|кверцетин/i },
  resveratrol: { label: 'Ресвератрол', emoji: '🍇', match: /resveratrol|ресвератрол/i },
  nmn: { label: 'NMN/NR/NAD+', emoji: '⏳', match: /nmn|nicotinamide.mononucleotide|nr|nad/i },
  pqq: { label: 'PQQ', emoji: '🔋', match: /pqq|pyrroloquinoline/i },
  bacopa: { label: 'Бакопа', emoji: '🌿', match: /bacopa|бакопа/i },
  ginkgo: { label: 'Гинкго', emoji: '🍃', match: /ginkgo|гинкго/i },
  lions_mane: { label: 'Ежовик гребенчатый', emoji: '🍄', match: /lion.*mane|ежовик|hericium/i },
  reishi: { label: 'Рейши', emoji: '🍄', match: /reishi|рейши|ganoderma/i },
  cordyceps: { label: 'Кордицепс', emoji: '🍄', match: /cordyceps|кордицепс/i },
  chaga: { label: 'Чага', emoji: '🍄', match: /chaga|чага|inonotus/i },
  tudca: { label: 'TUDCA', emoji: '🫁', match: /tudca|тауроурсодезоксихол/i },
  black_cumin: { label: 'Чёрный тмин', emoji: '⚫', match: /black.cumin|тмин|nigella/i },
  valerian: { label: 'Валериана', emoji: '😴', match: /valerian|валериан/i },
  passionflower: { label: 'Пассифлора', emoji: '🌸', match: /passionflower|пассифлор|passiflora/i },
  chamomile: { label: 'Ромашка', emoji: '🌼', match: /chamomile|ромашк/i },
  peppermint: { label: 'Мята', emoji: '🌿', match: /peppermint|мят/i },
  echinacea: { label: 'Эхинацея', emoji: '🌻', match: /echinacea|эхинаце/i },
  elderberry: { label: 'Бузина', emoji: '🫐', match: /elderberry|бузин|sambucus/i },
  astaxanthin: { label: 'Астаксантин', emoji: '🔴', match: /astaxanthin|астаксантин/i },
  lutein: { label: 'Лютеин', emoji: '👁', match: /lutein|лютеин|zeaxanthin|зеаксантин/i },
  grape_seed: { label: 'Виноградные косточки', emoji: '🍇', match: /grape.seed|виноград.*кост/i },
  green_tea: { label: 'Зелёный чай (EGCG)', emoji: '🍵', match: /green.tea|зелён.*чай|egcg|катехин/i },
  spirulina: { label: 'Спирулина/Хлорелла', emoji: '🌿', match: /spirulina|хлорел|спирулин/i },
  moringa: { label: 'Моринга', emoji: '🌳', match: /moringa|моринг/i },
  papaya_enzyme: { label: 'Папаин/Бромелайн', emoji: '🍍', match: /papain|bromelain|папаин|бромелайн/i },
  bile_salts: { label: 'Желчные соли', emoji: '💧', match: /bile.salt|желчн/i },
  betaine_hcl: { label: 'Бетаин HCl', emoji: '🧪', match: /betaine|бетаин|hcl/i },
};

export const SYNERGY_COLORS: Record<string, string> = {
  synergistic: '#22c55e',
  additive: '#84cc16',
  potentiative: '#3b82f6',
  complementary: '#8b5cf6',
  antagonistic: '#ef4444',
};

export const SUPPORT_CLASS_LABELS: Record<string, string> = {
  support: '💊 Поддержка',
  peptide_regenerative: '🧬 Регенерация',
  peptide_nootropic: '🧠 Ноотропы',
  peptide_immune: '🛡 Иммунная',
  bady: '🌿 БАДы',
};

export const MECH_LABELS: Record<string,string> = { ...MECHANISM_LABELS,
  'NAD_PATHWAY': 'NAD+ метаболизм', 'MITO_REPAIR': 'Митохондриальная защита',
  'OXIDATIVE_STRESS_REDUCTION': 'Антиоксидант', 'COLLAGEN_SUPPORT': 'Синтез коллагена',
  'CALCIUM_HOMEOSTASIS': 'Кальциевый гомеостаз', 'CALCIUM_DISTRIBUTION': 'Распределение Ca²⁺',
  'BONE_MINERALIZATION': 'Минерализация костей', 'MEMBRANE_PROTECTION': 'Защита мембран',
  'SIRT1_ACTIVATION': 'Активация SIRT1', 'IMMUNE_SUPPORT': 'Иммунная поддержка',
  'IMMUNE_MODULATION': 'Иммуномодуляция', 'NEUROTRANSMITTER_SUPPORT': 'Нейротрансмиттеры',
  'HOMOCYSTEINE_REDUCTION': 'Снижение гомоцистеина', 'CARBOXYLASE_SUPPORT': 'Кофактор карбоксилаз',
  'METHYLATION': 'Метилирование', 'CELL_DIVISION': 'Деление клеток',
  'MYELIN_REPAIR': 'Репарация миелина', 'CELL_REPAIR': 'Репарация клеток',
  'ENERGY': 'Энергетический обмен', 'NITRIC_OXIDE_BINDING': 'Связывание NO',
  'LIPOSOMAL_DELIVERY': 'Липосомальная доставка', 'ELECTRON_TRANSPORT_CHAIN': 'Электрон-транспортная цепь',
  'ANTIOXIDANT': 'Антиоксидант', 'GLUTATHIONE_RECYCLING': 'Рециклинг глутатиона',
  'GLUCOSE_REGULATION': 'Регуляция глюкозы', 'INSULIN_SENSITIVITY': 'Чувствительность к инсулину',
  'INSULIN_SIGNALING': 'Инсулиновый сигналинг', 'SEROTONIN_SUPPORT': 'Серотонин',
  'SKIN_REPAIR': 'Репарация кожи', 'ANTI_INFLAMMATION': 'Противовоспалительное',
  'OXYGEN_UTILIZATION': 'Утилизация кислорода', 'METHYL_DONOR': 'Донор метильных групп',
  'FATTY_ACID_TRANSPORT': 'Транспорт жирных кислот', 'ATP_PRODUCTION': 'Продукция АТФ',
  'COA_PATHWAY': 'Кофермент А', 'HORMONE_SYNTHESIS': 'Синтез гормонов',
  'LIPID_METABOLISM': 'Метаболизм липидов', 'FLAVIN_PATHWAY': 'Флавиновый обмен',
  'TPP_PATHWAY': 'Тиаминпирофосфат', 'NERVE_REPAIR': 'Репарация нервов',
  'NERVE_PROTECTION': 'Защита нервов', 'ANTI_GLYCATION': 'Анти-гликирование',
  'RETINOID_SIGNALING': 'Ретиноидный сигналинг', 'CAROTENOID_PATHWAY': 'Каротиноидный обмен',
  'LIPID_BALANCE': 'Баланс липидов', 'NAD_SYNTHESIS': 'Синтез NAD+',
  'MITO_BIOGENESIS': 'Биогенез митохондрий', 'VASCULAR_RELAXATION': 'Вазодилатация',
  'GABA_SUPPORT': 'ГАМК-поддержка', 'CALCIUM_REGULATION': 'Регуляция Ca²⁺',
  'SULFITE_OXIDASE': 'Сульфитоксидаза', 'DETOX': 'Детоксикация',
  'BONE_METABOLISM': 'Костный метаболизм', 'TESTOSTERONE_SUPPORT': 'Поддержка тестостерона',
};
export const SUPPORT_MED_DETAIL: Record<string, {
  description: string;
  mechanism: string;
  mechanismKeys: string[];
  systems: { key: string; label: string; mechanisms: string[] }[];
  risks: string[];
  contraindications: string[];
}> = {
  telmisartan: {
    description: 'Телмисартан (Микардис) — АРБ с уникальным PPAR-γ частичным агонизмом. Кардиопротекция, нефропротекция, улучшение липидного обмена на ААС курсах.',
    mechanism: 'Блокада AT1-рецепторов ангиотензина II → ↓ вазоконстрикция, ↓ альдостерон → ↓ АД. Частичный агонист PPAR-γ → ↑ инсулиновая чувствительность, ↑ липидный обмен. Снижает TGF-β1 → нефропротекция.',
    mechanismKeys: ['AT1_BLOCK', 'ALDOSTERONE_DOWN', 'BP_DOWN'],
    systems: [
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Снижение АД', 'Снижение гипертрофии ЛЖ'] },
      { key: 'renal', label: 'Почечная', mechanisms: ['Нефропротекция', 'Снижение протеинурии'] },
    ],
    risks: ['Гипотензия при передозировке', 'Головокружение', 'Гиперкалиемия (редко)'],
    contraindications: ['Беременность', 'Двусторонний стеноз почечных артерий', 'Одновременный приём ИАПФ'],
  },
nebivolol: {
    description: 'Небиволол (Небилет) — кардиоселективный β1-блокатор III поколения с NO-вазодилатацией. Снижает АД и ЧСС, защищает миокард, улучшает эндотелиальную функцию.',
    mechanism: 'Кардиоселективная блокада β1-адренорецепторов → ↓ ЧСС, ↓ сократимость, ↓ АД. Активация eNOS → ↑ NO → вазодилатация. Снижает окислительный стресс в сосудах.',
    mechanismKeys: ['BETA1_BLOCK', 'NO_UP', 'HR_DOWN'],
    systems: [
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Снижение ЧСС и АД', 'NO-вазодилатация', 'Кардиопротекция'] },
    ],
    risks: ['Брадикардия при передозировке', 'Усталость', 'Гипотензия'],
    contraindications: ['AV-блокада II-III степени', 'Кардиогенный шок', 'Бронхиальная астма (с осторожностью)'],
  },
  hcg: {
    description: 'Хорионический гонадотропин (ХГЧ) — аналог ЛГ. Стимулирует клетки Лейдига → эндогенный тестостерон. Предотвращает атрофию яичек на курсе ААС.',
    mechanism: 'Связывается с LH/CG-рецепторами на клетках Лейдига → ↑ цАМФ → стероидогенез → ↑ тестостерон. Стимулирует сперматогенез через поддержание интратестикулярного тестостерона.',
    mechanismKeys: ['LH_MIMETIC', 'TESTOSTERONE_UP', 'HPTA_SUPPORT'],
    systems: [
      { key: 'reproductive', label: 'Репродуктивная', mechanisms: ['Стимуляция Лейдигов', 'Предотвращение атрофии яичек'] },
    ],
    risks: ['Эстрогенные эффекты (гинекомастия)', 'Подавление HPTA при высоких дозах', 'Сенсибилизация яичников к ЛГ'],
    contraindications: ['Рак простаты', 'Рак яичка', 'Преждевременное половое созревание'],
  },
  nac: {
    description: 'N-ацетилцистеин — предшественник глутатиона, главного внутриклеточного антиоксиданта. Гепатопротектор, нейропротектор, муколитик. Основа любой поддержки печени.',
    mechanism: 'Деацетилирование → цистеин → глутатион (GSH). Нейтрализация ROS и электрофильных токсинов. Модуляция NF-κB → противовоспалительное действие. Расщепление дисульфидных связей мукопротеинов → муколитик.',
    mechanismKeys: ['GSH_UP', 'ROS_DOWN', 'DETOX_UP', 'NFkB_DOWN'],
    systems: [
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Синтез глутатиона', 'Детоксикация'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Антиоксидантная защита'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Нейропротекция'] },
    ],
    risks: ['Тошнота, ЖК-дискомфорт', 'Неприятный запах', 'Аллергические реакции (редко)'],
    contraindications: ['Бронхиальная астма (ингаляционно)', 'Тяжёлая печёночная недостаточность'],
  },
  tudca: {
    description: 'TUDCA (таурсооксихолевая кислота) — урсодезоксихолевая кислота с таурином. Мощный гепатопротектор: стабилизирует митохондрии, восстанавливает желчеотток, снижает апоптоз гепатоцитов.',
    mechanism: 'Стабилизация митохондриальных мембран → ↓ апоптоз гепатоцитов. Усиление желчеоттока → растворение холестаза. Активация рецепторов FXR/TGR5 → противовоспалительный эффект.',
    mechanismKeys: ['MITO_STABILIZE', 'BILE_FLOW_UP', 'APOPTOSIS_DOWN'],
    systems: [
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Стабилизация митохондрий', 'Восстановление желчеоттока', 'Снижение апоптоза'] },
    ],
    risks: ['Диарея при высоких дозах', 'Дискомфорт в правом подреберье'],
    contraindications: ['Желчнокаменная болезнь (с осторожностью)', 'Обструкция жёлчных путей'],
  },
  omega3: {
    description: 'Омега-3 (EPA + DHA) — эссенциальные жирные кислоты. Кардиопротектор, противовоспалительный, нейропротектор. Улучшает липидный профиль, снижает триглицериды.',
    mechanism: 'EPA → резолвины/протектины (SPM) → синтетическое разрешение воспаления; DHA → структурный компонент нейромембран; конкуренция с AA → ↓ PGE2. Активация PPAR-α → ↓ триглицериды.',
    mechanismKeys: ['SPM_UP', 'TG_DOWN', 'NFkB_DOWN', 'NEURO_MEMBRANE'],
    systems: [
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Снижение триглицеридов', 'Антивоспалительное', 'Антиаритмическое'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Структура нейромембран', 'Нейропротекция'] },
    ],
    risks: ['Рыбный запах от тела', 'Разжижение крови при высоких дозах', 'ЖК-дискомфорт'],
    contraindications: ['Гемофилия', 'Приём антикоагулянтов без контроля МНО'],
  },
  magnesium: {
    description: 'Магний бисглицинат — хелатная форма магния с высокой биодоступностью. Успокаивает ЦНС, снижает кортизол, расслабляет мышцы, поддерживает сердце.',
    mechanism: 'Блокада NMDA-рецепторов → ↓ возбудимость нейронов. Активация ГАМК-рецепторов → седативный эффект. Кофактор АТФазы → энергетический обмен. Блокада кальциевых каналов → расслабление гладкой мускулатуры.',
    mechanismKeys: ['NMDA_DOWN', 'GABA_UP', 'ATPASE_UP', 'CA_CHANNELS_DOWN'],
    systems: [
      { key: 'neuro', label: 'Нервная', mechanisms: ['Снижение тревожности', 'Улучшение сна'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Снижение АД', 'Антиаритмическое'] },
    ],
    risks: ['Диарея при высоких дозах', 'Сонливость', 'Гипотензия'],
    contraindications: ['AV-блокада', 'Тяжёлая почечная недостаточность'],
  },
  berberine: {
    description: 'Берберин — алкалоид растений. Мощный АМПК-активатор, снижает сахар, улучшает липидный профиль, ингибирует CYP3A4. Природный метформин.',
    mechanism: 'Активация АМПК → ↑ инсулиновая чувствительность, ↑ глюкозный транспорт. Ингибирование CYP3A4 → взаимодействие с фармпрепаратами. Снижение ЛПНП через PCSK9. ↓ липогенез в печени.',
    mechanismKeys: ['AMPK_UP', 'INSULIN_SENSITIVITY_UP', 'CYP3A4_INHIBIT', 'LDL_DOWN'],
    systems: [
      { key: 'endocrine', label: 'Эндокринная', mechanisms: ['Снижение сахара', 'Сенсибилизация к инсулину'] },
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Активация АМПК'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Снижение ЛПНП'] },
    ],
    risks: ['ЖК-дискомфорт', 'CYP3A4-опосредованные взаимодействия', 'Гипогликемия при комбинации с сахароснижающими'],
    contraindications: ['Беременность', 'Приём макролидов/статинов без контроля', 'Тяжёлые заболевания печени'],
  },
  coq10: {
    description: 'Коэнзим Q10 (убихинон) — ключевой компонент дыхательной цепи митохондрий. Антиоксидант, кардиопротектор, регенерирует витамин E. Критичен на ААС курсах при HEFT-нагрузке.',
    mechanism: 'Электрон-транспортная цепь (комплекс I-III) → АТФ-синтез. Антиоксидант в липидных мембранах. Регенерирует витамин E из токоферил-радикала. Снижает окисление ЛПНП.',
    mechanismKeys: ['ETC_UP', 'ATP_UP', 'ANTIOXIDANT', 'VITE_REGEN'],
    systems: [
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Энергетика миокарда', 'Антиоксидант', 'Снижение окисления ЛПНП'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Митохондриальная защита'] },
    ],
    risks: ['Лёгкий ЖК-дискомфорт', 'Бессонница при вечернем приёме'],
    contraindications: ['Приём варфарина (снижает антикоагулянтный эффект)'],
  },
  vitamin_d3: {
    description: 'Витамин D3 (холекальциферол) — стероидный прогормон. Критичен для иммунитета, костного метаболизма и тестостерона. Дефицит есть у 80% населения.',
    mechanism: 'Гидроксилирование в печени (25-OH-D3) → почках (1,25-OH2-D3 = кальцитриол) → связывание с VDR → ↑ >200 генов. ↑ всасывание Ca/P, ↑ иммунитет через кателицидины, ↑ тестостерон через стимуляцию ЛГ.',
    mechanismKeys: ['VDR_UP', 'CALCIUM_UP', 'IMMUNE_MOD', 'AR_UP'],
    systems: [
      { key: 'endocrine', label: 'Эндокринная', mechanisms: ['↑ тестостерон через ЛГ', '↑ всасывание кальция'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Иммуномодуляция'] },
    ],
    risks: ['Гиперкальциемия при передозировке', 'Тошнота при высоких дозах', 'Камни в почках (редко)'],
    contraindications: ['Гиперкальциемия', 'Саркоидоз', 'Тяжёлая почечная недостаточность'],
  },
  zinc: {
    description: 'Цинк пиколинат — хелатная форма цинка с максимальной биодоступностью. Кофактор 5α-редуктазы, супероксиддисмутазы, иммунных ферментов. Критичен для тестостерона.',
    mechanism: 'Кофактор 5α-редуктазы → конверсия тестостерон→ДГТ. Кофактор Zn-зависимой SOD → антиоксидантная защита. Кофактор >300 ферментов. ↑ иммунитет через тимулин и Т-клетки.',
    mechanismKeys: ['5AR_UP', 'AR_UP', 'SOD_UP', 'IMMUNE_UP'],
    systems: [
      { key: 'reproductive', label: 'Репродуктивная', mechanisms: ['Поддержка тестостерона', '5α-редуктаза'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Zn-зависимый иммунитет', 'SOD-антиоксидант'] },
    ],
    risks: ['Тошнота натощак', 'Взаимодействие с медью (длительный приём)', 'Снижение меди при высоких дозах'],
    contraindications: ['Болезнь Вильсона', 'Одновременный приём антибиотиков тетрациклинового ряда'],
  },
alpha_lipoic: {
    description: 'Альфа-липоевая кислота (ALA) — универсальный водорасстворимый антиоксидант. Регенерирует витамины C, E и глутатион. Нейропротектор, гепатопротектор, митохондриальный кофактор.',
    mechanism: 'Кофактор ПВК-дегидрогеназы (PDH) → энергетический обмен. Прямое scavenging ROS. Регенерация GSH, витаминов C и E. Хелатирование тяжёлых металлов (Fe, Cu).',
    mechanismKeys: ['ROS_SCAVENGE', 'GSH_REGEN', 'PDH_UP', 'MITO_UP'],
    systems: [
      { key: 'neuro', label: 'Нервная', mechanisms: ['Нейропротекция', 'Регенерация GSH', 'Митохондриальная защита'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Антиоксидант', 'Антигликирование'] },
    ],
    risks: ['Гипогликемия при комбинации с сахароснижающими', 'ЖК-дискомфорт', 'Кожная сыпь (редко)'],
    contraindications: ['Тиреотоксикоз (без контроля)', 'Приём химиотерапии (без разрешения)'],
  },
  ashwagandha: {
    description: 'Withania somnifera — адаптоген. Снижает кортизол, модулирует GABA, защищает нейроны, поддерживает тестостерон. Анксиолитик + нейропротектор + эндокринный модулятор.',
    mechanism: 'Модуляция GABA-А рецепторов → анксиолитический эффект. ↓ кортизол через ингибирование HPA-оси. ↑ LH → ↑ тестостерон. ↑ SOD и каталаза → антиоксидантная защита нейронов.',
    mechanismKeys: ['GABA_MOD', 'CORTISOL_DOWN', 'HPA_MOD', 'LH_UP'],
    systems: [
      { key: 'neuro', label: '', mechanisms: ['', '', ''] },
      { key: 'endocrine', label: '', mechanisms: ['', ''] },
      { key: 'reproductive', label: '', mechanisms: [''] },
    ],
    risks: ['', '', ''],
    contraindications: ['', '', ''],
  },
  saw_palmetto: {
    description: 'Serenoa repens — ингибитор 5α-редуктазы и α1-адренорецепторов. Защита простаты, снижение DHT-опосредованных рисков, мочегонное.',
    mechanism: 'Ингибирование 5α-редуктазы → ↓ конверсия тестостерон→ДГТ. Блокада α1-адренорецепторов → расслабление гладкой мускулатуры простаты. Антиандрогенный эффект локальный.',
    mechanismKeys: ['5AR_INHIBIT', 'DHT_DOWN', 'ALPHA1_BLOCK'],
    systems: [
      { key: 'reproductive', label: '', mechanisms: ['', '', ''] },
    ],
    risks: ['', '', ''],
    contraindications: ['', '', ''],
  },
  celery_extract: {
    description: 'Экстракт сельдерея — диуретик, урикостатик, вазодилататор. Мочегонное, снижает мочевую кислоту, улучшает NO-путь. Нефропротектор.',
    mechanism: 'Диуретическое действие через фталиды. Снижение мочевой кислоты (урикодавление). NO-вазодилатация через фталиды. Защита подоцитов почек.',
    mechanismKeys: ['DIURESIS_UP', 'URIC_DOWN', 'NO_UP', 'KIDNEY_PROTECT'],
    systems: [
      { key: 'renal', label: 'Почечная', mechanisms: ['Мочегонное', 'Снижение мочевой кислоты', 'Защита подоцитов'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['NO-вазодилатация', 'Снижение АД'] },
    ],
    risks: ['Увеличение диуреза', 'Фотосенсибилизация', 'Взаимодействие с литием'],
    contraindications: ['Тяжёлая почечная недостаточность', 'Приём лития'],
  },
  vitamin_k2: {
    description: 'Витамин K2 (МК-7) — активатор остеокальцина и матриксного Gla-белка. Направляет кальций в кости, предотвращает кальцификацию сосудов.',
    mechanism: 'γ-карбоксилирование остеокальцина → связывание Ca в костях. γ-карбоксилирование MGP (матриксный Gla-белок) → ингибирование кальцификации сосудов. Синергия с витамином D3.',
    mechanismKeys: ['GLA_UP', 'CALCIUM_TARGETING', 'BONE_UP', 'VASCULAR_PROTECT'],
    systems: [
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Предотвращение кальцификации сосудов', 'Защита клапанов'] },
      { key: 'endocrine', label: 'Эндокринная', mechanisms: ['Костный метаболизм'] },
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Коагуляция'] },
    ],
    risks: ['Взаимодействие с варфарином (антагонизм)', 'Тромбоз при высоких дозах без показаний'],
    contraindications: ['Приём антикоагулянтов (варфарин)', 'Тромбофилия'],
  },
  selenium: {
    description: 'Селен (селексен) — кофактор глутатионпероксидазы (GPx) и дейодиназы тиреоидных гормонов. Антиоксидант, поддержка щитовидной железы, иммуномодулятор.',
    mechanism: 'Кофактор GPx → преобразование H2O2 в H2O. Кофактор 5-дейодиназы → конверсия T4→T3 (активный тиреоидный гормон). ↑ иммунитет через селено-протеины. Антиоксидантная защита мембран.',
    mechanismKeys: ['GPX_UP', 'T3_UP', 'IMMUNE_UP', 'ANTIOXIDANT'],
    systems: [
      { key: 'endocrine', label: 'Эндокринная', mechanisms: ['Конверсия T4→T3', 'Поддержка щитовидной'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Иммуномодуляция'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Антиоксидантная защита'] },
    ],
    risks: ['Токсичность при дозах >400 мкг/день', 'Запах чеснока изо рта', 'Выпадение волос при передозировке'],
    contraindications: ['Тиреотоксикоз (без контроля)', 'Одновременный приём высоких доз цинка'],
  },
  milk_thistle: {
    description: 'Расторопша (силимарин) — гепатопротектор №1 в фитотерапии. Стабилизирует мембраны гепатоцитов, стимулирует синтез белка, активирует глутатион-S-трансферазу.',
    mechanism: 'Силибинин → стабилизация мембран гепатоцитов → ↓ проникновение токсинов. ↑ синтез белка и регенерация печени. Активация GST (глутатион-S-трансфераза) → детоксикация. Ингибирование NF-κB → противовоспалительное.',
    mechanismKeys: ['MEMBRANE_STABILIZE', 'PROTEIN_SYNTHESIS_UP', 'GST_UP', 'NFkB_DOWN'],
    systems: [
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Стабилизация мембран', 'Регенерация ткани', 'Активация GST', 'Ингибирование NF-κB'] },
    ],
    risks: ['Диарея при высоких дозах', 'Аллергические реакции (редко)', 'Взаимодействие с CYP3A4'],
    contraindications: ['Желчнокаменная болезнь (с осторожностью)', 'Беременность'],
  },
  probiotics: {
    description: 'Пробиотики (Lactobacillus/Bifidobacterium) — живые микроорганизмы для восстановления микробиома. Улучшают пищеварение, иммунитет, кишечный барьер.',
    mechanism: 'Колонизация кишечника → продукция короткоцепочечных жирных кислот (бутират, пропионат, ацетат). Модуляция иммунной системы через Treg. Укрепление кишечного барьера через tight junctions. Конкуренция с патогенами.',
    mechanismKeys: ['MICROBIOME_UP', 'SCFA_UP', 'IMMUNE_MOD', 'GUT_BARRIER_UP'],
    systems: [
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Снижение эндотоксемии', 'Улучшение пищеварения'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Иммуномодуляция', 'Снижение воспаления'] },
    ],
    risks: ['Вздутие живота в первые дни', 'Риск инфекции у иммунокомпрометированных'],
    contraindications: ['Тяжёлый иммунодефицит', 'Центральный венозный катетер (риск фунгемии)'],
  },
  vitamin_b12: {
    description: 'Витамин B12 (метилкобаламин) — кофактор метионинсинтазы и метилмалонил-КоА мутазы. Критичен для миелинизации нервов, эритропоэза и метилирования ДНК.',
    mechanism: 'Метилкобаламин → кофактор метионинсинтазы → реметилирование гомоцистеина в метионин. Кофактор метилмалонил-КоА мутазы → превращение пропионата в сукцинил-КоА. Поддержка миелинизации.',
    mechanismKeys: ['METHIONINE_UP', 'HCY_DOWN', 'MYELIN_UP', 'ERYTHROPOIESIS_UP'],
    systems: [
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Эритропоэз', 'Снижение гомоцистеина'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Миелинизация', 'Нейропротекция'] },
    ],
    risks: ['Аллергические реакции (редко)', 'Акне (при высоких дозах)'],
    contraindications: ['Болезнь Лебера', 'Дефицит калия при начале терапии'],
  },
  vitamin_b6: {
    description: 'Витамин B6 (пиридоксаль-5-фосфат, P5P) — кофактор трансаминаз, декарбоксилаз и синтеза нейромедиаторов. Критичен для синтеза серотонина, дофамина и ГАМК.',
    mechanism: 'P5P → трансаминазы, декарбоксилазы; синтез серотонина/дофамина/GABA; гем-синтез через ALA-синтазу; снижение гомоцистеина',
    mechanismKeys: ['AAT_UP', 'SEROTONIN_UP', 'GABA_UP', 'HCY_DOWN', 'HEM_UP'],
    systems: [
      { key: 'neuro', label: 'Нервная', mechanisms: ['Синтез серотонина и дофамина', 'ГАМК-ергическая передача'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Гем-синтез', 'Снижение гомоцистеина'] },
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Трансаминазы'] },
    ],
    risks: ['Периферическая нейропатия при дозах >200 мг/день', 'Сенсибилизация к солнцу'],
    contraindications: ['Болезнь Паркинсона (при приёме леводопы)', 'Длительный приём высоких доз'],
  },
  folate: {
    description: '5-метилтетрагидрофолат — активная форма фолиевой кислоты. Метилирование ДНК, эритропоэз, снижение гомоцистеина. Обходит MTHFR-мутации.',
    mechanism: '5-МТГФ → метильный донор для метионинсинтазы (с B12) → метилирование ДНК; тимидилат-синтаз → синтез ДНК; снижение гомоцистеина',
    mechanismKeys: ['DNA_METHYLATION_UP', 'THYMIDYLATE_UP', 'HCY_DOWN', 'RBC_UP'],
    systems: [
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Эритропоэз', 'Синтез ДНК', 'Снижение гомоцистеина'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Снижение гомоцистеина'] },
    ],
    risks: ['Маскировка дефицита B12 при приёме без B12', 'Судороги при эпилепсии (редко)'],
    contraindications: ['Дефицит B12 без одновременного приёма B12', 'Эпилепсия (без контроля)'],
  },
  iron: {
    description: 'Железо (Fe²⁺) — эссенциальный микроэлемент. Компонент гемоглобина, миоглобина, цитохромов. Критичен для транспорта кислорода и энергетического обмена.',
    mechanism: 'Fe²⁺ → гем → гемоглобин/миоглобин. Fe-S-кластеры → комплексы I-III дыхательной цепи. Fe → каталаза/пероксидаза → антиоксидантная защита.',
    mechanismKeys: ['HEM_UP', 'O2_TRANSPORT', 'ETC_UP', 'OXYGEN_UP'],
    systems: [
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Синтез гемоглобина', 'Транспорт кислорода'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Энергетика миокарда', 'Цитохромы'] },
    ],
    risks: ['Гемохроматоз при хронической передозировке', 'ЖК-дискомфорт (запор)', 'Окислительный стресс при избытке', 'Взаимодействие с тетрациклинами'],
    contraindications: ['Гемохроматоз', 'Гемосидероз', 'Талассемия', 'Приём леводопы/тетрациклинов'],
  },
  copper: {
    description: 'Медь — кофактор Cu/Zn-SOD, цитохром-c-оксидазы, лизилоксидазы. Критична для антиоксидантной защиты, энергетического обмена и синтеза коллагена/эластина.',
    mechanism: 'Cu/Zn-SOD → антиоксидант; цитохром-c-оксидаза → терминальный комплекс ЭТК; лизилоксидаза → кросслинкинг коллагена/эластина; церулоплазмин → Fe-транспорт',
    mechanismKeys: ['SOD_UP', 'ETC_UP', 'COLLAGEN_UP', 'FE_TRANSPORT'],
    systems: [
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Cu/Zn-SOD антиоксидант', 'Железотранспорт через церулоплазмин'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Цитохром-c-оксидаза', 'Миелинизация'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Лизилоксидаза → эластин'] },
    ],
    risks: ['Токсичность при высоких дозах', 'Взаимодействие с цинком (антагонизм)', 'Болезнь Вильсона при дисбалансе'],
    contraindications: ['Болезнь Вильсона', 'Одновременный приём высоких доз цинка'],
  },
astragalus: {
    description: 'Астрагал (Astragalus membranaceus) — нефропротектор, иммуномодулятор. Защищает подоциты почек, снижает TGF-β1, модулирует NF-κB. Используется в китайской медицине тысячелетиями.',
    mechanism: 'Защита подоцитов через астрагалозиды. ↓ TGF-β1 → ↓ фиброз почек. Ингибирование NF-κB → противовоспалительное действие. ↑ иммунитет через активацию макрофагов и NK-клеток.',
    mechanismKeys: ['PODOCYTE_PROTECT', 'NFkB_DOWN', 'TGF_B1_DOWN', 'IMMUNE_UP'],
    systems: [
      { key: 'renal', label: 'Почечная', mechanisms: ['Защита подоцитов', 'Снижение фиброза', 'Противовоспалительное'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Кардиопротекция'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Иммуномодуляция'] },
    ],
    risks: ['Взаимодействие с иммунодепрессантами', 'Снижение сахара (с осторожностью при диабете)', 'Возможная аллергия'],
    contraindications: ['Аутоиммунные заболевания (без контроля)', 'Приём иммунодепрессантов'],
  },
  taurine: {
    description: 'Таурин — условно-незаменимая аминокислота. Конъюгация жёлчных кислот, осморегуляция, ГАМК-миметик, антиоксидант. Кардиопротектор и нейропротектор.',
    mechanism: 'Конъюгация жёлчных кислот → эмульгация жиров. Осморегуляция клеток. ГАМК-А агонист → седативный эффект. Модуляция Ca²⁺-каналов в кардиомиоцитах → инотропная поддержка.',
    mechanismKeys: ['BILE_ACID_CONJUGATE', 'OSMOLYTE', 'GABA_AGONIST', 'CA_MOD', 'ANTIOXIDANT'],
    systems: [
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Инотропная поддержка', 'Антиаритмическое', 'Снижение АД'] },
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Конъюгация жёлчных кислот', 'Осморегуляция'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['ГАМК-миметический эффект', 'Нейропротекция'] },
      { key: 'renal', label: 'Почечная', mechanisms: ['Осморегуляция', 'Антиоксидант'] },
    ],
    risks: ['Сонливость при высоких дозах', 'Диарея при дозах >6 г', 'Снижение АД'],
    contraindications: ['Тяжёлая гипотензия', 'Приём лития (без контроля)'],
  },
  melatonin: {
    description: 'Мелатонин — гормон шишковидной железы. Регулятор циркадных ритмов, антиоксидант, снижает кортизол. Критичен для восстановления на ААС курсах.',
    mechanism: 'MT1/MT2 → циркадная регуляция сна. Проникновение в митохондрии → антиоксидант (прямое scavenging ROS). ↓ кортизол через ингибирование HPA-оси. ↑ BDNF → нейропластичность. Иммуностью модуляция.',
    mechanismKeys: ['CIRCADIAN_UP', 'MITO_ANTIOX', 'CORTISOL_DOWN', 'BDNF_UP', 'SLEEP_UP'],
    systems: [
      { key: 'neuro', label: 'Нервная', mechanisms: ['Регуляция сна', 'Снижение кортизола', '↑ BDNF'] },
      { key: 'endocrine', label: 'Эндокринная', mechanisms: ['Ингибирование HPA-оси', 'Циркадная регуляция'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Снижение АД ночью'] },
    ],
    risks: ['Сонливость утром при высоких дозах', 'Яркие сновидения', 'Головная боль'],
    contraindications: ['Аутоиммунные заболевания', 'Приём иммунодепрессантов'],
  },
  ginseng: {
    description: 'Женьшень (Panax ginseng) — адаптоген, модулятор HPA-оси. Повышает NO-продукцию, BDNF, ЛГ. Антиусталостное, нейропротекторное, иммуномодулирующее действие.',
    mechanism: 'Модуляция HPA-оси → адаптогенный эффект. ↑ NO через eNOS → вазодилатация. ↑ BDNF → нейропластичность. ↑ ЛГ → тестостерон. Иммуномодуляция через макрофаги и NK-клетки.',
    mechanismKeys: ['HPA_MOD', 'NO_UP', 'BDNF_UP', 'LH_UP', 'IMMUNE_MOD'],
    systems: [
      { key: 'endocrine', label: 'Эндокринная', mechanisms: ['↑ ЛГ и тестостерон', 'Модуляция HPA-оси'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['↑ BDNF', 'Антиусталостное действие'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['NO-вазодилатация'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Иммуномодуляция'] },
    ],
    risks: ['Бессонница', 'Головная боль', 'Гипогликемия', 'Тахикардия при высоких дозах'],
    contraindications: ['Беременность', 'Неконтролируемая гипертензия', 'Приём антикоагулянтов'],
  },
  egcg: {
    description: 'EGCG (эпигаллокатехин галлат) — главный катехин зелёного чая. Мощный антиоксидант, AMPK-активатор, хелатор железа, ингибитор NF-κB. Кардио- и нейропротектор.',
    mechanism: 'Прямое scavenging ROS и хелатирование железа. Активация AMPK → ↑ липидный обмен, ↓ липогенез. Ингибирование NF-κB → противовоспалительное действие. ↓ окисление ЛПНП.',
    mechanismKeys: ['ROS_SCAVENGE', 'FE_CHELATE', 'AMPK_UP', 'NFkB_DOWN', 'LDL_OX_DOWN'],
    systems: [
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Снижение окисления ЛПНП', 'Антивоспалительное'] },
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Активация AMPK', 'Жиросжигание'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Нейропротекция', 'Антиоксидант'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Хелатирование железа'] },
    ],
    risks: ['Гепатотоксичность при высоких дозах (>800 мг)', 'Взаимодействие с фолатом', 'Снижение всасывания железа'],
    contraindications: ['Беременность', 'Железодефицитная анемия', 'Приём фолиевой кислоты одновременно'],
  },
  curcumin: {
    description: 'Куркумин с пиперином — мощный противовоспалительный и антиоксидант. Ингибирует NF-κB, COX-2, AMPK-активатор. Биодоступность ↑2000% с пиперином.',
    mechanism: 'Ингибирование NF-κB → ↓ TNF-α, ↓ IL-6, ↓ COX-2. Активация AMPK → ↓ липогенез. Хелатирование железа. Ингибирование CYP3A4 (через пиперин). ↑ BDNF в гиппокампе.',
    mechanismKeys: ['NFkB_DOWN', 'COX2_DOWN', 'AMPK_UP', 'FE_CHELATE', 'CYP3A4_INHIBIT'],
    systems: [
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Активация AMPK', 'Противовоспалительное'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Антиоксидант'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['↑ BDNF', 'Нейропротекция'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Хелатирование железа'] },
    ],
    risks: ['CYP3A4-опосредованные взаимодействия (через пиперин)', 'ЖК-дискомфорт', 'Разжижение крови при высоких дозах'],
    contraindications: ['Желчнокаменная болезнь', 'Приём антикоагулянтов', 'Беременность (в терапевтических дозах)', 'Гемохроматоз'],
  },
  phosphatidylcholine: {
    description: 'Фосфатидилхолин — главный фосфолипид клеточных мембран и жёлчи. Гепатопротектор, нейропротектор, источник холина для ацетилхолина.',
    mechanism: 'Предшественник ацетилхолина → нейромедиаторная передача. Компонент жёлчи → эмульгация жиров. Ремонт клеточных мембран → гепатопротекция. Снижение ЛПНП через ↑ VLDL-метаболизм.',
    mechanismKeys: ['MEMBRANE_REPAIR', 'BILE_UP', 'ACH_UP', 'VLDL_UP'],
    systems: [
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Ремонт мембран гепатоцитов', 'Усиление жёлчеоттока', 'Снижение стеатоза'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Предшественник ацетилхолина', 'Нейропротекция'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Снижение ЛПНП'] },
    ],
    risks: ['Диарея при высоких дозах', 'Потливость', 'Запах рыбы изо рта'],
    contraindications: ['Жёлчнокаменная болезнь (с осторожностью)', 'Депрессия (избыток холина)'],
  },
  l_carnitine: {
    description: 'L-карнитин — транспортёр жирных кислот в митохондрии. Кардиопротектор, нейропротектор, поддержка печени. Улучшает энергетику миокарда и скелетных мышц.',
    mechanism: 'Транспорт длинноцепочечных ЖК в митохондрии → β-окисление → АТФ. Ацетил-КоА буфер → энергетический обмен. ↑ вентиляция митохондрий → антиоксидантная защита.',
    mechanismKeys: ['FA_OXIDATION_UP', 'ATP_UP', 'ACETYL_COA_UP', 'MITO_UP'],
    systems: [
      { key: 'cardio', label: '', mechanisms: ['', ''] },
      { key: 'hepatic', label: '', mechanisms: ['', ''] },
      { key: 'neuro', label: '', mechanisms: ['', ''] },
    ],
    risks: ['TMAO при высоких дозах (кишечная флора)', '', ''],
    contraindications: ['', '', ''],
  },
glucosamine: {
    description: 'Глюкозамин — аминосахар, предшественник гликозаминогликанов (GAG). Хондропротектор, снижает MMP-активность, восстанавливает синовиальную жидкость.',
    mechanism: 'Предшественник GAG → rebuilding хряща. ↑ синтез протеогликанов и гиалуроновой кислоты. ↓ MMP (матриксные металлопротеиназы) → снижение деградации хряща.',
    mechanismKeys: ['GAG_UP', 'PROTEOGLYCAN_UP', 'HYALURONAN_UP', 'MMP_DOWN'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['Восстановление хряща', '↑ протеогликаны', '↑ гиалуронан'] },
    ],
    risks: ['Диарея при высоких дозах', 'Взаимодействие с варфарином (редко)', 'Аллергия у людей с аллергией на моллюсков'],
    contraindications: ['Приём варфарина', 'Аллергия на моллюсков (для глюкозамина из хитина)'],
  },
chondroitin: {
    description: 'Хондроитинсульфат — гликозаминогликан, компонент хрящевой ткани. Восстанавливает гидратацию хряща, ингибирует эластазу, стимулирует синтез коллагена II.',
    mechanism: 'Гидратация хряща через osmotic pressure. Ингибирование эластазы и других протеаз → ↓ деградация хряща. ↑ синтез коллагена II и протеогликанов.',
    mechanismKeys: ['CARTILAGE_HYDRATION', 'ELASTASE_DOWN', 'COLLAGEN2_UP', 'PROTEOGLYCAN_UP'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['Гидратация хряща', 'Ингибирование эластазы', '↑ коллаген II'] },
    ],
    risks: ['Диарея', 'Аллергические реакции (редко)', 'Взаимодействие с антикоагулянтами'],
    contraindications: ['Приём антикоагулянтов', 'Астма (с осторожностью)'],
  },
  msm: {
    description: 'MSM (метилсульфонилметан) — органическая сера. Донор серы для дисульфидных связей коллагена, противовоспалительное через NF-κB, снижает простагландин E2.',
    mechanism: 'Донор серы → дисульфидные связи коллагена и кератина. Ингибирование NF-κB → ↓ воспаление. ↓ PGE2 и COX-2 → обезболивание. Улучшение проницаемости клеточных мембран.',
    mechanismKeys: ['SULFUR_DONOR', 'DISULFIDE_UP', 'NFkB_DOWN', 'PGE2_DOWN'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['Ремонт коллагена', 'Противовоспалительное', 'Обезболивание'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Антиоксидант'] },
    ],
    risks: ['Диарея при высоких дозах', 'Головная боль', 'Тошнота'],
    contraindications: ['Приём антикоагулянтов', 'Беременность (без контроля)'],
  },
  collagen: {
    description: 'Коллаген (гидролизат) — пептиды коллагена I и III типов. Стимулирует фибробласты, снижает MMP-13, восстанавливает связки, сухожилия и кожу.',
    mechanism: 'Гидролизат коллагена → пептиды → абсорбция → стимуляция фибробластов. ↑ синтез коллагена I и III. ↓ MMP-13 (коллагеназа) → защита хряща. ↑ протеогликаны.',
    mechanismKeys: ['COLLAGEN_PEPTIDES_UP', 'FIBROBLAST_UP', 'MMP13_DOWN', 'PROTEOGLYCAN_UP'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['↑ синтез коллагена I/III', '↑ фибробласты', '↓ MMP-13', '↑ протеогликаны'] },
    ],
    risks: ['Изжога при высоких дозах', 'Аллергия (рыбный/говяжий источник)', 'Запоры'],
    contraindications: ['Аллергия на источник коллагена'],
  },
  hyaluronic: {
    description: 'Гиалуроновая кислота — главный компонент синовиальной жидкости и кожи. Удерживает 1000× вес воды. Восстанавливает суставы, увлажняет кожу.',
    mechanism: 'Связывание 1000× вес воды → гидратация суставов и кожи. ↑ синовиальная жидкость → амортизация. Ингибирование MMP → защита хряща. ↑ синтез эндогенной гиалуроновой кислоты.',
    mechanismKeys: ['WATER_BINDING', 'SYNOVIAL_UP', 'MMP_DOWN', 'HYALURONAN_UP'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['Гидратация суставов', '↑ синовиальная жидкость', 'Ингибирование MMP'] },
    ],
    risks: ['Болезненность в месте инъекции', 'Отёчность сустава'],
    contraindications: ['Инфекция в суставе (для инъекций)'],
  },
  boswellia: {
    description: 'Босвеллия (Boswellia serrata) — ингибитор 5-липоксигеназы и NF-κB. Мощное противовоспалительное для суставов, нейропротектор, снижает лейкотриены.',
    mechanism: 'Ингибирование 5-LOX → ↓ лейкотриены (LTB4, LTC4). Ингибирование NF-κB → ↓ TNF-α, ↓ IL-1β. ↓ MMP → защита хряща. Противовоспалительное без COX-ингибирования (без ЖК-побочек).',
    mechanismKeys: ['5LOX_DOWN', 'LEUKOTRIENE_DOWN', 'NFkB_DOWN', 'MMP_DOWN'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['Ингибирование 5-LOX', 'Снижение лейкотриенов', 'Защита хряща'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Нейропротекция'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Противовоспалительное'] },
    ],
    risks: ['Диарея при высоких дозах', 'Изжога', 'Кожная сыпь (редко)'],
    contraindications: ['Беременность', 'Приём антикоагулянтов'],
  },
vitamin_c: {
    description: 'Витамин C (аскорбиновая кислота) — водорастворимый антиоксидант №1. Кофактор синтеза коллагена, регенерирует витамин E, поддерживает иммунитет, синтез карнитина.',
    mechanism: 'Кофактор пролил-4-гидроксилазы и лизил-гидроксилазы → синтез коллагена. Прямое scavenging ROS. Регенерация витамина E из α-токоферил-радикала. Кофактор синтеза карнитина. ↑ иммунитет через NK-клетки и фагоцитоз.',
    mechanismKeys: ['COLLAGEN_SYNTHESIS_UP', 'ANTIOXIDANT', 'VITE_REGEN', 'CARNITINE_UP', 'IMMUNE_UP'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['Синтез коллагена', 'Антиоксидант', 'Регенерация'] },
      { key: 'hematologic', label: 'Гематологическая', mechanisms: ['Иммунитет', 'Поглощение железа'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Антиоксидант сосудов'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Нейропротекция'] },
    ],
    risks: ['Диарея при дозах >2 г', 'Оксалатные камни при предрасположенности', 'Взаимодействие с химиотерапией'],
    contraindications: ['Гемохроматоз', 'Оксалатные камни в анамнезе'],
  },
  bromelain: {
    description: 'Бромелайн — протеолитический фермент из ананаса. Фибринолитик, снижает отёк, модулирует цитокины (IL-1β, TNF-α), ингибирует NF-κB. Противовоспалительное и противоотёчное.',
    mechanism: 'Протеолиз фибрина → фибринолитическое действие. ↓ PGE2 и брадикинин → обезболивание. Ингибирование NF-κB → ↓ TNF-α и IL-1β. Модуляция цитокинов. ↓ отёк через деградацию кининов.',
    mechanismKeys: ['FIBRINOLYSIS_UP', 'PGE2_DOWN', 'NFkB_DOWN', 'CYTOKINE_MOD', 'EDEMA_DOWN'],
    systems: [
      { key: 'musculoskeletal', label: '', mechanisms: ['', '', ''] },
      { key: 'hematologic', label: '', mechanisms: [''] },
      { key: 'cardio', label: '', mechanisms: ['', ''] },
    ],
    risks: ['', '', '', ''],
    contraindications: ['', '', '', ''],
  },
  bpc157: {
    description: 'BPC-157 (Body Protection Compound) — пептид 15 а.к. из желудочного сока. Мощнейший регенератор: связки, сухожилия, хрящи, ЖКТ, нервная ткань. Ускоряет заживление в 2-3 раза.',
    mechanism: 'Активация VEGF → ангиогенез → неоваскуляризация. Активация FGF-2 → пролиферация фибробластов. ↑ коллаген I/III. Модуляция PI3K/AKT → клеточная миграция. Стабилизация NO-пути. Гепатопротекция.',
    mechanismKeys: ['VEGF_UP', 'ANGIOGENESIS_UP', 'FGF_UP', 'COLLAGEN_UP', 'PI3K_AKT_UP', 'GASTRO_PROTECT'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['Ангиогенез', 'Фибробласты', 'Коллаген I/III', 'Регенерация сухожилий'] },
      { key: 'neuro', label: 'Нервная', mechanisms: ['Нейропротекция', 'ГАМК-стабилизация'] },
      { key: 'hepatic', label: 'Печёночная', mechanisms: ['Гепатопротекция', 'Антиоксидант'] },
    ],
    risks: ['Стимуляция ангиогенеза при скрытых опухолях (теоретически)', 'Лёгкая тошнота'],
    contraindications: ['Активные злокачественные новообразования', 'Беременность'],
  },
  tb500: {
    description: 'TB-500 (тимозин β4) — пептид 43 а.к. Регулирует актин → мобильность клеток → заживление. Восстанавливает связки, сухожилия, кожу, сердечную мышцу. Синергия с BPC-157.',
    mechanism: 'Связывание с G-актином → полимеризация актиновых филаментов → мобильность клеток. ↑ VEGF → ангиогенез. ↓ TGF-β1 → снижение фиброза. Ингибирование NF-κB → противовоспалительное действие.',
    mechanismKeys: ['ACTIN_POLYMERIZE', 'CELL_MIGRATION_UP', 'VEGF_UP', 'TGF_B1_DOWN', 'NFkB_DOWN'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['Полимеризация актина', 'Миграция клеток', 'Ангиогенез', 'Противовоспалительное'] },
      { key: 'cardio', label: 'Сердечно-сосудистая', mechanisms: ['Кардиопротекция'] },
    ],
    risks: ['Потенциальная стимуляция ангиогенеза при опухолях', 'Лёгкая тошнота', 'Головная боль'],
    contraindications: ['Активные злокачественные новообразования', 'Беременность'],
  },
  meloxicam: {
    description: 'Мелоксикам — селективный ингибитор COX-2. Противовоспалительное и обезболивающее с меньшим ЖК-риском чем неселективные НПВС.',
    mechanism: 'Селективное ингибирование COX-2 → ↓ PGE2 (воспаление), сохранение COX-1 (защита слизистой ЖК). Обезболивание через ↓ сенсибилизации ноцицепторов.',
    mechanismKeys: ['COX2_SELECTIVE', 'PGE2_DOWN', 'ANALGESIC', 'ANTIINFLAMMATORY'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['Обезболивание', 'Противовоспалительное', 'Снижение отёка'] },
    ],
    risks: ['ЖК-кровотечение (реже чем неселективные)', 'Сердечно-сосудистый риск при длительном приёме', 'Нефротоксичность', 'Головокружение'],
    contraindications: ['Язвенная болезнь (обострение)', 'Тяжёлая почечная недостаточность', 'Беременность (III триместр)', 'Приём антикоагулянтов'],
  },
  diclofenac: {
    description: 'Диклофенак — неселективный НПВС. Ингибирует COX-1/COX-2, снижает PGE2. Обезболивающее и противовоспалительное. Кратковременное использование на курсе.',
    mechanism: 'Ингибирование циклооксигеназы (COX-1 и COX-2) → ↓ синтез простагландинов (PGE2, PGI2). Обезболивание через ↓ сенсибилизации ноцицепторов. Противовоспалительное через ↓ хемотаксиса.',
    mechanismKeys: ['COX1_2_INHIBIT', 'PGE2_DOWN', 'ANALGESIC', 'ANTIINFLAMMATORY', 'PLATELET_DOWN'],
    systems: [
      { key: 'musculoskeletal', label: 'Костно-мышечная', mechanisms: ['Обезболивание', 'Противовоспалительное', 'Снижение отёка'] },
    ],
    risks: ['Гастропатия (язвы, кровотечения)', 'Нефротоксичность при длительном приёме', 'Кардиваскулярный риск', 'Гепатотоксичность (редко)', 'Бронхоспазм при аспириновой астме'],
    contraindications: ['Язвенная болезнь', 'Печёночная недостаточность', 'ClCr<30', 'Аспириновая астма', 'Беременность (III триместр)', 'Кровотечения в анамнезе'],
  },
};

export class InfoErrorBoundary extends React.Component<{children?:React.ReactNode;label:string},{hasError:boolean;err:string}> {
  constructor(p:{children?:React.ReactNode;label:string}){super(p);this.state={hasError:false,err:''};}
  static getDerivedStateFromError(e:Error){return{hasError:true,err:String(e)};}
  render(){if(this.state.hasError)return <div style={{padding:16,textAlign:'center',color:'#ef4444',fontSize:10,background:'rgba(239,68,68,0.06)',borderRadius:8,border:'1px solid rgba(239,68,68,0.2)'}}>⚠ {this.props.label}: {this.state.err}</div>;return this.props.children;}
}

