/**
 * exercise-catalog-ta-supplement.ts — TA-специфичные упражнения (PLOS 2026, Torokhtiy)
 * Дополнение к EXERCISE_CATALOG без правки основного файла (кодировка PowerShell).
 * Регистрирует deficit_snatch etc с корректными группами для WLDiagnosticsHub.
 */
import type { Exercise } from './types';

export const TA_CATALOG_SUPPLEMENT: Exercise[] = [
  { id: 'deficit_snatch', name: 'Рывок с дефицита', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 7, targetMuscle: 'Ноги/спина (отрыв)', movementPattern: 'hinge', canReplace: ['snatch_pull'], cannotReplace: [] },
  { id: 'block_snatch', name: 'Рывок с блоков', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Подрыв', movementPattern: 'hinge', canReplace: ['snatch'], cannotReplace: [] },
  { id: 'pause_snatch', name: 'Рывок с паузой', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 7, targetMuscle: 'Средняя тяга', movementPattern: 'hinge', canReplace: ['snatch_pull'], cannotReplace: [] },
  { id: 'high_hang_snatch', name: 'Рывок с высокого виса', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Уход под штангу', movementPattern: 'hinge', canReplace: ['muscle_snatch'], cannotReplace: [] },
  { id: 'muscle_snatch', name: 'Масл-рывок', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Трапеции/плечи', movementPattern: 'vertical_push', canReplace: ['high_hang_snatch'], cannotReplace: [] },
  { id: 'deficit_clean', name: 'Взятие с дефицита', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 7, targetMuscle: 'Отрыв', movementPattern: 'hinge', canReplace: ['clean_pull'], cannotReplace: [] },
  { id: 'block_clean', name: 'Взятие с блоков', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Подрыв', movementPattern: 'hinge', canReplace: ['clean_and_jerk'], cannotReplace: [] },
  { id: 'pause_clean', name: 'Взятие с паузой', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 7, targetMuscle: 'Середина', movementPattern: 'hinge', canReplace: ['clean_pull'], cannotReplace: [] },
  { id: 'pause_jerk', name: 'Толчок с паузой', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Фиксация', movementPattern: 'vertical_push', canReplace: ['split_jerk'], cannotReplace: [] },
  { id: 'jerk_dip', name: 'Подсед для толчка', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Квадрицепс', movementPattern: 'squat', canReplace: ['pause_jerk'], cannotReplace: [] },
  { id: 'snatch_pull', name: 'Рывковая тяга', group: 'back', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 8, targetMuscle: 'Тяга', movementPattern: 'hinge', canReplace: ['pause_pull'], cannotReplace: [] },
  { id: 'clean_pull', name: 'Толчковая тяга', group: 'back', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 8, targetMuscle: 'Тяга', movementPattern: 'hinge', canReplace: ['snatch_pull'], cannotReplace: [] },
  { id: 'pause_pull', name: 'Тяга с паузой', group: 'back', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 7, targetMuscle: 'Проход коленей', movementPattern: 'hinge', canReplace: ['deficit_pull'], cannotReplace: [] },
  { id: 'overhead_squat_v2', name: 'Присед оверхед', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Оверхед сед', movementPattern: 'squat', canReplace: ['snatch_balance'], cannotReplace: [] },
  // ── ROUND-9: закрыт синтетический дрейф — все id библиотеки коррекции теперь реальные записи ──
  // Рывок/тяга
  { id: 'segment_snatch', name: 'Сегментный рывок', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Спина/подрыв (по сегментам)', movementPattern: 'hinge', canReplace: ['pause_snatch'], cannotReplace: [] },
  { id: 'slow_pull_snatch', name: 'Медленный рывок (тяга 3 с)', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Спина (стартовая тяга)', movementPattern: 'hinge', canReplace: ['segment_snatch'], cannotReplace: [] },
  { id: 'snatch_liftoff', name: 'Отрыв рывковый до колена', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Становая позиция', movementPattern: 'hinge', canReplace: ['deficit_snatch'], cannotReplace: [] },
  { id: 'tall_snatch', name: 'Толл-рывок', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Уход под штангу', movementPattern: 'hinge', canReplace: ['high_hang_snatch'], cannotReplace: [] },
  { id: 'drop_snatch', name: 'Drop-рывок', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Скорость ухода', movementPattern: 'hinge', canReplace: ['tall_snatch'], cannotReplace: [] },
  { id: 'nofeet_snatch', name: 'Рывок без отрыва пяток', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Вертикальный драйв', movementPattern: 'hinge', canReplace: ['tall_snatch'], cannotReplace: [] },
  { id: 'dip_snatch', name: 'Рывок под бедро (dip)', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Высокий подрыв', movementPattern: 'hinge', canReplace: ['high_hang_snatch'], cannotReplace: [] },
  { id: 'snatch_deadlift', name: 'Становая рывковым хватом 105%', group: 'back', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 7, targetMuscle: 'Спина/ноги', movementPattern: 'hinge', canReplace: ['snatch_pull'], cannotReplace: [] },
  { id: 'deficit_pull', name: 'Тяга с дефицита', group: 'back', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 8, targetMuscle: 'Спина (старт)', movementPattern: 'hinge', canReplace: ['pause_pull'], cannotReplace: [] },
  { id: 'hip_snatch', name: 'Рывок от бедра', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Подрыв (высокий старт)', movementPattern: 'hinge', canReplace: ['high_hang_snatch'], cannotReplace: [] },
  // Взятие
  { id: 'clean_segment', name: 'Сегментное взятие', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Спина/подрыв (по сегментам)', movementPattern: 'hinge', canReplace: ['pause_clean'], cannotReplace: [] },
  { id: 'high_hang_clean', name: 'Взятие с высокого виса', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Уход под штангу', movementPattern: 'hinge', canReplace: ['tall_clean'], cannotReplace: [] },
  { id: 'hang_clean_knee', name: 'Взятие с виса выше колена', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Подрыв', movementPattern: 'hinge', canReplace: ['high_hang_clean'], cannotReplace: [] },
  { id: 'tall_clean', name: 'Толл-взятие', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Уход под штангу', movementPattern: 'hinge', canReplace: ['high_hang_clean'], cannotReplace: [] },
  { id: 'muscle_clean', name: 'Масл-взятие', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Трапеции/плечи', movementPattern: 'vertical_push', canReplace: ['muscle_snatch'], cannotReplace: [] },
  { id: 'front_rack_hold', name: 'Удержание фронта 8 с', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Фронт-стойка', movementPattern: 'squat', canReplace: ['front_squat'], cannotReplace: [] },
  { id: 'clean_shrug', name: 'Шраги толчковые 110%', group: 'back', type: 'isolation', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Трапеции', movementPattern: 'isolation_back', canReplace: ['clean_pull'], cannotReplace: [] },
  // Толчок/жим
  { id: 'push_jerk_pause', name: 'Швунг толчковый с паузой', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Полусед/фиксация', movementPattern: 'vertical_push', canReplace: ['push_jerk'], cannotReplace: [] },
  { id: 'double_pause_jerk', name: 'Толчок с двойной паузой', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Стабильность толчка', movementPattern: 'vertical_push', canReplace: ['pause_jerk'], cannotReplace: [] },
  { id: 'jerk_balance', name: 'Толчковый баланс', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Ножницы (без дипа)', movementPattern: 'vertical_push', canReplace: ['split_jerk'], cannotReplace: [] },
  { id: 'behind_neck_jerk', name: 'Толчок из-за головы', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'high', fatigueCost: 7, targetMuscle: 'Плечи/фиксация', movementPattern: 'vertical_push', canReplace: ['push_jerk'], cannotReplace: [] },
  { id: 'tall_jerk', name: 'Толл-толчок', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Панч ногами', movementPattern: 'vertical_push', canReplace: ['push_jerk'], cannotReplace: [] },
  { id: 'split_jerk', name: 'Толчок в ножницы', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Фиксация в ножницах', movementPattern: 'vertical_push', canReplace: ['push_jerk'], cannotReplace: [] },
  { id: 'jerk_recovery', name: 'Восстановление из ножниц', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Фиксация/шаги', movementPattern: 'vertical_push', canReplace: ['jerk_support'], cannotReplace: [] },
  { id: 'jerk_support', name: 'Удержание толчка в ножницах', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Фиксация', movementPattern: 'vertical_push', canReplace: ['overhead_hold'], cannotReplace: [] },
  { id: 'jerk_split_measure', name: 'Замер ножниц (мел)', group: 'legs', type: 'isolation', equipment: 'bodyweight', difficulty: 'beginner', jointStress: 'low', fatigueCost: 2, targetMuscle: 'Стабильность ножниц', movementPattern: 'lunge', canReplace: ['split_pause'], cannotReplace: [] },
  { id: 'oh_lunge', name: 'Выпады над головой', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Ноги/плечи', movementPattern: 'lunge', canReplace: ['split_pause'], cannotReplace: [] },
  { id: 'split_pause', name: 'Ножницы с паузой 2 с', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Ноги/ягодицы', movementPattern: 'lunge', canReplace: ['oh_lunge'], cannotReplace: [] },
  { id: 'heaving_balance', name: 'Хивинг-баланс', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Ноги/плечи', movementPattern: 'vertical_push', canReplace: ['snatch_balance'], cannotReplace: [] },
  { id: 'snatch_push_press', name: 'Рывковый швунг-жим', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Плечи/ноги (драйв)', movementPattern: 'vertical_push', canReplace: ['push_press'], cannotReplace: [] },
  { id: 'sots_press', name: 'Соц-жим', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'high', fatigueCost: 5, targetMuscle: 'Плечи (из седа)', movementPattern: 'vertical_push', canReplace: ['overhead_squat_v2'], cannotReplace: [] },
  { id: 'overhead_hold', name: 'Оверхед-холд', group: 'shoulders', type: 'isolation', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 3, targetMuscle: 'Фиксация над головой', movementPattern: 'isolation_shoulders', canReplace: ['jerk_support'], cannotReplace: [] },
  { id: 'pin_press', name: 'Жим с упоров', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Плечи (мёртвая точка)', movementPattern: 'vertical_push', canReplace: ['pin_press_high'], cannotReplace: [] },
  { id: 'pin_press_high', name: 'Жим с высоких упоров', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Плечи/трицепс', movementPattern: 'vertical_push', canReplace: ['pin_press'], cannotReplace: [] },
  { id: 'z_press', name: 'Z-жим сидя', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Плечи/кор', movementPattern: 'vertical_push', canReplace: ['ohp'], cannotReplace: [] },
  { id: 'single_arm_press', name: 'Односторонний жим стоя', group: 'shoulders', type: 'compound', equipment: 'dumbbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Плечи/кор', movementPattern: 'vertical_push', canReplace: ['ohp'], cannotReplace: [] },
  { id: 'klokov_press', name: 'Жим Клокова', group: 'shoulders', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'high', fatigueCost: 6, targetMuscle: 'Плечи (за головой)', movementPattern: 'vertical_push', canReplace: ['ohp'], cannotReplace: [] },
  // Присед/кор
  { id: 'pause_squat', name: 'Приседания с паузой 3 с', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 7, targetMuscle: 'Квадрицепс (низ)', movementPattern: 'squat', canReplace: ['tempo_squat'], cannotReplace: [] },
  { id: 'back_squat', name: 'Приседания со штангой', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'med', fatigueCost: 8, targetMuscle: 'Квадрицепс/ягодицы', movementPattern: 'squat', canReplace: ['front_squat_v2'], cannotReplace: [] },
  { id: 'tempo_squat', name: 'Темповые приседания 3-0-1', group: 'legs', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Квадрицепс (контроль)', movementPattern: 'squat', canReplace: ['pause_squat'], cannotReplace: [] },
  { id: 'tspine_ext', name: 'Разгибание грудного отдела', group: 'core', type: 'isolation', equipment: 'bodyweight', difficulty: 'beginner', jointStress: 'low', fatigueCost: 2, targetMuscle: 'Грудной отдел', movementPattern: 'core', canReplace: [], cannotReplace: [] },
  { id: 'dead_bug_oh', name: 'Dead bug с палкой над головой', group: 'core', type: 'isolation', equipment: 'bodyweight', difficulty: 'beginner', jointStress: 'low', fatigueCost: 2, targetMuscle: 'Кор (антиэкстензия)', movementPattern: 'core', canReplace: [], cannotReplace: [] },
  { id: 'pallof_hold', name: 'Паллоф-холд', group: 'core', type: 'isolation', equipment: 'bodyweight', difficulty: 'beginner', jointStress: 'low', fatigueCost: 2, targetMuscle: 'Кор (антиротация)', movementPattern: 'anti_rotation', canReplace: [], cannotReplace: [] },
];

// side-effect регистрация (опционально, если EXERCISE_CATALOG импортирует)
try {
  const { EXERCISE_CATALOG } = require('./exercise-catalog') as any;
  if (Array.isArray(EXERCISE_CATALOG)) {
    for (const ex of TA_CATALOG_SUPPLEMENT) if (!EXERCISE_CATALOG.find((e: any) => e.id === ex.id)) EXERCISE_CATALOG.push(ex);
  }
} catch {}
