/**
 * exercise-catalog-arm.ts — арм-упражнения (отдельный файл, не трогает main catalog).
 * 60 упражнений для армрестлинга/армлифтинга. Все поля как в exercise-catalog.ts.
 * Мерж делается локально в arm-движке.
 */
import type { Exercise } from './types';

export const ARM_EXERCISES: Exercise[] = [
  { id: 'wrist_curl_belt', name: 'Сгибание кисти через ремень (пояс)', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Сгибатели кисти (cup)', order: 1, substitutionGroup: 'cup_iso', movementPattern: 'cupping' as any, canReplace: ['wrist_curl_bb','wrist_curl_db'], cannotReplace: ['pronation_cable','side_press_cable'], technique: 'Ремень через проксимальную фалангу указательного пальца. Кисть не проваливается — фиксация.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Кузнецов: через ремень на фалангу, угол локтя <=120, фиксация кисти.' },
  { id: 'wrist_curl_bb', name: 'Сгибание кисти со штангой', group: 'arms', type: 'isolation', equipment: 'barbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Сгибатели кисти', order: 1, substitutionGroup: 'cup_iso', movementPattern: 'cupping' as any, canReplace: ['wrist_curl_belt','wrist_curl_db'], cannotReplace: ['pronation_cable'], technique: 'Предплечье на скамье, кисть свисает. Сгибание к себе.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'База cup. 4x6-8 тяж + 2x15 памп.' },
  { id: 'wrist_curl_db', name: 'Сгибание кисти с гантелью', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Сгибатели кисти', order: 1, substitutionGroup: 'cup_iso', movementPattern: 'cupping' as any, canReplace: ['wrist_curl_bb'], cannotReplace: ['pronation_cable'], technique: 'Одной рукой, предплечье на колене.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Односторонний cup.' },
  { id: 'wrist_ext_bb', name: 'Разгибание кисти со штангой', group: 'arms', type: 'isolation', equipment: 'barbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 3, targetMuscle: 'Разгибатели кисти', order: 2, substitutionGroup: 'wrist_ext', movementPattern: 'wrist_extension' as any, canReplace: ['wrist_ext_db'], cannotReplace: ['wrist_curl_bb'], technique: 'Ладони вниз, разгибание к себе. High-rep на жжение.', pauseSeconds: 1, peakContraction: false, stretchPhase: false, comments: 'Баланс flex/ext. High reps.' },
  { id: 'riser_lift', name: 'Riser lift (Judo belt + pin)', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Rising (пальцы)', order: 1, substitutionGroup: 'rising', movementPattern: 'rising' as any, canReplace: ['plate_pinch_hold'], cannotReplace: ['wrist_curl_bb'], technique: 'Вертикальная ручка, подъём за счёт пальцев (Devon Larratt).', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Rising — удержание над соперником.' },
  { id: 'wrist_roller', name: 'Ролик для запястья', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'beginner', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Сгибатели/разгибатели', order: 2, substitutionGroup: 'wrist_roll', movementPattern: 'cupping' as any, canReplace: ['wrist_curl_bb'], cannotReplace: ['side_press_cable'], technique: 'Накручивание веса вращением кистей. Вверх-вниз = 1 подход.', pauseSeconds: 0, peakContraction: false, stretchPhase: false, comments: 'Олдскул для предплечий.' },
  { id: 'ulnar_dev', name: 'Локтевое отведение (ulnar)', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 3, targetMuscle: 'Локтевые девиаторы', order: 2, substitutionGroup: 'ulnar_iso', movementPattern: 'ulnar_deviation' as any, canReplace: ['radial_dev'], cannotReplace: ['pronation_cable'], technique: 'Гантель вдоль тела, кисть к мизинцу.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Ulnar deviation.' },
  { id: 'radial_dev', name: 'Лучевое отведение (radial)', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 3, targetMuscle: 'Лучевые девиаторы', order: 2, substitutionGroup: 'radial_iso', movementPattern: 'radial_deviation' as any, canReplace: ['ulnar_dev'], cannotReplace: ['pronation_cable'], technique: 'Кисть к большому пальцу.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Radial deviation.' },
  { id: 'pronation_cable', name: 'Пронация на блоке (90)', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Пронаторы', order: 1, substitutionGroup: 'pronation', movementPattern: 'pronation' as any, canReplace: ['pronation_sledge','pronation_strap'], cannotReplace: ['supination_cable','wrist_curl_bb'], technique: 'Локоть 90 у корпуса, вращение внутрь. 5x5 heavy.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Топролл. Не заменяет супинацию!' },
  { id: 'pronation_sledge', name: 'Пронация кувалдой', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Пронаторы', order: 1, substitutionGroup: 'pronation', movementPattern: 'pronation' as any, canReplace: ['pronation_cable'], cannotReplace: ['supination_cable'], technique: 'Кувалда/рычаг, микро-амплитуда, фиксация.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Tendon density.' },
  { id: 'pronation_pulses', name: 'Пронация — пульсы (tendon)', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'beginner', jointStress: 'low', fatigueCost: 3, targetMuscle: 'Пронаторы (сухожилие)', order: 2, substitutionGroup: 'pronation', movementPattern: 'pronation' as any, canReplace: ['pronation_cable'], cannotReplace: ['supination_cable'], technique: 'Микро-диапазон, 15-20 пульсов.', pauseSeconds: 0, peakContraction: false, stretchPhase: false, comments: 'Tendon conditioning.' },
  { id: 'pronation_strap', name: 'Пронация ремнем на столе', group: 'arms', type: 'isolation', equipment: 'band', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Пронаторы', order: 1, substitutionGroup: 'pronation', movementPattern: 'pronation' as any, canReplace: ['pronation_cable'], cannotReplace: ['supination_cable'], technique: 'Ремень через кисть, вращение к столу.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Специфика стола.' },
  { id: 'supination_cable', name: 'Супинация на блоке (drag к бедру)', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Супинаторы', order: 1, substitutionGroup: 'supination', movementPattern: 'supination' as any, canReplace: ['supination_hammer'], cannotReplace: ['pronation_cable','wrist_curl_bb'], technique: 'Тяга локтя к бедру + супинация.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Hook. Drag to hip.' },
  { id: 'supination_hammer', name: 'Супинация молотком', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Супинаторы', order: 1, substitutionGroup: 'supination', movementPattern: 'supination' as any, canReplace: ['supination_cable'], cannotReplace: ['pronation_cable'], technique: 'Молот, вращение наружу.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Hook support.' },
  { id: 'indian_clubs', name: 'Indian clubs — pron/sup', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 3, targetMuscle: 'Пронаторы/супинаторы', order: 2, substitutionGroup: 'pron_sup', movementPattern: 'pronation' as any, canReplace: ['pronation_cable','supination_cable'], cannotReplace: ['side_press_cable'], technique: 'Легкие булавы 5 lbs, high-rep.', pauseSeconds: 0, peakContraction: false, stretchPhase: false, comments: 'Balance + blood flow.' },
  { id: 'lever_top', name: 'Levertop — удержание', group: 'arms', type: 'isolation', equipment: 'grip_tool', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Пронаторы/супинаторы', order: 1, substitutionGroup: 'pron_sup', movementPattern: 'pronation' as any, canReplace: ['pronation_cable'], cannotReplace: ['wrist_curl_bb'], technique: 'Удержание рычага горизонтально.', pauseSeconds: 3, peakContraction: true, stretchPhase: false, comments: 'Static hold.' },
  { id: 'hammer_curl_thick', name: 'Молот с толстым грифом', group: 'arms', type: 'compound', equipment: 'dumbbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Брахиалис', order: 1, substitutionGroup: 'hammer', movementPattern: 'hammer_curl' as any, canReplace: ['hammer_belt','hammer_db'], cannotReplace: ['side_press_cable'], technique: 'Нейтральный хват, спина нейтрально как за столом.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Hammer — брахиалис.' },
  { id: 'hammer_belt', name: 'Молот через ремень (на фалангу)', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Брахиалис + кисть', order: 1, substitutionGroup: 'hammer', movementPattern: 'hammer_curl' as any, canReplace: ['hammer_curl_thick'], cannotReplace: ['side_press_cable'], technique: 'Ремень через фалангу, угол локтя <=120, кисть фиксирована.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Кузнецов: фиксация кисти обязательна.' },
  { id: 'reverse_ez_curl', name: 'Обратные сгибания EZ', group: 'arms', type: 'isolation', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Брахиорадиалис', order: 1, substitutionGroup: 'reverse_curl', movementPattern: 'hammer_curl' as any, canReplace: ['hammer_curl_thick'], cannotReplace: ['side_press_cable'], technique: 'Пронированный хват, строго.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Двойной эффект — wrist ext.' },
  { id: 'zottman_curl', name: 'Сгибания Зоттмана', group: 'arms', type: 'compound', equipment: 'dumbbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Бицепс + предплечье', order: 1, substitutionGroup: 'bicep_curl', movementPattern: 'hammer_curl' as any, canReplace: ['hammer_curl_thick'], cannotReplace: ['side_press_cable'], technique: 'Вверх супинация, вниз пронация.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Бицепс + брахиорадиалис.' },
  { id: 'preacher_hammer', name: 'Молот на скамье Скотта', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Брахиалис', order: 2, substitutionGroup: 'hammer', movementPattern: 'hammer_curl' as any, canReplace: ['hammer_curl_thick'], cannotReplace: ['side_press_cable'], technique: 'Изолированно, без читинга.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Строгий молот.' },
  { id: 'incline_hammer', name: 'Молот на наклонной', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Длинная головка бицепса', order: 1, substitutionGroup: 'hammer', movementPattern: 'hammer_curl' as any, canReplace: ['hammer_curl_thick'], cannotReplace: ['side_press_cable'], technique: 'Растянутая позиция.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Lengthened.' },
  { id: 'side_press_cable', name: 'Боковое давление на блоке', group: 'arms', type: 'compound', equipment: 'cable', difficulty: 'advanced', jointStress: 'high', fatigueCost: 8, targetMuscle: 'Боковое давление', order: 1, substitutionGroup: 'side_press', movementPattern: 'side_press' as any, canReplace: ['side_press_table'], cannotReplace: ['pronation_cable','wrist_curl_bb'], technique: 'Локоть на подушке высота стола, давление перпендикулярно. Медленно! Humerus-risk.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Опасно — прогрессия <=10%/нед, RIR>=2.' },
  { id: 'side_press_table', name: 'Боковое у стола (изометрия)', group: 'arms', type: 'compound', equipment: 'band', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Боковое', order: 1, substitutionGroup: 'side_press', movementPattern: 'side_press' as any, canReplace: ['side_press_cable'], cannotReplace: ['pronation_cable'], technique: 'Упор в неподвижную перекладину 10с.', pauseSeconds: 3, peakContraction: true, stretchPhase: false, comments: 'Изометрия безопаснее блока.' },
  { id: 'lat_drag_belt', name: 'Тяга широчайших ремнём (к запястью)', group: 'back', type: 'compound', equipment: 'cable', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 7, targetMuscle: 'Широчайшие (back pressure)', order: 1, substitutionGroup: 'back_drag', movementPattern: 'back_drag' as any, canReplace: ['row_strap_hip','landmine_row_under'], cannotReplace: ['side_press_cable'], technique: 'Ремень вокруг запястья, тяга к себе как топролл старт.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Back pressure.' },
  { id: 'row_strap_hip', name: 'Тяга к бедру с ремнём', group: 'back', type: 'compound', equipment: 'cable', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Широчайшие', order: 1, substitutionGroup: 'back_drag', movementPattern: 'back_drag' as any, canReplace: ['lat_drag_belt'], cannotReplace: ['side_press_cable'], technique: 'Рука к карману, локоть прижат.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Hook drag.' },
  { id: 'landmine_row_under', name: 'Тяга лэндмайн одной рукой (супинация)', group: 'back', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Широчайшие', order: 1, substitutionGroup: 'back_drag', movementPattern: 'back_drag' as any, canReplace: ['lat_drag_belt'], cannotReplace: ['side_press_cable'], technique: 'Супинированный хват, микс тяж 5 + 12.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Rising back pressure.' },
  { id: 'internal_rotation_band', name: 'Внутренняя ротация плеча (резина)', group: 'shoulders', type: 'isolation', equipment: 'band', difficulty: 'beginner', jointStress: 'low', fatigueCost: 2, targetMuscle: 'Ротаторная манжета', order: 3, substitutionGroup: 'shoulder_int', movementPattern: 'shoulder_internal' as any, canReplace: ['external_rotation_band'], cannotReplace: ['side_press_cable'], technique: 'High-rep 12-20, не в отказ.', pauseSeconds: 1, peakContraction: false, stretchPhase: false, comments: 'Защита плеча.' },
  { id: 'external_rotation_band', name: 'Наружная ротация (резина)', group: 'shoulders', type: 'isolation', equipment: 'band', difficulty: 'beginner', jointStress: 'low', fatigueCost: 2, targetMuscle: 'Ротаторная манжета', order: 3, substitutionGroup: 'shoulder_ext', movementPattern: 'shoulder_internal' as any, canReplace: ['internal_rotation_band'], cannotReplace: ['side_press_cable'], technique: 'High-rep, контроль.', pauseSeconds: 1, peakContraction: false, stretchPhase: false, comments: 'Антагонист.' },
  { id: 'table_pushdown_iso', name: 'Изометрия у стола 10с', group: 'arms', type: 'compound', equipment: 'band', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Боковое + кисть', order: 1, substitutionGroup: 'side_press', movementPattern: 'side_press' as any, canReplace: ['side_press_cable'], cannotReplace: ['pronation_cable'], technique: 'Локоть на подушке, давление в неподвижный упор 10с макс.', pauseSeconds: 3, peakContraction: true, stretchPhase: false, comments: 'Isometric hold.' },
  { id: 'hook_drag_cable', name: 'Hook drag на блоке', group: 'arms', type: 'compound', equipment: 'cable', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Брахиалис + кисть', order: 1, substitutionGroup: 'hook_drag', movementPattern: 'back_drag' as any, canReplace: ['lat_drag_belt'], cannotReplace: ['side_press_cable'], technique: 'Супинация + тяга на себя.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Hook.' },
  { id: 'anti_rotation_hold', name: 'Антиротация (split-stance)', group: 'core', type: 'isolation', equipment: 'cable', difficulty: 'beginner', jointStress: 'low', fatigueCost: 3, targetMuscle: 'Кор', order: 3, substitutionGroup: 'core_anti', movementPattern: 'core_anchor' as any, canReplace: ['ab_wheel'], cannotReplace: ['side_press_cable'], technique: 'Трос тянет вбок, корпус квадрат.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Якорь.' },
  { id: 'rolling_thunder', name: 'Rolling Thunder (вращающаяся ручка)', group: 'arms', type: 'compound', equipment: 'grip_tool', difficulty: 'advanced', jointStress: 'low', fatigueCost: 7, targetMuscle: 'Хват поддержка', order: 1, substitutionGroup: 'grip_support', movementPattern: 'grip_support' as any, canReplace: ['apollon_axle','farmer_walk_fat'], cannotReplace: ['plate_pinch_hold','coc_gripper'], technique: '60мм вращающаяся, DOH, без лямок. Тяга одной рукой.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Support grip. WR 130.5кг.' },
  { id: 'apollon_axle', name: 'Apollon Axle тяга (58мм)', group: 'arms', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'low', fatigueCost: 8, targetMuscle: 'Хват поддержка', order: 1, substitutionGroup: 'grip_support', movementPattern: 'grip_support' as any, canReplace: ['rolling_thunder'], cannotReplace: ['plate_pinch_hold'], technique: '58мм DOH, без лямок/разнохвата. Вес меньше обычной тяги.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Axle. 1x/нед.' },
  { id: 'saxon_bar', name: 'Saxon Bar тяга (3 щипок)', group: 'arms', type: 'compound', equipment: 'barbell', difficulty: 'advanced', jointStress: 'low', fatigueCost: 7, targetMuscle: 'Хват щипок', order: 1, substitutionGroup: 'grip_pinch', movementPattern: 'grip_pinch' as any, canReplace: ['hub_pinch','plate_pinch_hold'], cannotReplace: ['rolling_thunder','coc_gripper'], technique: 'Прямоугольник 3, двумя руками щипок.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Pinch.' },
  { id: 'hub_pinch', name: 'Хаб щипок (IronMind Hub)', group: 'arms', type: 'isolation', equipment: 'grip_tool', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Хват щипок', order: 1, substitutionGroup: 'grip_pinch', movementPattern: 'grip_pinch' as any, canReplace: ['saxon_bar','plate_pinch_hold'], cannotReplace: ['rolling_thunder'], technique: 'Щипок хаба, удержание.', pauseSeconds: 3, peakContraction: true, stretchPhase: false, comments: 'Hub.' },
  { id: 'plate_pinch_hold', name: 'Щипок блинов (удержание)', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Хват щипок', order: 1, substitutionGroup: 'grip_pinch', movementPattern: 'grip_pinch' as any, canReplace: ['hub_pinch','saxon_bar'], cannotReplace: ['rolling_thunder'], technique: 'Два блина гладкими наружу, удержание 10-20с.', pauseSeconds: 3, peakContraction: true, stretchPhase: false, comments: 'Pinch endurance.' },
  { id: 'coc_gripper', name: 'Эспандер CoC (дробление)', group: 'arms', type: 'isolation', equipment: 'grip_tool', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Хват дробление', order: 1, substitutionGroup: 'grip_crush', movementPattern: 'grip_crush' as any, canReplace: ['silver_bullet_hold'], cannotReplace: ['rolling_thunder','plate_pinch_hold'], technique: 'Сжатие до касания ручек.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Crush.' },
  { id: 'silver_bullet_hold', name: 'Silver Bullet hold', group: 'arms', type: 'isolation', equipment: 'grip_tool', difficulty: 'advanced', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Хват дробление', order: 1, substitutionGroup: 'grip_crush', movementPattern: 'grip_crush' as any, canReplace: ['coc_gripper'], cannotReplace: ['rolling_thunder'], technique: 'Удержание эспандера с патроном.', pauseSeconds: 3, peakContraction: true, stretchPhase: false, comments: 'Crush hold.' },
  { id: 'farmer_walk_fat', name: 'Фермер с Fat Gripz', group: 'arms', type: 'compound', equipment: 'dumbbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Хват поддержка', order: 1, substitutionGroup: 'grip_support', movementPattern: 'grip_support' as any, canReplace: ['rolling_thunder'], cannotReplace: ['plate_pinch_hold'], technique: '20-30м с толстыми ручками.', pauseSeconds: 0, peakContraction: true, stretchPhase: false, comments: 'Support + ноги.' },
  { id: 'fat_gripz_curl', name: 'Сгибания с Fat Gripz', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Хват + бицепс', order: 2, substitutionGroup: 'grip_support', movementPattern: 'grip_support' as any, canReplace: ['farmer_walk_fat'], cannotReplace: ['plate_pinch_hold'], technique: 'Любые сгибания с накладками.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Дешёвый старт armlifting.' },
  // === PRO expansion 20 (60 total) — towel/fatbar/pinch80/CoC levels/containment ===
  { id: 'towel_pullup', name: 'Подтягивания на полотенце', group: 'back', type: 'compound', equipment: 'bodyweight', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Хват поддержка + широчайшие', order: 2, substitutionGroup: 'grip_support', movementPattern: 'grip_support' as any, canReplace: ['rolling_thunder','fat_bar_deadlift'], cannotReplace: ['coc_gripper','plate_pinch_hold'], technique: 'Полотенце через перекладину, DOH, без лямок.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Crush + brachioradialis.' },
  { id: 'fat_bar_deadlift', name: 'Становая с Fat Bar 50мм', group: 'back', type: 'compound', equipment: 'barbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 7, targetMuscle: 'Хват поддержка', order: 1, substitutionGroup: 'grip_support', movementPattern: 'grip_support' as any, canReplace: ['rolling_thunder','apollon_axle'], cannotReplace: ['plate_pinch_hold','coc_gripper'], technique: '50мм гриф, DOH, без лямок/разнохвата.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Axle lite.' },
  { id: 'pinch_block_80', name: 'Pinch Block 80мм двуручный', group: 'arms', type: 'compound', equipment: 'grip_tool', difficulty: 'advanced', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Хват щипок', order: 1, substitutionGroup: 'grip_pinch', movementPattern: 'grip_pinch' as any, canReplace: ['saxon_bar','hub_pinch'], cannotReplace: ['rolling_thunder','coc_gripper'], technique: 'Деревянный блок 80мм, щипок двумя руками, тяга.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Pinch 80 — замена Saxon при отсутствии.' },
  { id: 'excalibur_handle', name: 'Excalibur 50мм вращающаяся', group: 'arms', type: 'isolation', equipment: 'grip_tool', difficulty: 'advanced', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Хват поддержка', order: 1, substitutionGroup: 'grip_support', movementPattern: 'grip_support' as any, canReplace: ['rolling_thunder'], cannotReplace: ['plate_pinch_hold'], technique: 'Одна рука, 50мм вращающаяся, как RT но 50мм.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Excalibur.' },
  { id: 'little_big_horn', name: 'Little Big Horn конус', group: 'arms', type: 'isolation', equipment: 'grip_tool', difficulty: 'advanced', jointStress: 'low', fatigueCost: 6, targetMuscle: 'Хват щипок', order: 1, substitutionGroup: 'grip_pinch', movementPattern: 'grip_pinch' as any, canReplace: ['hub_pinch','saxon_bar'], cannotReplace: ['rolling_thunder'], technique: 'Конус 76→50мм, щипок, удержание.', pauseSeconds: 3, peakContraction: true, stretchPhase: false, comments: 'Horn pinch.' },
  { id: 'coc_trainer', name: 'CoC Trainer (100 lb)', group: 'arms', type: 'isolation', equipment: 'grip_tool', difficulty: 'beginner', jointStress: 'low', fatigueCost: 3, targetMuscle: 'Хват дробление', order: 2, substitutionGroup: 'grip_crush', movementPattern: 'grip_crush' as any, canReplace: ['coc_gripper'], cannotReplace: ['rolling_thunder','plate_pinch_hold'], technique: 'Trainer 100lb, закрытие.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Crush lvl1.' },
  { id: 'coc_no1', name: 'CoC No.1 (140 lb)', group: 'arms', type: 'isolation', equipment: 'grip_tool', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Хват дробление', order: 1, substitutionGroup: 'grip_crush', movementPattern: 'grip_crush' as any, canReplace: ['coc_trainer','coc_no1_5'], cannotReplace: ['rolling_thunder'], technique: 'No.1 140lb.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Crush lvl2.' },
  { id: 'coc_no1_5', name: 'CoC No.1.5 (167.5 lb)', group: 'arms', type: 'isolation', equipment: 'grip_tool', difficulty: 'advanced', jointStress: 'low', fatigueCost: 5, targetMuscle: 'Хват дробление', order: 1, substitutionGroup: 'grip_crush', movementPattern: 'grip_crush' as any, canReplace: ['coc_no1','coc_no2'], cannotReplace: ['rolling_thunder'], technique: 'No.1.5 167.5lb.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Crush lvl3.' },
  { id: 'coc_no2', name: 'CoC No.2 (195 lb)', group: 'arms', type: 'isolation', equipment: 'grip_tool', difficulty: 'advanced', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Хват дробление', order: 1, substitutionGroup: 'grip_crush', movementPattern: 'grip_crush' as any, canReplace: ['coc_no1_5'], cannotReplace: ['rolling_thunder','plate_pinch_hold'], technique: 'No.2 195lb, competitive.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Crush lvl4 competitive.' },
  { id: 'finger_containment_band', name: 'Finger containment (резина)', group: 'arms', type: 'isolation', equipment: 'band', difficulty: 'beginner', jointStress: 'low', fatigueCost: 3, targetMuscle: 'Rising + пальцы', order: 2, substitutionGroup: 'rising', movementPattern: 'rising' as any, canReplace: ['riser_lift'], cannotReplace: ['wrist_curl_bb'], technique: 'Резина вокруг пальцев, разведение против сопротивления.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Containment — не распахивать пальцы.' },
  { id: 'wrist_curl_behind', name: 'Сгибание кисти за спиной', group: 'arms', type: 'isolation', equipment: 'barbell', difficulty: 'beginner', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Сгибатели кисти', order: 1, substitutionGroup: 'cup_iso', movementPattern: 'cupping' as any, canReplace: ['wrist_curl_bb'], cannotReplace: ['pronation_cable'], technique: 'Стоя, штанга за спиной, кисти к себе.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Behind-back cup (StrengthLog).' },
  { id: 'hammer_rope_cable', name: 'Молот канатом на блоке', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'beginner', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Брахиалис', order: 2, substitutionGroup: 'hammer', movementPattern: 'hammer_curl' as any, canReplace: ['hammer_curl_thick'], cannotReplace: ['side_press_cable'], technique: 'Канат, нейтральный хват.', pauseSeconds: 1, peakContraction: true, stretchPhase: true, comments: 'Rope hammer.' },
  { id: 'reverse_curl_cable', name: 'Обратные сгибания на блоке', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'beginner', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Брахиорадиалис', order: 2, substitutionGroup: 'reverse_curl', movementPattern: 'hammer_curl' as any, canReplace: ['reverse_ez_curl'], cannotReplace: ['side_press_cable'], technique: 'Канат/прямая, пронированно.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Cable reverse.' },
  { id: 'side_belt_table', name: 'Боковое ремнём на столе (safe)', group: 'arms', type: 'isolation', equipment: 'band', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Боковое давление', order: 1, substitutionGroup: 'side_press', movementPattern: 'side_press' as any, canReplace: ['side_press_table','table_pushdown_iso'], cannotReplace: ['pronation_cable'], technique: 'Ремень на столе, вектор как в борьбе, не на блоке (чемпионы отказались от блока).', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'Safe side — ремень, не блок.' },
  { id: 'cup_to_little', name: 'Cup к мизинцу (РН)', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Сгибатели кисти', order: 1, substitutionGroup: 'cup_iso', movementPattern: 'cupping' as any, canReplace: ['wrist_curl_belt'], cannotReplace: ['pronation_cable'], technique: 'Сгибание кисти с направлением к мизинцу (Kuznetsov РН).', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'РН to_little.' },
  { id: 'cup_to_thumb', name: 'Cup к большому (РН)', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'intermediate', jointStress: 'med', fatigueCost: 5, targetMuscle: 'Сгибатели кисти', order: 1, substitutionGroup: 'cup_iso', movementPattern: 'cupping' as any, canReplace: ['wrist_curl_belt'], cannotReplace: ['pronation_cable'], technique: 'Сгибание кисти к большому пальцу (РН).', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'РН to_thumb.' },
  { id: 'pron_high_strap', name: 'Пронация high-torque ремнём', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'advanced', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Пронаторы', order: 1, substitutionGroup: 'pronation', movementPattern: 'pronation' as any, canReplace: ['pronation_cable'], cannotReplace: ['supination_cable'], technique: 'Ремень, максимальная ротация, 5×5 heavy.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'High torque pron.' },
  { id: 'sup_high_strap', name: 'Супинация high-torque ремнём', group: 'arms', type: 'isolation', equipment: 'cable', difficulty: 'advanced', jointStress: 'med', fatigueCost: 6, targetMuscle: 'Супинаторы', order: 1, substitutionGroup: 'supination', movementPattern: 'supination' as any, canReplace: ['supination_cable'], cannotReplace: ['pronation_cable'], technique: 'Ремень, наружу, hook.', pauseSeconds: 2, peakContraction: true, stretchPhase: false, comments: 'High torque sup.' },
  { id: 'ulnar_dev_heavy', name: 'Ulnar heavy (гантель)', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Локтевые девиаторы', order: 2, substitutionGroup: 'ulnar_iso', movementPattern: 'ulnar_deviation' as any, canReplace: ['ulnar_dev'], cannotReplace: ['pronation_cable'], technique: 'Тяжёлая гантель, к мизинцу, 6-8 повт.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Ulnar heavy.' },
  { id: 'radial_dev_heavy', name: 'Radial heavy (гантель)', group: 'arms', type: 'isolation', equipment: 'dumbbell', difficulty: 'intermediate', jointStress: 'low', fatigueCost: 4, targetMuscle: 'Лучевые девиаторы', order: 2, substitutionGroup: 'radial_iso', movementPattern: 'radial_deviation' as any, canReplace: ['radial_dev'], cannotReplace: ['pronation_cable'], technique: 'К большому, тяж.', pauseSeconds: 1, peakContraction: true, stretchPhase: false, comments: 'Radial heavy.' },
];

export function getArmExercises(): Exercise[] {
  return ARM_EXERCISES;
}

export function getArmExercisesByGroup(group: string): Exercise[] {
  return ARM_EXERCISES.filter(e => e.group === group);
}

export function getArmExerciseById(id: string): Exercise | undefined {
  return ARM_EXERCISES.find(e => e.id === id);
}

export function validateArmCatalog(): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  for (const ex of ARM_EXERCISES) {
    if (ids.has(ex.id)) errors.push(`duplicate id ${ex.id}`);
    ids.add(ex.id);
    if (!ex.name) errors.push(`${ex.id}: no name`);
    if (!ex.group) errors.push(`${ex.id}: no group`);
    if (!ex.movementPattern) errors.push(`${ex.id}: no movementPattern`);
    if (!ex.substitutionGroup) errors.push(`${ex.id}: no substitutionGroup`);
  }
  return errors;
}
