// ─── Meat, Poultry, Fish, Seafood, Eggs — Supplement for FOOD_DB ───
import { FoodItem } from './nutrition-database';

export const SUPPLEMENT_MEAT: FoodItem[] = [
  // ═══════════════════════════════════════════════════════════════════
  // BEEF (25)
  // ═══════════════════════════════════════════════════════════════════
  {id:"beef_sirloin",name:"Говядина сирлойн (постная)",category:"protein",kcal:176,protein:26,fat:7.6,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Постный отруб говядины, высокое содержание белка, низкая жирность",micros:{Ca:18,Fe:2.6,Mg:24,Zn:4.6,K:335}},
  {id:"beef_ribeye_fresh",name:"Говядина рибай (стейк)",category:"protein",kcal:271,protein:24,fat:19,carbs:0,fiber:0,gi:0,servingSize:"250 г",tier:"max",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Мраморный стейк с высоким содержанием жира, сочный и насыщенный вкус",micros:{Ca:12,Fe:2.1,Mg:22,Zn:5.2,K:290}},
  {id:"beef_tenderloin_fresh",name:"Говядина филе-миньон (вырезка)",category:"protein",kcal:188,protein:26,fat:8.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Самый нежный отруб говядины, минимальное содержание соединительной ткани",micros:{Ca:14,Fe:3.0,Mg:23,Zn:4.2,K:310}},
  {id:"beef_chuck_raw",name:"Говядина лопатка (чак)",category:"protein",kcal:215,protein:23,fat:13,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Лопаточная часть с умеренным содержанием жира, подходит для тушения и фарша",micros:{Ca:16,Fe:2.8,Mg:20,Zn:5.6,K:295}},
  {id:"beef_brisket_fresh",name:"Говядина грудинка (брискет)",category:"protein",kcal:274,protein:21,fat:21,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Жирная часть грудины, идеальна для длительного тушения и копчения",micros:{Ca:11,Fe:2.4,Mg:19,Zn:4.8,K:270}},
  {id:"beef_flank",name:"Говядина фланк (пашина)",category:"protein",kcal:192,protein:25,fat:9.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Тонкий отруб из пашины, постный с выраженным мясным вкусом",micros:{Ca:15,Fe:3.2,Mg:22,Zn:4.4,K:305}},
  {id:"beef_skirt",name:"Говядина скёрт (диафрагма)",category:"protein",kcal:198,protein:25,fat:10,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Отруб из диафрагмы, насыщенный мясной вкус, популярен для фахоитас",micros:{Ca:13,Fe:3.4,Mg:21,Zn:4.7,K:290}},
  {id:"beef_shank_raw",name:"Говядина голяшка (шэнк)",category:"protein",kcal:199,protein:24,fat:11,carbs:0,fiber:0,gi:0,servingSize:"250 г",tier:"basic",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Мозговая кость с мясом, богата коллагеном и желатином",micros:{Ca:20,Fe:2.5,Mg:18,Zn:4.1,K:260}},
  {id:"beef_oxtail",name:"Говяжий хвост (окстейл)",category:"protein",kcal:255,protein:22,fat:18,carbs:0,fiber:0,gi:0,servingSize:"250 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Хвостовая часть с костным мозгом, богата коллагеном для суставов",micros:{Ca:25,Fe:2.3,Mg:17,Zn:3.9,K:245}},
  {id:"beef_tongue",name:"Говяжий язык",category:"protein",kcal:260,protein:19,fat:20,carbs:0.3,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Субпродукт с нежной текстурой, богат цинком и витамином B12",micros:{Ca:12,Fe:3.1,Mg:18,Zn:4.9,K:280}},
  {id:"beef_liver",name:"Говяжья печень",category:"protein",kcal:135,protein:20,fat:3.6,carbs:5.1,fiber:0,gi:0,servingSize:"150 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"morning",description:"Суперпродукт с высоким содержанием витамина A, B12, железа и меди",micros:{Ca:6,Fe:6.2,Mg:21,Zn:4.0,K:320}},
  {id:"beef_heart",name:"Говяжье сердце",category:"protein",kcal:112,protein:17,fat:4.3,carbs:0.1,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Постный субпродукт с высоким содержанием CoQ10 и железа",micros:{Ca:7,Fe:4.5,Mg:22,Zn:2.8,K:310}},
  {id:"beef_kidney",name:"Говяжьи почки",category:"protein",kcal:99,protein:17,fat:3.1,carbs:0.3,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Субпродукт с низкой калорийностью, богат селеном и витамином B12",micros:{Ca:10,Fe:5.1,Mg:18,Zn:2.6,K:250}},
  {id:"beef_tripe_raw",name:"Говяжий рубец (требуха)",category:"protein",kcal:85,protein:12,fat:3.7,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Низкокалорийный субпродукт с высоким содержанием коллагена",micros:{Ca:15,Fe:1.1,Mg:14,Zn:1.9,K:185}},
  {id:"beef_marrow",name:"Говяжий костный мозг",category:"protein",kcal:785,protein:12,fat:83,carbs:0,fiber:0,gi:0,servingSize:"100 г",tier:"max",bestFor:["bulk"],timing:"any",description:"Высокожировой продукт с костным мозгом, богат коллагеном и витаминами",micros:{Ca:8,Fe:2.2,Mg:10,Zn:1.1,K:150}},
  {id:"beef_ground_5",name:"Говяжий фарш 5% жирности",category:"protein",kcal:133,protein:24,fat:4.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Постный говяжий фарш, максимальное содержание белка при минимуме жира",micros:{Ca:12,Fe:2.5,Mg:20,Zn:4.1,K:310}},
  {id:"beef_ground_10",name:"Говяжий фарш 10% жирности",category:"protein",kcal:184,protein:22,fat:10,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","cutting"],timing:"any",description:"Классический говяжий фарш, баланс вкуса и питательности",micros:{Ca:14,Fe:2.4,Mg:19,Zn:4.0,K:300}},
  {id:"beef_ground_15",name:"Говяжий фарш 15% жирности",category:"protein",kcal:215,protein:20,fat:15,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Фарш средней жирности, универсальный для кулинарных целей",micros:{Ca:13,Fe:2.3,Mg:18,Zn:3.8,K:295}},
  {id:"beef_ground_20",name:"Говяжий фарш 20% жирности",category:"protein",kcal:246,protein:19,fat:19,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Жирный фарш, сочные блюда для набора массы",micros:{Ca:12,Fe:2.2,Mg:17,Zn:3.6,K:285}},
  {id:"beef_ground_30",name:"Говяжий фарш 30% жирности",category:"protein",kcal:298,protein:16,fat:29,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["bulk"],timing:"any",description:"Высокожирный фарш, максимальная сочность и калорийность",micros:{Ca:11,Fe:2.1,Mg:16,Zn:3.4,K:270}},
  {id:"beef_roast",name:"Говядина ростбиф (запечённая)",category:"protein",kcal:189,protein:25,fat:9,carbs:0.1,fiber:0,gi:0,servingSize:"150 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Запечённая говядина с пряностями, классическое холодное блюдо",micros:{Ca:16,Fe:2.8,Mg:22,Zn:5.0,K:315}},
  {id:"beef_corned",name:"Говядина солонина (корнбиф)",category:"protein",kcal:224,protein:22,fat:15,carbs:0.3,fiber:0,gi:0,servingSize:"150 г",tier:"basic",bestFor:["mass","maintenance"],timing:"any",description:"Солёная говядина, традиционный консервированный продукт",micros:{Ca:17,Fe:2.9,Mg:16,Zn:4.3,K:210}},
  {id:"beef_jerky",name:"Говядина вяленая (джерки)",category:"protein",kcal:310,protein:33,fat:7,carbs:11,fiber:0,gi:35,servingSize:"50 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Сушёное мясо с пряностями, удобный высокобелковый перекус",micros:{Ca:20,Fe:3.5,Mg:28,Zn:5.5,K:490}},
  {id:"beef_neck",name:"Говядина шея (нэк)",category:"protein",kcal:230,protein:22,fat:15,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Шейная часть с прожилками, отлично подходит для тушения и супов",micros:{Ca:14,Fe:2.6,Mg:19,Zn:4.5,K:285}},
  {id:"beef_thin_flank",name:"Говядина тонкий край (строганов)",category:"protein",kcal:186,protein:25,fat:9,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Постный отруб для бефстроганов, быстрое приготовление",micros:{Ca:15,Fe:2.7,Mg:23,Zn:4.3,K:308}},

  // ═══════════════════════════════════════════════════════════════════
  // PORK (20)
  // ═══════════════════════════════════════════════════════════════════
  {id:"pork_tenderloin_raw",name:"Свиная вырезка (филе)",category:"protein",kcal:143,protein:26,fat:3.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Самый постный отруб свинины, сравним с куриной грудкой по жирности",micros:{Ca:10,Fe:1.3,Mg:24,Zn:2.4,K:345}},
  {id:"pork_chop_lean",name:"Свиная отбивная (корейка постная)",category:"protein",kcal:185,protein:25,fat:8.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Постная корейка, классическая отбивная на кости",micros:{Ca:10,Fe:1.2,Mg:22,Zn:2.5,K:340}},
  {id:"pork_shoulder_steak",name:"Свиная лопатка",category:"protein",kcal:235,protein:22,fat:16,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Лопатка с умеренным содержанием жира, идеальна для маринования и BBQ",micros:{Ca:12,Fe:1.5,Mg:20,Zn:3.0,K:320}},
  {id:"pork_belly_fresh",name:"Свиная грудинка (белли)",category:"protein",kcal:394,protein:17,fat:36,carbs:0,fiber:0,gi:0,servingSize:"150 г",tier:"basic",bestFor:["bulk"],timing:"any",description:"Брюшина с высоким содержанием жира, основа для бекона и тушёной свинины",micros:{Ca:14,Fe:1.4,Mg:16,Zn:2.8,K:230}},
  {id:"pork_ribs_back",name:"Свиные рёбра карбонад (бэк)",category:"protein",kcal:240,protein:21,fat:17,carbs:0,fiber:0,gi:0,servingSize:"250 г",tier:"mid",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Мясные рёбра из спинной части, нежное мясо с косточкой",micros:{Ca:11,Fe:1.3,Mg:21,Zn:2.6,K:300}},
  {id:"pork_ribs_spare",name:"Свиные рёбра спар-рёбра",category:"protein",kcal:278,protein:19,fat:22,carbs:0,fiber:0,gi:0,servingSize:"250 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Плоские рёбра из грудинной части, жирные и сочные",micros:{Ca:12,Fe:1.5,Mg:18,Zn:2.8,K:280}},
  {id:"pork_ham_raw",name:"Свиной окорок (ветчина сырая)",category:"protein",kcal:195,protein:24,fat:10,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","cutting"],timing:"any",description:"Задняя часть свинины, постный отруб для запекания и варки",micros:{Ca:11,Fe:1.4,Mg:21,Zn:2.9,K:345}},
  {id:"pork_bacon",name:"Бекон свиной",category:"protein",kcal:541,protein:12,fat:55,carbs:1.5,fiber:0,gi:0,servingSize:"50 г",tier:"basic",bestFor:["bulk"],timing:"morning",description:"Копчёная грудинка с высоким содержанием жира и хрустящей текстурой",micros:{Ca:11,Fe:1.1,Mg:14,Zn:1.9,K:180}},
  {id:"pork_sausage_brat",name:"Колбаса свиная (братвурст)",category:"protein",kcal:297,protein:15,fat:26,carbs:2,fiber:0,gi:0,servingSize:"150 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Немецкая свиная колбаса для гриля со специями",micros:{Ca:18,Fe:1.8,Mg:16,Zn:2.9,K:260}},
  {id:"pork_sausage_italian",name:"Колбаса свиная итальянская",category:"protein",kcal:308,protein:14,fat:27,carbs:3,fiber:0,gi:0,servingSize:"150 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Итальянская свиная колбаса с фенхелем, сладкая или острая",micros:{Ca:19,Fe:1.9,Mg:15,Zn:2.8,K:255}},
  {id:"pork_liver",name:"Свиная печень",category:"protein",kcal:134,protein:21,fat:4.4,carbs:2.2,fiber:0,gi:0,servingSize:"150 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"morning",description:"Богата витаминами A, B12 и железом, мягкая текстура",micros:{Ca:7,Fe:16.1,Mg:18,Zn:4.6,K:270}},
  {id:"pork_heart_organ",name:"Свиное сердце",category:"protein",kcal:118,protein:17,fat:4.8,carbs:0.4,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Постный субпродукт, богат CoQ10 и железом",micros:{Ca:10,Fe:4.5,Mg:20,Zn:2.5,K:290}},
  {id:"pork_trotters",name:"Свиные ножки",category:"protein",kcal:198,protein:19,fat:13,carbs:0.2,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Богаты коллагеном и желатином, популярны для холодца и студня",micros:{Ca:28,Fe:1.2,Mg:14,Zn:1.8,K:210}},
  {id:"pork_ear",name:"Свиные уши",category:"protein",kcal:210,protein:18,fat:15,carbs:0.5,fiber:0,gi:0,servingSize:"150 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Хрящевой субпродукт с высоким содержанием коллагена, хрустящая текстура",micros:{Ca:20,Fe:1.1,Mg:12,Zn:1.5,K:195}},
  {id:"pork_ground_10",name:"Свиной фарш 10% жирности",category:"protein",kcal:178,protein:22,fat:10,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Постный свиной фарш, подходит для котлет и тефтелей",micros:{Ca:11,Fe:1.3,Mg:19,Zn:2.4,K:320}},
  {id:"pork_ground_20",name:"Свиной фарш 20% жирности",category:"protein",kcal:242,protein:19,fat:20,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Классический свиной фарш для сочных блюд",micros:{Ca:10,Fe:1.2,Mg:17,Zn:2.6,K:300}},
  {id:"pork_ground_30",name:"Свиной фарш 30% жирности",category:"protein",kcal:305,protein:16,fat:30,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["bulk"],timing:"any",description:"Жирный фарш для максимальной сочности и калорийности",micros:{Ca:9,Fe:1.1,Mg:15,Zn:2.3,K:280}},
  {id:"pork_loin",name:"Свиная корейка (цельная)",category:"protein",kcal:210,protein:23,fat:12,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Спинная часть свинины с тонким слоем жира, универсальный отруб",micros:{Ca:11,Fe:1.3,Mg:22,Zn:2.7,K:330}},
  {id:"pork_collar",name:"Свиная шейка (кляр)",category:"protein",kcal:240,protein:21,fat:17,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Шейная часть с мраморными прожилками, сочный отруб для стейков и запекания",micros:{Ca:12,Fe:1.4,Mg:19,Zn:3.1,K:310}},
  {id:"pork_jowl",name:"Свиные щёки (джоул)",category:"protein",kcal:287,protein:16,fat:25,carbs:0,fiber:0,gi:0,servingSize:"150 г",tier:"mid",bestFor:["mass","bulk"],timing:"any",description:"Жирный отруб из щечной области, нежнейшая текстура после долгого приготовления",micros:{Ca:10,Fe:1.5,Mg:14,Zn:2.4,K:225}},

  // ═══════════════════════════════════════════════════════════════════
  // LAMB (10)
  // ═══════════════════════════════════════════════════════════════════
  {id:"lamb_leg_roast",name:"Баранина нога (задняя)",category:"protein",kcal:218,protein:23,fat:13,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Задняя нога ягнёнка, классический воскресный ростбиф с пряностями",micros:{Ca:14,Fe:2.1,Mg:24,Zn:4.5,K:310}},
  {id:"lamb_chop_loin",name:"Баранина корейка (лэмб-чопс)",category:"protein",kcal:245,protein:22,fat:17,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","maintenance","bulk"],timing:"dinner",description:"Нежные отбивные на косточке, премиальный отруб с насыщенным вкусом",micros:{Ca:13,Fe:2.0,Mg:22,Zn:4.8,K:305}},
  {id:"lamb_shoulder",name:"Баранина лопатка",category:"protein",kcal:260,protein:21,fat:19,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Лопатка с прожилками, лучший отруб для долгого тушения и барбекю",micros:{Ca:15,Fe:2.2,Mg:21,Zn:4.2,K:290}},
  {id:"lamb_rack",name:"Баранина раклет (каре)",category:"protein",kcal:272,protein:20,fat:21,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","bulk"],timing:"dinner",description:"Премиальный отруб из корейки, подаётся целиком или нарезанным на чопсы",micros:{Ca:12,Fe:1.9,Mg:20,Zn:4.6,K:295}},
  {id:"lamb_ground",name:"Баранина фарш",category:"protein",kcal:240,protein:18,fat:18,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Фарш из баранины с характерным вкусом, основа для кебабов и люля",micros:{Ca:14,Fe:2.0,Mg:19,Zn:3.9,K:285}},
  {id:"lamb_liver",name:"Баранья печень",category:"protein",kcal:139,protein:21,fat:5,carbs:2.5,fiber:0,gi:0,servingSize:"150 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"morning",description:"Нежная печень ягнёнка, богата железом и витамином A",micros:{Ca:7,Fe:9.5,Mg:22,Zn:4.0,K:270}},
  {id:"lamb_kidney_organ",name:"Бараньи почки",category:"protein",kcal:97,protein:17,fat:2.6,carbs:0.5,fiber:0,gi:0,servingSize:"150 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Постные субпродукты с низкой калорийностью, богаты селеном",micros:{Ca:11,Fe:5.8,Mg:17,Zn:2.3,K:240}},
  {id:"lamb_shank",name:"Баранья голяшка",category:"protein",kcal:217,protein:23,fat:13,carbs:0,fiber:0,gi:0,servingSize:"250 г",tier:"mid",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Голень с желатином и коллагеном, идеальна для медленного приготовления",micros:{Ca:17,Fe:2.0,Mg:21,Zn:4.3,K:285}},
  {id:"lamb_breast",name:"Баранья грудинка",category:"protein",kcal:288,protein:20,fat:23,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["bulk"],timing:"any",description:"Жирная часть грудины с ярким вкусом, для BBQ и запекания",micros:{Ca:13,Fe:1.9,Mg:18,Zn:3.5,K:260}},
  {id:"lamb_neck",name:"Баранья шея",category:"protein",kcal:235,protein:22,fat:16,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","bulk"],timing:"any",description:"Шейная часть с желатином и костями, отлично для супов и рагу",micros:{Ca:16,Fe:2.1,Mg:20,Zn:4.1,K:275}},

  // ═══════════════════════════════════════════════════════════════════
  // GAME (5)
  // ═══════════════════════════════════════════════════════════════════
  {id:"game_venison_loin",name:"Оленина вырезка",category:"protein",kcal:150,protein:30,fat:3.3,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Диетическое мясо оленя, очень высокое содержание белка при низкой жирности",micros:{Ca:12,Fe:4.2,Mg:25,Zn:3.8,K:350}},
  {id:"game_rabbit_loin",name:"Кролик филе (корейка)",category:"protein",kcal:155,protein:28,fat:4.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Нежнейшее диетическое мясо с высоким содержанием белка и низким жиром",micros:{Ca:16,Fe:2.3,Mg:22,Zn:2.1,K:320}},
  {id:"game_bison_steak",name:"Бизон стейк",category:"protein",kcal:156,protein:28,fat:4.2,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Постный стейк из мяса бизона, насыщенный вкус и высокое содержание белка",micros:{Ca:12,Fe:3.8,Mg:24,Zn:4.5,K:330}},
  {id:"game_elk_steak",name:"Лось стейк (вырезка)",category:"protein",kcal:147,protein:29,fat:3.1,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Мясо лося с минимальным содержанием жира и высоким содержанием железа",micros:{Ca:10,Fe:4.5,Mg:23,Zn:3.6,K:340}},
  {id:"game_wild_boar_loin",name:"Кабанина вырезка",category:"protein",kcal:160,protein:27,fat:4.8,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Мясо дикого кабана с характерным вкусом, плотнее свинины и постнее",micros:{Ca:11,Fe:2.4,Mg:21,Zn:3.2,K:325}},

  // ═══════════════════════════════════════════════════════════════════
  // POULTRY (15)
  // ═══════════════════════════════════════════════════════════════════
  {id:"poultry_duck_breast",name:"Утиная грудка (магре)",category:"protein",kcal:200,protein:22,fat:11,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Утиная грудка с хрустящей кожицей, богатый вкус и умеренная жирность",micros:{Ca:9,Fe:2.5,Mg:20,Zn:2.2,K:300}},
  {id:"poultry_duck_leg",name:"Утиная ножка (конфи)",category:"protein",kcal:210,protein:20,fat:14,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Утиная ножка с нежным тёмным мясом, богата железом и цинком",micros:{Ca:10,Fe:2.8,Mg:18,Zn:2.5,K:285}},
  {id:"poultry_goose_breast",name:"Гусиная грудка",category:"protein",kcal:210,protein:24,fat:12,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Плотная грудка гуся с высоким содержанием белка и тёмным мясом",micros:{Ca:11,Fe:3.1,Mg:22,Zn:2.4,K:320}},
  {id:"poultry_quail_whole",name:"Перепелка целиком",category:"protein",kcal:160,protein:24,fat:6.5,carbs:0,fiber:0,gi:0,servingSize:"150 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Мелкая дичь с нежным мясом, высокая концентрация питательных веществ",micros:{Ca:12,Fe:3.5,Mg:23,Zn:2.8,K:290}},
  {id:"poultry_pheasant_breast",name:"Фазан грудка",category:"protein",kcal:175,protein:26,fat:7,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Постная грудка фазана с деликатным вкусом дичи",micros:{Ca:10,Fe:1.8,Mg:21,Zn:1.9,K:310}},
  {id:"poultry_turkey_breast",name:"Индейка грудка (филе)",category:"protein",kcal:135,protein:30,fat:1.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Самая постная часть индейки, рекордсмен по содержанию белка на 100г",micros:{Ca:14,Fe:1.4,Mg:25,Zn:1.7,K:350}},
  {id:"poultry_turkey_thigh",name:"Индейка бедро (филе)",category:"protein",kcal:165,protein:25,fat:6.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","cutting"],timing:"any",description:"Тёмное мясо индейки, сочнее грудки с более насыщенным вкусом",micros:{Ca:12,Fe:2.1,Mg:22,Zn:2.6,K:320}},
  {id:"poultry_turkey_drumstick",name:"Индейка голень",category:"protein",kcal:170,protein:24,fat:7.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Голень индейки с тёмным мясом, сочная и ароматная",micros:{Ca:11,Fe:2.0,Mg:21,Zn:2.8,K:310}},
  {id:"poultry_turkey_wing",name:"Индейка крыло",category:"protein",kcal:190,protein:22,fat:11,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Крыло индейки с кожицей, сочное мясо с умеренным содержанием жира",micros:{Ca:12,Fe:1.8,Mg:19,Zn:2.3,K:290}},
  {id:"poultry_turkey_ground_lean",name:"Фарш индейки постный (2%)",category:"protein",kcal:135,protein:27,fat:2.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Постный фарш из филе индейки с минимальным содержанием жира",micros:{Ca:13,Fe:1.2,Mg:23,Zn:1.5,K:325}},
  {id:"poultry_turkey_ground_regular",name:"Фарш индейки обычный (15%)",category:"protein",kcal:200,protein:22,fat:12,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Фарш из тёмного мяса индейки, сочные котлеты с умеренной жирностью",micros:{Ca:11,Fe:1.8,Mg:20,Zn:2.2,K:310}},
  {id:"poultry_turkey_bacon",name:"Бекон из индейки",category:"protein",kcal:160,protein:16,fat:10,carbs:1.5,fiber:0,gi:0,servingSize:"50 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"morning",description:"Копчёный бекон из индейки, альтернатива свиному с меньшей жирностью",micros:{Ca:10,Fe:1.5,Mg:15,Zn:1.2,K:240}},
  {id:"poultry_chicken_breast_organic",name:"Куриная грудка органическая",category:"protein",kcal:140,protein:29,fat:2,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Органическое филе куриной грудки без антибиотиков и гормонов",micros:{Ca:12,Fe:1.1,Mg:26,Zn:1.2,K:340}},
  {id:"poultry_chicken_thigh_skinless",name:"Куриное бедро без кожи",category:"protein",kcal:170,protein:24,fat:7.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","cutting"],timing:"any",description:"Тёмное мясо курицы, сочнее грудки с более высоким содержанием железа",micros:{Ca:14,Fe:1.5,Mg:22,Zn:2.1,K:300}},
  {id:"poultry_chicken_drumstick",name:"Куриная голень",category:"protein",kcal:175,protein:23,fat:8.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Классическая голень с сочным тёмным мясом и хрустящей кожицей",micros:{Ca:13,Fe:1.4,Mg:20,Zn:2.3,K:285}},

  // ═══════════════════════════════════════════════════════════════════
  // FISH (20)
  // ═══════════════════════════════════════════════════════════════════
  {id:"fish_salmon_atlantic",name:"Лосось атлантический (сёмга)",category:"protein",kcal:208,protein:20,fat:13,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Жирная рыба с высоким содержанием омега-3 EPA/DHA, фермерский лосось",micros:{Ca:12,Fe:0.8,Mg:27,Zn:0.6,K:380}},
  {id:"fish_salmon_wild",name:"Лосось дикий (кета/чавыча)",category:"protein",kcal:182,protein:22,fat:10,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Дикий тихоокеанский лосось с натуральным омега-3 и астаксантином",micros:{Ca:14,Fe:1.1,Mg:29,Zn:0.7,K:400}},
  {id:"fish_salmon_sockeye",name:"Нерка (красная рыба)",category:"protein",kcal:168,protein:24,fat:7.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Дикая нерка с ярко-красным мясом, рекордное содержание астаксантина",micros:{Ca:13,Fe:1.2,Mg:28,Zn:0.8,K:390}},
  {id:"fish_trout_rainbow",name:"Форель радужная",category:"protein",kcal:148,protein:22,fat:6,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Нежная пресноводная форель с умеренным содержанием жира и омега-3",micros:{Ca:15,Fe:0.9,Mg:26,Zn:0.7,K:370}},
  {id:"fish_trout_lake",name:"Форель озёрная (кумжа)",category:"protein",kcal:155,protein:21,fat:7,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","cutting"],timing:"any",description:"Крупная озёрная форель с плотной текстурой и насыщенным вкусом",micros:{Ca:14,Fe:1.0,Mg:25,Zn:0.6,K:360}},
  {id:"fish_halibut",name:"Палтус",category:"protein",kcal:140,protein:22,fat:5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Камбалообразная рыба с плотным белым мясом, богата селеном и омега-3",micros:{Ca:10,Fe:0.6,Mg:28,Zn:0.5,K:400}},
  {id:"fish_sea_bass",name:"Сибас (морской окунь)",category:"protein",kcal:124,protein:21,fat:4,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Белая морская рыба с нежным вкусом и низкой калорийностью",micros:{Ca:12,Fe:0.8,Mg:24,Zn:0.5,K:370}},
  {id:"fish_red_snapper",name:"Луциан (красный снэппер)",category:"protein",kcal:128,protein:22,fat:4,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Тропическая рыба с плотным белым мясом, популярна в азиатской кухне",micros:{Ca:11,Fe:0.7,Mg:25,Zn:0.5,K:380}},
  {id:"fish_cod_liver",name:"Печень трески (консервы)",category:"protein",kcal:613,protein:4.2,fat:65,carbs:1.3,fiber:0,gi:0,servingSize:"100 г",tier:"max",bestFor:["bulk","maintenance"],timing:"morning",description:"Консервированная печень трески, рекордсмен по содержанию омега-3 и витамина D",micros:{Ca:10,Fe:0.6,Mg:8,Zn:0.5,K:110}},
  {id:"fish_anchovy_oil",name:"Анчоусы в масле",category:"protein",kcal:210,protein:20,fat:14,carbs:0,fiber:0,gi:0,servingSize:"50 г",tier:"mid",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Солёные анчоусы с насыщенным вкусом, богаты омега-3 и кальцием",micros:{Ca:120,Fe:2.5,Mg:14,Zn:0.9,K:180}},
  {id:"fish_eel_fresh",name:"Угорь свежий (унаги)",category:"protein",kcal:184,protein:19,fat:12,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Жирная рыба с плотным мясом, богата витаминами A и B12",micros:{Ca:20,Fe:0.6,Mg:22,Zn:1.5,K:280}},
  {id:"fish_catfish",name:"Сом (филе)",category:"protein",kcal:130,protein:19,fat:5.5,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Пресноводная рыба с нежным белым мясом и умеренной жирностью",micros:{Ca:14,Fe:0.9,Mg:23,Zn:0.6,K:350}},
  {id:"fish_tilapia",name:"Тилапия (филе)",category:"protein",kcal:96,protein:20,fat:1.7,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Постная белая рыба с нейтральным вкусом и низкой калорийностью",micros:{Ca:12,Fe:0.5,Mg:24,Zn:0.4,K:320}},
  {id:"fish_barramundi",name:"Баррамунди",category:"protein",kcal:118,protein:21,fat:3.2,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Австралийская рыба с плотным белым мясом и высоким содержанием омега-3",micros:{Ca:13,Fe:0.6,Mg:26,Zn:0.5,K:340}},
  {id:"fish_perch",name:"Окунь речной (филе)",category:"protein",kcal:96,protein:19,fat:1.9,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Пресноводная рыба с белым упругим мясом, диетический продукт",micros:{Ca:15,Fe:0.8,Mg:24,Zn:0.6,K:330}},
  {id:"fish_pike",name:"Щука (филе)",category:"protein",kcal:92,protein:19,fat:1.6,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Хищная пресноводная рыба с плотным белым мясом и низкой жирностью",micros:{Ca:16,Fe:0.7,Mg:23,Zn:0.5,K:310}},
  {id:"fish_zander",name:"Судак (филе)",category:"protein",kcal:91,protein:19,fat:1.4,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Ценная пресноводная рыба с белым упругим мясом, минимальная жирность",micros:{Ca:14,Fe:0.8,Mg:25,Zn:0.6,K:335}},
  {id:"fish_carp",name:"Карп (филе)",category:"protein",kcal:127,protein:18,fat:5.6,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Пресноводная рыба с умеренным содержанием жира и характерным вкусом",micros:{Ca:15,Fe:0.7,Mg:22,Zn:0.5,K:320}},
  {id:"fish_mackerel",name:"Скумбрия (макрель)",category:"protein",kcal:205,protein:19,fat:14,carbs:0,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","maintenance","bulk"],timing:"any",description:"Жирная морская рыба, богата омега-3 и коэнзимом Q10",micros:{Ca:15,Fe:1.6,Mg:26,Zn:0.8,K:370}},
  {id:"fish_sardine_oil",name:"Сардины в масле (консервы)",category:"protein",kcal:208,protein:25,fat:11,carbs:0,fiber:0,gi:0,servingSize:"100 г",tier:"max",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Консервированные сардины с высоким содержанием кальция и омега-3",micros:{Ca:380,Fe:2.9,Mg:18,Zn:1.5,K:340}},

  // ═══════════════════════════════════════════════════════════════════
  // SEAFOOD (15)
  // ═══════════════════════════════════════════════════════════════════
  {id:"seafood_shrimp_tiger",name:"Креветки тигровые",category:"protein",kcal:94,protein:19,fat:1.2,carbs:0.5,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Крупные тигровые креветки с плотным мясом, низкая калорийность",micros:{Ca:70,Fe:0.5,Mg:30,Zn:1.2,K:185}},
  {id:"seafood_shrimp_king",name:"Креветки королевские",category:"protein",kcal:91,protein:18,fat:1.1,carbs:0.6,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Крупные королевские креветки с сочным мясом и низкой калорийностью",micros:{Ca:65,Fe:0.5,Mg:28,Zn:1.1,K:180}},
  {id:"seafood_shrimp_salad",name:"Креветки салатные (мелкие)",category:"protein",kcal:85,protein:17,fat:0.8,carbs:0.4,fiber:0,gi:0,servingSize:"150 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Мелкие северные креветки для салатов, варёно-мороженые",micros:{Ca:60,Fe:0.4,Mg:26,Zn:1.0,K:170}},
  {id:"seafood_lobster",name:"Омар (лобстер)",category:"protein",kcal:89,protein:19,fat:0.9,carbs:0.5,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"dinner",description:"Премиальный морской деликатес с нежным сладковатым мясом",micros:{Ca:50,Fe:0.3,Mg:30,Zn:2.5,K:280}},
  {id:"seafood_crab_legs",name:"Крабовые ноги (камчатский краб)",category:"protein",kcal:84,protein:18,fat:0.6,carbs:0.2,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Мясо из ног камчатского краба, нежное и сладковатое на вкус",micros:{Ca:55,Fe:0.4,Mg:32,Zn:3.0,K:290}},
  {id:"seafood_crab_meat",name:"Мясо краба (консервы)",category:"protein",kcal:82,protein:17,fat:0.7,carbs:0.3,fiber:0,gi:0,servingSize:"150 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Консервированное крабовое мясо, удобный источник белка и селена",micros:{Ca:50,Fe:0.5,Mg:30,Zn:2.8,K:270}},
  {id:"seafood_scallops",name:"Морские гребешки",category:"protein",kcal:88,protein:17,fat:0.8,carbs:2.4,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Нежные моллюски с белым мясом, богаты витамином B12 и селеном",micros:{Ca:20,Fe:0.4,Mg:25,Zn:1.1,K:240}},
  {id:"seafood_octopus",name:"Осьминог (варёный)",category:"protein",kcal:82,protein:15,fat:1.5,carbs:2.2,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Морской деликатес с плотным мясом и низкой калорийностью",micros:{Ca:40,Fe:5.3,Mg:30,Zn:1.6,K:350}},
  {id:"seafood_squid",name:"Кальмар (филе)",category:"protein",kcal:92,protein:18,fat:1.4,carbs:1.6,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Головоногий моллюск с упругим мясом, богат медью и селеном",micros:{Ca:35,Fe:0.7,Mg:24,Zn:1.4,K:230}},
  {id:"seafood_clams",name:"Моллюски (клэмс)",category:"protein",kcal:74,protein:13,fat:0.7,carbs:2.6,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Двустворчатые моллюски с высоким содержанием железа и витамина B12",micros:{Ca:55,Fe:14,Mg:22,Zn:1.4,K:250}},
  {id:"seafood_mussels",name:"Мидии (варёные)",category:"protein",kcal:86,protein:12,fat:2.2,carbs:3.7,fiber:0,gi:0,servingSize:"200 г",tier:"mid",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Морские двустворчатые моллюски, богаты витамином B12 и марганцем",micros:{Ca:40,Fe:3.5,Mg:28,Zn:1.7,K:260}},
  {id:"seafood_oysters",name:"Устрицы (сырые)",category:"protein",kcal:68,protein:9,fat:2.5,carbs:3.3,fiber:0,gi:0,servingSize:"200 г",tier:"max",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Морской деликатес с высоким содержанием цинка, рекордсмен по Zn",micros:{Ca:60,Fe:5.4,Mg:22,Zn:50,K:220}},
  {id:"seafood_crawfish",name:"Раки (варёные)",category:"protein",kcal:87,protein:17,fat:1.5,carbs:0.6,fiber:0,gi:0,servingSize:"200 г",tier:"basic",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Пресноводные ракообразные с нежным мясом, популярная закуска к пиву",micros:{Ca:40,Fe:1.3,Mg:22,Zn:1.5,K:230}},
  {id:"seafood_abalone",name:"Морское ухо (алиот)",category:"protein",kcal:105,protein:17,fat:1.3,carbs:6,fiber:0,gi:0,servingSize:"150 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Деликатесный брюхоногий моллюск с плотным мясом, богат йодом и селеном",micros:{Ca:30,Fe:3.2,Mg:28,Zn:1.1,K:250}},
  {id:"seafood_sea_urchin",name:"Морской ёж (икра)",category:"protein",kcal:125,protein:13,fat:5.6,carbs:2.9,fiber:0,gi:0,servingSize:"100 г",tier:"max",bestFor:["mass","maintenance"],timing:"any",description:"Деликатесная икра морского ежа с насыщенным вкусом умами",micros:{Ca:40,Fe:1.5,Mg:30,Zn:2.1,K:210}},

  // ═══════════════════════════════════════════════════════════════════
  // EGGS (10)
  // ═══════════════════════════════════════════════════════════════════
  {id:"egg_quail",name:"Яйца перепелиные",category:"protein",kcal:158,protein:13,fat:11,carbs:0.4,fiber:0,gi:0,servingSize:"60 г (5 шт)",tier:"max",bestFor:["mass","cutting","maintenance"],timing:"any",description:"Мелкие яйца с высоким содержанием витаминов группы B и железа",micros:{Ca:64,Fe:3.5,Mg:13,Zn:1.5,K:140}},
  {id:"egg_duck",name:"Яйца утиные",category:"protein",kcal:185,protein:13,fat:14,carbs:1.5,fiber:0,gi:0,servingSize:"150 г (2 шт)",tier:"mid",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Крупные яйца с насыщенным вкусом и более высокой жирностью",micros:{Ca:60,Fe:3.6,Mg:12,Zn:1.4,K:150}},
  {id:"egg_goose",name:"Яйца гусиные",category:"protein",kcal:200,protein:14,fat:15,carbs:1.4,fiber:0,gi:0,servingSize:"200 г (1 шт)",tier:"mid",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Очень крупные яйца с плотным желтком, богаты витамином D",micros:{Ca:70,Fe:3.1,Mg:14,Zn:1.3,K:160}},
  {id:"egg_chicken_organic",name:"Яйца куриные органические (С0)",category:"protein",kcal:155,protein:13,fat:11,carbs:1.1,fiber:0,gi:0,servingSize:"120 г (2 шт)",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Органические яйца кур свободного выгула, без антибиотиков",micros:{Ca:55,Fe:1.8,Mg:12,Zn:1.3,K:145}},
  {id:"egg_chicken_pasture",name:"Яйца куриные пастбищные",category:"protein",kcal:155,protein:13,fat:11,carbs:1.1,fiber:0,gi:0,servingSize:"120 г (2 шт)",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Яйца кур на пастбищном содержании, улучшенный жирнокислотный профиль",micros:{Ca:55,Fe:1.8,Mg:12,Zn:1.3,K:145}},
  {id:"egg_chicken_omega3",name:"Яйца куриные с омега-3",category:"protein",kcal:155,protein:13,fat:11,carbs:1.1,fiber:0,gi:0,servingSize:"120 г (2 шт)",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Обогащённые яйца с повышенным содержанием омега-3 жирных кислот",micros:{Ca:55,Fe:1.8,Mg:12,Zn:1.3,K:145}},
  {id:"egg_yolk",name:"Яичный желток (куриный)",category:"protein",kcal:322,protein:16,fat:27,carbs:3.6,fiber:0,gi:0,servingSize:"50 г (3 шт)",tier:"mid",bestFor:["mass","bulk"],timing:"morning",description:"Концентрированный источник жиров, холина, витаминов A, D, E и лецитина",micros:{Ca:130,Fe:2.7,Mg:8,Zn:2.0,K:110}},
  {id:"egg_white_liquid",name:"Яичный белок жидкий (пастеризованный)",category:"protein",kcal:42,protein:10,fat:0,carbs:0.4,fiber:0,gi:0,servingSize:"200 мл",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Пастеризованный жидкий яичный белок, удобно для омлетов и коктейлей",micros:{Ca:7,Fe:0.1,Mg:9,Zn:0.1,K:150}},
  {id:"egg_white_powder",name:"Яичный белок сухой (порошок)",category:"protein",kcal:375,protein:82,fat:0.5,carbs:4.5,fiber:0,gi:0,servingSize:"30 г",tier:"max",bestFor:["mass","cutting","maintenance","recomp"],timing:"any",description:"Концентрированный яичный белок для протеиновых коктейлей и выпечки",micros:{Ca:60,Fe:0.5,Mg:45,Zn:0.2,K:680}},
  {id:"egg_whole_powder",name:"Яичный порошок (меланж сухой)",category:"protein",kcal:530,protein:48,fat:37,carbs:4.1,fiber:0,gi:0,servingSize:"30 г",tier:"mid",bestFor:["mass","bulk","maintenance"],timing:"any",description:"Сушёная яичная смесь с длительным сроком хранения, универсальный ингредиент",micros:{Ca:190,Fe:4.5,Mg:25,Zn:2.8,K:510}},

  // ─── VERIFICATION ───
];
