import { PharmaSubstance } from './types';

export const PHARMA_DB: Record<string, PharmaSubstance> = {
  // === ТЕСТОСТЕРОН ===
  test_prop: { id:'test_prop', name:'Тестостерон пропионат', class:'testosterone', esters:['propionate'], pk:{ka:0.48,k10:0.05,k12:0.02,k21:0.015,Vd:35,bioavailability:1,halfLifeHours:48}, pd:{AR_affinity:1,aromatization:1,five_alpha_reduction:0.5,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.3,hct_impact:4,neuro_toxicity:0.1}, ec50:400,n_hill:2.5,maxEffect:1, targetSystems:['cardio','endocrine','reproductive','hematologic','musculoskeletal','prostate','skin'], targetMechanisms:['AR_AGONISM','mTOR_UP','PROTEIN_SYNTHESIS','ERYTHROPOIESIS'], linkedRisks:[{system:'cardio',direction:'up',strength:0.4},{system:'hematologic',direction:'up',strength:0.6},{system:'reproductive',direction:'down',strength:0.8},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'high',cnsLoad:'low'} },
  test_enan: { id:'test_enan', name:'Тестостерон энантат', class:'testosterone', esters:['enanthate'], pk:{ka:0.024,k10:0.05,k12:0.02,k21:0.015,Vd:35,bioavailability:1,halfLifeHours:336}, pd:{AR_affinity:1,aromatization:1,five_alpha_reduction:0.5,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.3,hct_impact:4,neuro_toxicity:0.1}, ec50:400,n_hill:2.5,maxEffect:1, targetSystems:['cardio','endocrine','reproductive','hematologic','musculoskeletal','prostate','skin'], targetMechanisms:['AR_AGONISM','mTOR_UP','PROTEIN_SYNTHESIS','ERYTHROPOIESIS'], linkedRisks:[{system:'cardio',direction:'up',strength:0.4},{system:'hematologic',direction:'up',strength:0.6},{system:'reproductive',direction:'down',strength:0.8},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'high',cnsLoad:'low'} },
  test_cyp:  { id:'test_cyp', name:'Тестостерон ципионат', class:'testosterone', esters:['cypionate'], pk:{ka:0.02,k10:0.05,k12:0.02,k21:0.015,Vd:35,bioavailability:1,halfLifeHours:384}, pd:{AR_affinity:1,aromatization:1,five_alpha_reduction:0.5,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.3,hct_impact:4,neuro_toxicity:0.1}, ec50:400,n_hill:2.5,maxEffect:1, targetSystems:['cardio','endocrine','reproductive','hematologic','musculoskeletal','prostate','skin'], targetMechanisms:['AR_AGONISM','mTOR_UP','PROTEIN_SYNTHESIS','ERYTHROPOIESIS'], linkedRisks:[{system:'cardio',direction:'up',strength:0.4},{system:'hematologic',direction:'up',strength:0.6},{system:'reproductive',direction:'down',strength:0.8},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'high',cnsLoad:'low'} },
  test_undec:{ id:'test_undec', name:'Тестостерон ундеканоат', class:'testosterone', esters:['undecanoate'], pk:{ka:0.008,k10:0.05,k12:0.02,k21:0.015,Vd:35,bioavailability:1,halfLifeHours:1200}, pd:{AR_affinity:1,aromatization:1,five_alpha_reduction:0.5,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.3,hct_impact:4,neuro_toxicity:0.1}, ec50:400,n_hill:2.5,maxEffect:1, targetSystems:['cardio','endocrine','reproductive','hematologic','musculoskeletal','prostate','skin'], targetMechanisms:['AR_AGONISM','mTOR_UP','PROTEIN_SYNTHESIS','ERYTHROPOIESIS'], linkedRisks:[{system:'cardio',direction:'up',strength:0.4},{system:'hematologic',direction:'up',strength:0.6},{system:'reproductive',direction:'down',strength:0.8},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'high',cnsLoad:'low'} },

  // === ТРЕНБОЛОН ===
  tren_acet: { id:'tren_acet', name:'Тренболон ацетат', class:'trenbolone', esters:['acetate'], pk:{ka:0.35,k10:0.04,k12:0.025,k21:0.018,Vd:40,bioavailability:1,halfLifeHours:72}, pd:{AR_affinity:1.8,aromatization:0,five_alpha_reduction:0.1,progestogenic:0.3,hepatotoxicity:1.5,lipid_impact:-0.5,hct_impact:5,neuro_toxicity:0.6}, ec50:250,n_hill:2.2,maxEffect:1, targetSystems:['cardio','hepatic','neuro','neuro_toxicity','endocrine','reproductive','hematologic'], targetMechanisms:['AR_AGONISM','PR_AGONISM','GR_ANTAGONISM','DOPAMINE_MODULATION'], linkedRisks:[{system:'neuro_toxicity',direction:'up',strength:0.9},{system:'hepatic',direction:'up',strength:0.7},{system:'cardio',direction:'up',strength:0.6},{system:'endocrine',direction:'down',strength:0.9}], cvProfile:{bloodPressure:'up',heartRate:'up',vascularTone:'constrict',thrombosisRisk:'high',cnsLoad:'high'} },
  tren_enan: { id:'tren_enan', name:'Тренболон энантат', class:'trenbolone', esters:['enanthate'], pk:{ka:0.022,k10:0.04,k12:0.025,k21:0.018,Vd:40,bioavailability:1,halfLifeHours:240}, pd:{AR_affinity:1.8,aromatization:0,five_alpha_reduction:0.1,progestogenic:0.3,hepatotoxicity:1.5,lipid_impact:-0.5,hct_impact:5,neuro_toxicity:0.6}, ec50:250,n_hill:2.2,maxEffect:1, targetSystems:['cardio','hepatic','neuro','neuro_toxicity','endocrine','reproductive','hematologic'], targetMechanisms:['AR_AGONISM','PR_AGONISM','GR_ANTAGONISM','DOPAMINE_MODULATION'], linkedRisks:[{system:'neuro_toxicity',direction:'up',strength:0.9},{system:'hepatic',direction:'up',strength:0.7},{system:'cardio',direction:'up',strength:0.6},{system:'endocrine',direction:'down',strength:0.9}], cvProfile:{bloodPressure:'up',heartRate:'up',vascularTone:'constrict',thrombosisRisk:'high',cnsLoad:'high'} },
  tren_hex:  { id:'tren_hex', name:'Тренболон гексагидробензилкарбонат', class:'trenbolone', esters:['hexahydrobenzylcarbonate'], pk:{ka:0.015,k10:0.04,k12:0.025,k21:0.018,Vd:40,bioavailability:1,halfLifeHours:336}, pd:{AR_affinity:1.8,aromatization:0,five_alpha_reduction:0.1,progestogenic:0.3,hepatotoxicity:1.5,lipid_impact:-0.5,hct_impact:5,neuro_toxicity:0.6}, ec50:250,n_hill:2.2,maxEffect:1, targetSystems:['cardio','hepatic','neuro','neuro_toxicity','endocrine','reproductive','hematologic'], targetMechanisms:['AR_AGONISM','PR_AGONISM','GR_ANTAGONISM','DOPAMINE_MODULATION'], linkedRisks:[{system:'neuro_toxicity',direction:'up',strength:0.9},{system:'hepatic',direction:'up',strength:0.7},{system:'cardio',direction:'up',strength:0.6},{system:'endocrine',direction:'down',strength:0.9}], cvProfile:{bloodPressure:'up',heartRate:'up',vascularTone:'constrict',thrombosisRisk:'high',cnsLoad:'high'} },

  // === НАНДРОЛОН ===
  npp:       { id:'npp', name:'Нандролон фенилпропионат', class:'nandrolone', esters:['phenylpropionate'], pk:{ka:0.28,k10:0.03,k12:0.02,k21:0.016,Vd:45,bioavailability:1,halfLifeHours:96}, pd:{AR_affinity:0.9,aromatization:0.2,five_alpha_reduction:0.15,progestogenic:0.4,hepatotoxicity:0,lipid_impact:-0.4,hct_impact:3,neuro_toxicity:0.15}, ec50:300,n_hill:2.4,maxEffect:1, targetSystems:['cardio','endocrine','reproductive','hematologic','musculoskeletal','prostate'], targetMechanisms:['AR_AGONISM','PR_AGONISM','COLLAGEN_SYNTHESIS'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.6},{system:'reproductive',direction:'down',strength:0.5},{system:'hematologic',direction:'up',strength:0.4}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'medium',cnsLoad:'low'} },
  deca:      { id:'deca', name:'Нандролон деканоат', class:'nandrolone', esters:['decanoate'], pk:{ka:0.018,k10:0.03,k12:0.02,k21:0.016,Vd:45,bioavailability:1,halfLifeHours:336}, pd:{AR_affinity:0.9,aromatization:0.2,five_alpha_reduction:0.15,progestogenic:0.4,hepatotoxicity:0,lipid_impact:-0.4,hct_impact:3,neuro_toxicity:0.15}, ec50:300,n_hill:2.4,maxEffect:1, targetSystems:['cardio','endocrine','reproductive','hematologic','musculoskeletal','prostate'], targetMechanisms:['AR_AGONISM','PR_AGONISM','COLLAGEN_SYNTHESIS'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.6},{system:'reproductive',direction:'down',strength:0.5},{system:'hematologic',direction:'up',strength:0.4}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'medium',cnsLoad:'low'} },

  // === БОЛДЕНОН / ПРИМОБОЛАН ===
  bold_undec:{ id:'bold_undec', name:'Болденон ундециленат', class:'boldenone', esters:['undecylenate'], pk:{ka:0.016,k10:0.035,k12:0.022,k21:0.017,Vd:42,bioavailability:1,halfLifeHours:336}, pd:{AR_affinity:0.85,aromatization:0.5,five_alpha_reduction:0.2,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.35,hct_impact:4.5,neuro_toxicity:0.1}, ec50:350,n_hill:2.3,maxEffect:1, targetSystems:['cardio','endocrine','hematologic','musculoskeletal'], targetMechanisms:['AR_AGONISM','ERYTHROPOIESIS'], linkedRisks:[{system:'hematologic',direction:'up',strength:0.7},{system:'cardio',direction:'up',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'dilate',thrombosisRisk:'high',cnsLoad:'low'} },
  prim_enan: { id:'prim_enan', name:'Метенолон энантат (Примоболан)', class:'primobolan', esters:['enanthate'], pk:{ka:0.02,k10:0.03,k12:0.018,k21:0.014,Vd:38,bioavailability:1,halfLifeHours:288}, pd:{AR_affinity:0.75,aromatization:0,five_alpha_reduction:0.1,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.2,hct_impact:2,neuro_toxicity:0.05}, ec50:400,n_hill:2.1,maxEffect:1, targetSystems:['endocrine','musculoskeletal','reproductive'], targetMechanisms:['AR_AGONISM','ANTI_CATABOLIC'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.5},{system:'reproductive',direction:'down',strength:0.4}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },

  // === ОРАЛЬНЫЕ 17-α ===
  methand:   { id:'methand', name:'Метандиенон', class:'oral_17aa', pk:{ka:0.9,k10:0.07,k12:0.035,k21:0.028,Vd:30,bioavailability:0.8,halfLifeHours:5}, pd:{AR_affinity:1.1,aromatization:0.8,five_alpha_reduction:0.2,progestogenic:0,hepatotoxicity:3,lipid_impact:-0.8,hct_impact:3,neuro_toxicity:0.1}, ec50:60,n_hill:2.1,maxEffect:1, targetSystems:['hepatic','cardio','endocrine','reproductive','skin'], targetMechanisms:['AR_AGONISM','CYP3A4_METABOLISM','GLYCOGEN_SYNTHESIS'], linkedRisks:[{system:'hepatic',direction:'up',strength:0.9},{system:'cardio',direction:'up',strength:0.5},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'constrict',thrombosisRisk:'high',cnsLoad:'low'} },
  oxan:      { id:'oxan', name:'Оксандролон', class:'oral_17aa', pk:{ka:0.8,k10:0.06,k12:0.03,k21:0.025,Vd:28,bioavailability:0.95,halfLifeHours:9}, pd:{AR_affinity:1.2,aromatization:0,five_alpha_reduction:0.8,progestogenic:0,hepatotoxicity:2,lipid_impact:-0.7,hct_impact:2,neuro_toxicity:0.05}, ec50:50,n_hill:2.0,maxEffect:1, targetSystems:['hepatic','cardio','endocrine','reproductive','skin'], targetMechanisms:['AR_AGONISM','CYP3A4_METABOLISM','GLYCOGEN_SYNTHESIS'], linkedRisks:[{system:'hepatic',direction:'up',strength:0.9},{system:'cardio',direction:'up',strength:0.5},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'constrict',thrombosisRisk:'high',cnsLoad:'low'} },
  stan:      { id:'stan', name:'Станозолол', class:'oral_17aa', pk:{ka:0.85,k10:0.065,k12:0.032,k21:0.026,Vd:29,bioavailability:0.9,halfLifeHours:9}, pd:{AR_affinity:1.15,aromatization:0,five_alpha_reduction:0.3,progestogenic:0,hepatotoxicity:2.5,lipid_impact:-0.75,hct_impact:2.5,neuro_toxicity:0.08}, ec50:55,n_hill:2.05,maxEffect:1, targetSystems:['hepatic','cardio','endocrine','reproductive','skin'], targetMechanisms:['AR_AGONISM','CYP3A4_METABOLISM','GLYCOGEN_SYNTHESIS'], linkedRisks:[{system:'hepatic',direction:'up',strength:0.9},{system:'cardio',direction:'up',strength:0.5},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'constrict',thrombosisRisk:'high',cnsLoad:'low'} },
  trena:     { id:'trena', name:'Туринабол', class:'oral_17aa', pk:{ka:0.7,k10:0.05,k12:0.025,k21:0.02,Vd:32,bioavailability:0.85,halfLifeHours:16}, pd:{AR_affinity:0.95,aromatization:0.1,five_alpha_reduction:0.15,progestogenic:0,hepatotoxicity:2.5,lipid_impact:-0.65,hct_impact:2.5,neuro_toxicity:0.08}, ec50:70,n_hill:2.0,maxEffect:1, targetSystems:['hepatic','cardio','endocrine','reproductive','skin'], targetMechanisms:['AR_AGONISM','CYP3A4_METABOLISM','GLYCOGEN_SYNTHESIS'], linkedRisks:[{system:'hepatic',direction:'up',strength:0.9},{system:'cardio',direction:'up',strength:0.5},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'constrict',thrombosisRisk:'high',cnsLoad:'low'} },
  halo:      { id:'halo', name:'Хлордегидрометилтестостерон', class:'oral_17aa', pk:{ka:0.75,k10:0.055,k12:0.028,k21:0.022,Vd:31,bioavailability:0.88,halfLifeHours:14}, pd:{AR_affinity:1.05,aromatization:0,five_alpha_reduction:0.25,progestogenic:0,hepatotoxicity:2.8,lipid_impact:-0.72,hct_impact:2.8,neuro_toxicity:0.09}, ec50:65,n_hill:2.02,maxEffect:1, targetSystems:['hepatic','cardio','endocrine','reproductive','skin'], targetMechanisms:['AR_AGONISM','CYP3A4_METABOLISM','GLYCOGEN_SYNTHESIS'], linkedRisks:[{system:'hepatic',direction:'up',strength:0.9},{system:'cardio',direction:'up',strength:0.5},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'constrict',thrombosisRisk:'high',cnsLoad:'low'} },

  // === SARMs ===
  ostarine:  { id:'ostarine', name:'Ostarine MK-2866', class:'sarm', pk:{ka:0.5,k10:0.04,k12:0.02,k21:0.015,Vd:50,bioavailability:0.9,halfLifeHours:24}, pd:{AR_affinity:0.85,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0.5,lipid_impact:-0.2,hct_impact:1,neuro_toxicity:0.05}, ec50:150,n_hill:2.3,maxEffect:0.9, targetSystems:['endocrine','hepatic','musculoskeletal','cardio'], targetMechanisms:['AR_SELECTIVE_AGONISM'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.5},{system:'hepatic',direction:'up',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  lgd:       { id:'lgd', name:'Ligandrol LGD-4033', class:'sarm', pk:{ka:0.45,k10:0.035,k12:0.018,k21:0.014,Vd:55,bioavailability:0.88,halfLifeHours:36}, pd:{AR_affinity:0.9,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0.8,lipid_impact:-0.35,hct_impact:1.5,neuro_toxicity:0.06}, ec50:100,n_hill:2.4,maxEffect:0.95, targetSystems:['endocrine','hepatic','musculoskeletal','cardio'], targetMechanisms:['AR_SELECTIVE_AGONISM'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.5},{system:'hepatic',direction:'up',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  rad140:    { id:'rad140', name:'RAD-140', class:'sarm', pk:{ka:0.48,k10:0.038,k12:0.019,k21:0.015,Vd:52,bioavailability:0.85,halfLifeHours:30}, pd:{AR_affinity:0.92,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0.7,lipid_impact:-0.3,hct_impact:1.2,neuro_toxicity:0.1}, ec50:120,n_hill:2.35,maxEffect:0.93, targetSystems:['endocrine','hepatic','musculoskeletal','cardio'], targetMechanisms:['AR_SELECTIVE_AGONISM'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.5},{system:'hepatic',direction:'up',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  s23:       { id:'s23', name:'S-23', class:'sarm', pk:{ka:0.42,k10:0.042,k12:0.021,k21:0.016,Vd:48,bioavailability:0.82,halfLifeHours:28}, pd:{AR_affinity:0.95,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0.6,lipid_impact:-0.4,hct_impact:1.8,neuro_toxicity:0.08}, ec50:90,n_hill:2.45,maxEffect:0.97, targetSystems:['endocrine','hepatic','musculoskeletal','cardio'], targetMechanisms:['AR_SELECTIVE_AGONISM'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.5},{system:'hepatic',direction:'up',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },

  // === ПЕПТИДЫ ГР ===
  cjc1295:   { id:'cjc1295', name:'CJC-1295 (без DAC)', class:'peptide_ghrh', pk:{ka:0.6,k10:0.08,k12:0.04,k21:0.03,Vd:12,bioavailability:0.85,halfLifeHours:8}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:200,n_hill:1.8,maxEffect:1, targetSystems:['ghigf','endocrine','musculoskeletal'], targetMechanisms:['GHSR_AGONISM','GH_RELEASE','IGF1_UP'], linkedRisks:[{system:'ghigf',direction:'up',strength:0.5}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  ghrp6:     { id:'ghrp6', name:'GHRP-6', class:'peptide_ghrp', pk:{ka:0.7,k10:0.12,k12:0.05,k21:0.035,Vd:10,bioavailability:0.8,halfLifeHours:4}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:150,n_hill:1.9,maxEffect:1, targetSystems:['ghigf','endocrine','neuro'], targetMechanisms:['GHSR_AGONISM','GH_RELEASE'], linkedRisks:[{system:'ghigf',direction:'up',strength:0.4}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  ipamorelin:{ id:'ipamorelin', name:'Ipamorelin', class:'peptide_ghrp', pk:{ka:0.65,k10:0.1,k12:0.045,k21:0.032,Vd:11,bioavailability:0.82,halfLifeHours:5}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:180,n_hill:1.85,maxEffect:1, targetSystems:['ghigf','endocrine','neuro'], targetMechanisms:['GHSR_AGONISM','GH_RELEASE'], linkedRisks:[{system:'ghigf',direction:'up',strength:0.4}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  mk677:     { id:'mk677', name:'Ibutamoren MK-677', class:'peptide_ghrh', pk:{ka:0.3,k10:0.02,k12:0.01,k21:0.008,Vd:150,bioavailability:0.75,halfLifeHours:24}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.1,hct_impact:0,neuro_toxicity:0.02}, ec50:300,n_hill:1.7,maxEffect:1, targetSystems:['ghigf','endocrine','musculoskeletal'], targetMechanisms:['GHSR_AGONISM','GH_RELEASE','IGF1_UP'], linkedRisks:[{system:'ghigf',direction:'up',strength:0.5}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },

  // === ИГФ-1 & МГФ ===
  igf1_lr3:  { id:'igf1_lr3', name:'IGF-1 LR3', class:'igf1', pk:{ka:0.3,k10:0.06,k12:0.03,k21:0.02,Vd:8,bioavailability:0.75,halfLifeHours:20}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0.02}, ec50:100,n_hill:2.0,maxEffect:1, targetSystems:['ghigf','musculoskeletal'], targetMechanisms:['IGF1_AGONISM','PROTEIN_SYNTHESIS'], linkedRisks:[{system:'ghigf',direction:'up',strength:0.7}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  igf1_des:  { id:'igf1_des', name:'IGF-1 DES', class:'igf1', pk:{ka:0.4,k10:0.15,k12:0.06,k21:0.04,Vd:6,bioavailability:0.7,halfLifeHours:30}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0.02}, ec50:80,n_hill:2.1,maxEffect:1, targetSystems:['ghigf','musculoskeletal'], targetMechanisms:['IGF1_AGONISM','PROTEIN_SYNTHESIS'], linkedRisks:[{system:'ghigf',direction:'up',strength:0.7}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  mgf:       { id:'mgf', name:'Механо-Фактор (МГФ)', class:'mgf', pk:{ka:0.5,k10:0.18,k12:0.08,k21:0.05,Vd:5,bioavailability:0.65,halfLifeHours:5}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0.01}, ec50:120,n_hill:1.8,maxEffect:1, targetSystems:['musculoskeletal'], targetMechanisms:['MGF_AGONISM','SATELLITE_CELL_ACTIVATION'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },

  // === ИНСУЛИНЫ ===
  ins_short: { id:'ins_short', name:'Инсулин человеческий (короткий)', class:'insulin', pk:{ka:0.9,k10:0.25,k12:0.1,k21:0.06,Vd:4,bioavailability:0.95,halfLifeHours:1.5}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.1,hct_impact:0,neuro_toxicity:0.05}, ec50:50,n_hill:1.5,maxEffect:1, targetSystems:['metabolic','ins_axis','cardio'], targetMechanisms:['INSULIN_AGONISM','GLUCOSE_UPTAKE'], linkedRisks:[{system:'ins_axis',direction:'up',strength:0.5},{system:'metabolic',direction:'down',strength:0.6}], cvProfile:{bloodPressure:'down',heartRate:'up',vascularTone:'dilate',thrombosisRisk:'low',cnsLoad:'low'} },
  ins_long:  { id:'ins_long', name:'Инсулин гларгин (продлённый)', class:'insulin', pk:{ka:0.15,k10:0.04,k12:0.02,k21:0.015,Vd:4,bioavailability:0.98,halfLifeHours:24}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.1,hct_impact:0,neuro_toxicity:0.05}, ec50:40,n_hill:1.4,maxEffect:1, targetSystems:['metabolic','ins_axis','cardio'], targetMechanisms:['INSULIN_AGONISM','GLUCOSE_UPTAKE'], linkedRisks:[{system:'ins_axis',direction:'up',strength:0.5},{system:'metabolic',direction:'down',strength:0.6}], cvProfile:{bloodPressure:'down',heartRate:'up',vascularTone:'dilate',thrombosisRisk:'low',cnsLoad:'low'} },
  ins_aspart:{ id:'ins_aspart', name:'Инсулин аспарт (НовоРапид)', class:'insulin', pk:{ka:0.85,k10:0.22,k12:0.09,k21:0.055,Vd:4,bioavailability:0.96,halfLifeHours:1.2}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.1,hct_impact:0,neuro_toxicity:0.05}, ec50:45,n_hill:1.45,maxEffect:1, targetSystems:['metabolic','ins_axis','cardio'], targetMechanisms:['INSULIN_AGONISM','GLUCOSE_UPTAKE'], linkedRisks:[{system:'ins_axis',direction:'up',strength:0.5},{system:'metabolic',direction:'down',strength:0.6}], cvProfile:{bloodPressure:'down',heartRate:'up',vascularTone:'dilate',thrombosisRisk:'low',cnsLoad:'low'} },
  ins_detemir:{ id:'ins_detemir', name:'Инсулин детемир (Левемир)', class:'insulin', pk:{ka:0.12,k10:0.035,k12:0.018,k21:0.014,Vd:4,bioavailability:0.97,halfLifeHours:20}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.1,hct_impact:0,neuro_toxicity:0.05}, ec50:38,n_hill:1.38,maxEffect:1, targetSystems:['metabolic','ins_axis','cardio'], targetMechanisms:['INSULIN_AGONISM','GLUCOSE_UPTAKE'], linkedRisks:[{system:'ins_axis',direction:'up',strength:0.5},{system:'metabolic',direction:'down',strength:0.6}], cvProfile:{bloodPressure:'down',heartRate:'up',vascularTone:'dilate',thrombosisRisk:'low',cnsLoad:'low'} },

  // === ПКТ & АНТИЭСТРОГЕНЫ ===
  clomi:     { id:'clomi', name:'Кломифен', class:'pct_serm', pk:{ka:0.6,k10:0.03,k12:0.015,k21:0.012,Vd:250,bioavailability:1,halfLifeHours:120}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.05,hct_impact:-1,neuro_toxicity:0.1}, ec50:300,n_hill:2.0,maxEffect:1, targetSystems:['endocrine','reproductive'], targetMechanisms:['ER_ANTAGONISM','GNRH_UP','LH_UP'], linkedRisks:[{system:'reproductive',direction:'down',strength:0.5},{system:'endocrine',direction:'up',strength:0.5}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'medium',cnsLoad:'low'} },
  tamox:     { id:'tamox', name:'Тамоксифен', class:'pct_serm', pk:{ka:0.55,k10:0.025,k12:0.013,k21:0.01,Vd:280,bioavailability:0.98,halfLifeHours:168}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.04,hct_impact:-0.8,neuro_toxicity:0.08}, ec50:320,n_hill:1.95,maxEffect:1, targetSystems:['endocrine','reproductive'], targetMechanisms:['ER_ANTAGONISM','GNRH_UP','LH_UP'], linkedRisks:[{system:'reproductive',direction:'down',strength:0.5},{system:'endocrine',direction:'up',strength:0.5}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'medium',cnsLoad:'low'} },
  anastro:   { id:'anastro', name:'Анастрозол', class:'pct_aromatase', pk:{ka:0.8,k10:0.06,k12:0.03,k21:0.02,Vd:50,bioavailability:0.85,halfLifeHours:48}, pd:{AR_affinity:0,aromatization:-1,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0.05}, ec50:150,n_hill:2.5,maxEffect:1, targetSystems:['endocrine','reproductive','cardio'], targetMechanisms:['AROMATASE_INHIBITION','E2_SUPPRESSION'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.5},{system:'cardio',direction:'up',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'medium',cnsLoad:'low'} },
  letrozole: { id:'letrozole', name:'Летрозол', class:'pct_aromatase', pk:{ka:0.75,k10:0.055,k12:0.028,k21:0.019,Vd:48,bioavailability:0.88,halfLifeHours:52}, pd:{AR_affinity:0,aromatization:-1.1,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0.06}, ec50:140,n_hill:2.6,maxEffect:1, targetSystems:['endocrine','reproductive','cardio'], targetMechanisms:['AROMATASE_INHIBITION','E2_SUPPRESSION'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.5},{system:'cardio',direction:'up',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'medium',cnsLoad:'low'} },
  caberg:    { id:'caberg', name:'Каберголин', class:'pct_dopamine', pk:{ka:0.4,k10:0.005,k12:0.003,k21:0.002,Vd:60,bioavailability:0.9,halfLifeHours:3120}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0.15}, ec50:20,n_hill:1.8,maxEffect:1, targetSystems:['neuro','endocrine'], targetMechanisms:['D2_AGONISM','PROLACTIN_SUPPRESSION'], linkedRisks:[{system:'neuro',direction:'up',strength:0.2},{system:'endocrine',direction:'down',strength:0.4}], cvProfile:{bloodPressure:'down',heartRate:'neutral',vascularTone:'dilate',thrombosisRisk:'low',cnsLoad:'medium'} },
  bromocriptine:{ id:'bromocriptine', name:'Бромокриптин', class:'pct_dopamine', pk:{ka:0.45,k10:0.008,k12:0.004,k21:0.003,Vd:55,bioavailability:0.85,halfLifeHours:288}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0.12}, ec50:25,n_hill:1.75,maxEffect:1, targetSystems:['neuro','endocrine'], targetMechanisms:['D2_AGONISM','PROLACTIN_SUPPRESSION'], linkedRisks:[{system:'neuro',direction:'up',strength:0.2},{system:'endocrine',direction:'down',strength:0.4}], cvProfile:{bloodPressure:'down',heartRate:'neutral',vascularTone:'dilate',thrombosisRisk:'low',cnsLoad:'medium'} },

  // === ПОДДЕРЖКА ===
  telmi:     { id:'telmi', name:'Телмисартан', class:'support', pk:{ka:0.5,k10:0.04,k12:0.02,k21:0.015,Vd:300,bioavailability:0.9,halfLifeHours:24}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.1,hct_impact:0,neuro_toxicity:0.02}, ec50:250,n_hill:2.2,maxEffect:1, targetSystems:['cardio','renal'], targetMechanisms:['ARB_AGONISM','PPARG_UP'], linkedRisks:[{system:'cardio',direction:'down',strength:0.5},{system:'renal',direction:'down',strength:0.3}], cvProfile:{bloodPressure:'down',heartRate:'neutral',vascularTone:'dilate',thrombosisRisk:'low',cnsLoad:'low'} },
  nebivolol: { id:'nebivolol', name:'Небилет (небиволол)', class:'support', pk:{ka:0.55,k10:0.038,k12:0.019,k21:0.014,Vd:280,bioavailability:0.88,halfLifeHours:22}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.08,hct_impact:0,neuro_toxicity:0.01}, ec50:260,n_hill:2.15,maxEffect:1, targetSystems:['cardio','vessels'], targetMechanisms:['B1_BLOCKADE','NO_UP'], linkedRisks:[{system:'cardio',direction:'down',strength:0.5}], cvProfile:{bloodPressure:'down',heartRate:'down',vascularTone:'dilate',thrombosisRisk:'low',cnsLoad:'low'} },
  nac:       { id:'nac', name:'NAC', class:'support', pk:{ka:0.7,k10:0.08,k12:0.04,k21:0.03,Vd:15,bioavailability:0.6,halfLifeHours:6}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-1,lipid_impact:0.05,hct_impact:0,neuro_toxicity:-0.05}, ec50:800,n_hill:1.8,maxEffect:1, targetSystems:['hepatic','renal','neuro'], targetMechanisms:['GLUTATHIONE_UP','ANTIOXIDANT'], linkedRisks:[{system:'hepatic',direction:'down',strength:0.5},{system:'renal',direction:'down',strength:0.3},{system:'neuro',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  tudca:     { id:'tudca', name:'TUDCA', class:'support', pk:{ka:0.4,k10:0.05,k12:0.025,k21:0.018,Vd:20,bioavailability:0.7,halfLifeHours:8}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-1.2,lipid_impact:0.06,hct_impact:0,neuro_toxicity:-0.03}, ec50:600,n_hill:1.9,maxEffect:1, targetSystems:['hepatic','neuro'], targetMechanisms:['BILE_ACID_MOD','ANTIAPOPTOTIC'], linkedRisks:[{system:'hepatic',direction:'down',strength:0.6},{system:'neuro',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  omega3:    { id:'omega3', name:'Омега-3 (EPA/DHA)', class:'support', pk:{ka:0.3,k10:0.02,k12:0.01,k21:0.008,Vd:40,bioavailability:0.8,halfLifeHours:48}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.3,hct_impact:0,neuro_toxicity:-0.08}, ec50:2000,n_hill:1.6,maxEffect:1, targetSystems:['cardio','neuro','endocrine'], targetMechanisms:['EPA_DHA_UP','ANTIINFLAMMATORY'], linkedRisks:[{system:'cardio',direction:'down',strength:0.4},{system:'neuro',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'down',heartRate:'neutral',vascularTone:'dilate',thrombosisRisk:'low',cnsLoad:'low'} },
  magnesium: { id:'magnesium', name:'Магний бисглицинат', class:'support', pk:{ka:0.6,k10:0.06,k12:0.03,k21:0.022,Vd:25,bioavailability:0.75,halfLifeHours:12}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.02,hct_impact:0,neuro_toxicity:-0.1}, ec50:400,n_hill:1.7,maxEffect:1, targetSystems:['cardio','neuro','musculoskeletal'], targetMechanisms:['NMDA_BLOCK','GABA_MOD'], linkedRisks:[{system:'cardio',direction:'down',strength:0.3},{system:'neuro',direction:'down',strength:0.4}], cvProfile:{bloodPressure:'down',heartRate:'neutral',vascularTone:'dilate',thrombosisRisk:'low',cnsLoad:'low'} },
  berberine: { id:'berberine', name:'Берберин', class:'support', pk:{ka:0.5,k10:0.045,k12:0.022,k21:0.017,Vd:35,bioavailability:0.7,halfLifeHours:16}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.25,hct_impact:0,neuro_toxicity:0}, ec50:500,n_hill:2.0,maxEffect:1, targetSystems:['metabolic','cardio','ins_axis'], targetMechanisms:['AMPK_UP','GLUCOSE_UPTAKE'], linkedRisks:[{system:'metabolic',direction:'down',strength:0.5},{system:'ins_axis',direction:'down',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  aspirin:   { id:'aspirin', name:'Аспирин 75 мг', class:'support', pk:{ka:0.9,k10:0.12,k12:0.06,k21:0.045,Vd:18,bioavailability:0.95,halfLifeHours:3}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:1000,n_hill:1.5,maxEffect:1, targetSystems:['cardio','blood'], targetMechanisms:['COX_INHIBITION','PLATELET_AGGREGATION_INHIBITION'], linkedRisks:[{system:'cardio',direction:'down',strength:0.3},{system:'blood',direction:'down',strength:0.5}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },

  bpc157:    { id:'bpc157', name:'BPC-157', class:'peptide_regenerative', pk:{ka:0.8,k10:0.15,k12:0.06,k21:0.04,Vd:5,bioavailability:0.5,halfLifeHours:4}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-0.3,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.1}, ec50:100,n_hill:1.9,maxEffect:1, targetSystems:['musculoskeletal'], targetMechanisms:['TISSUE_REPAIR','COLLAGEN_SYNTHESIS'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  tb500:     { id:'tb500', name:'TB-500 (Тимозин β-4)', class:'peptide_regenerative', pk:{ka:0.7,k10:0.12,k12:0.05,k21:0.035,Vd:8,bioavailability:0.5,halfLifeHours:6}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.05}, ec50:120,n_hill:1.85,maxEffect:1, targetSystems:['musculoskeletal'], targetMechanisms:['TISSUE_REPAIR','COLLAGEN_SYNTHESIS'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  ghrp2:     { id:'ghrp2', name:'GHRP-2', class:'peptide_ghrp', pk:{ka:0.75,k10:0.11,k12:0.048,k21:0.032,Vd:9,bioavailability:0.82,halfLifeHours:3.5}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.05,hct_impact:0,neuro_toxicity:0}, ec50:155,n_hill:1.9,maxEffect:1, targetSystems:['ghigf','endocrine','neuro'], targetMechanisms:['GHSR_AGONISM','GH_RELEASE'], linkedRisks:[{system:'ghigf',direction:'up',strength:0.4}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  sermorelin:{ id:'sermorelin', name:'Sermorelin (GHRH 1-29)', class:'peptide_ghrh', pk:{ka:0.65,k10:0.09,k12:0.04,k21:0.03,Vd:10,bioavailability:0.8,halfLifeHours:3}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:190,n_hill:1.8,maxEffect:1, targetSystems:['ghigf','endocrine','musculoskeletal'], targetMechanisms:['GHSR_AGONISM','GH_RELEASE','IGF1_UP'], linkedRisks:[{system:'ghigf',direction:'up',strength:0.5}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  peg_mgf:   { id:'peg_mgf', name:'PEG-MGF', class:'mgf', pk:{ka:0.25,k10:0.08,k12:0.035,k21:0.025,Vd:7,bioavailability:0.7,halfLifeHours:48}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:90,n_hill:1.9,maxEffect:1, targetSystems:['musculoskeletal'], targetMechanisms:['MGF_AGONISM','SATELLITE_CELL_ACTIVATION'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  thymosin_a1:{ id:'thymosin_a1', name:'Тимозин альфа-1', class:'peptide_immune', pk:{ka:0.6,k10:0.1,k12:0.04,k21:0.03,Vd:15,bioavailability:0.7,halfLifeHours:7}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:180,n_hill:1.8,maxEffect:1, targetSystems:['immunity'], targetMechanisms:['IMMUNE_MODULATION'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  semax:     { id:'semax', name:'Семакс', class:'peptide_nootropic', pk:{ka:0.8,k10:0.12,k12:0.05,k21:0.035,Vd:5,bioavailability:0.3,halfLifeHours:1}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.3}, ec50:50,n_hill:1.7,maxEffect:1, targetSystems:['neuro'], targetMechanisms:['NEUROPEPTIDE_MOD','GABA_MOD'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  selank:    { id:'selank', name:'Селанк', class:'peptide_nootropic', pk:{ka:0.75,k10:0.1,k12:0.04,k21:0.03,Vd:6,bioavailability:0.35,halfLifeHours:2}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.2}, ec50:60,n_hill:1.75,maxEffect:1, targetSystems:['neuro'], targetMechanisms:['NEUROPEPTIDE_MOD','GABA_MOD'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  epitalon:  { id:'epitalon', name:'Эпиталон', class:'peptide_nootropic', pk:{ka:0.7,k10:0.1,k12:0.04,k21:0.028,Vd:8,bioavailability:0.6,halfLifeHours:3}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.1}, ec50:100,n_hill:1.8,maxEffect:1, targetSystems:['neuro'], targetMechanisms:['NEUROPEPTIDE_MOD','GABA_MOD'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  gonadorelin:{ id:'gonadorelin', name:'Гонадорелин (пульс-терапия)', class:'peptide_gnrh', pk:{ka:0.8,k10:0.2,k12:0.08,k21:0.05,Vd:3,bioavailability:0.7,halfLifeHours:2.5}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:120,n_hill:2.0,maxEffect:1, targetSystems:['endocrine','reproductive'], targetMechanisms:['GNRH_AGONISM','LH_UP','FSH_UP'], linkedRisks:[{system:'reproductive',direction:'up',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  hgh_frag:  { id:'hgh_frag', name:'HGH Fragment 176-191', class:'peptide_fat_loss', pk:{ka:0.6,k10:0.12,k12:0.05,k21:0.03,Vd:8,bioavailability:0.5,halfLifeHours:3.5}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.15,hct_impact:0,neuro_toxicity:0}, ec50:200,n_hill:1.85,maxEffect:1, targetSystems:['metabolic'], targetMechanisms:['LIPOLYSIS_ACTIVATION','HSL_STIMULATION'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  drostanolone_prop: { id:'drostanolone_prop', name:'Дростанолон пропионат (Мастерон)', class:'drostanolone', esters:['propionate'], pk:{ka:0.4,k10:0.045,k12:0.02,k21:0.015,Vd:35,bioavailability:1,halfLifeHours:72}, pd:{AR_affinity:0.85,aromatization:0,five_alpha_reduction:1.0,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.2,hct_impact:2,neuro_toxicity:0.05}, ec50:350,n_hill:2.2,maxEffect:1, targetSystems:['endocrine','musculoskeletal','prostate','skin'], targetMechanisms:['AR_AGONISM','AROMATASE_INHIBITION','ANTI_ESTROGENIC'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.4},{system:'skin',direction:'up',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  drostanolone_enan: { id:'drostanolone_enan', name:'Дростанолон энантат', class:'drostanolone', esters:['enanthate'], pk:{ka:0.022,k10:0.045,k12:0.02,k21:0.015,Vd:35,bioavailability:1,halfLifeHours:240}, pd:{AR_affinity:0.85,aromatization:0,five_alpha_reduction:1.0,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.2,hct_impact:2,neuro_toxicity:0.05}, ec50:350,n_hill:2.2,maxEffect:1, targetSystems:['endocrine','musculoskeletal','prostate','skin'], targetMechanisms:['AR_AGONISM','AROMATASE_INHIBITION','ANTI_ESTROGENIC'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.4},{system:'skin',direction:'up',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  superdrol: { id:'superdrol', name:'Метилдростанолон (Superdrol)', class:'oral_17aa', pk:{ka:0.85,k10:0.06,k12:0.03,k21:0.022,Vd:28,bioavailability:0.85,halfLifeHours:8}, pd:{AR_affinity:1.3,aromatization:0,five_alpha_reduction:0.9,progestogenic:0,hepatotoxicity:3.5,lipid_impact:-0.85,hct_impact:3,neuro_toxicity:0.12}, ec50:40,n_hill:2.1,maxEffect:1, targetSystems:['hepatic','cardio','endocrine','reproductive','skin'], targetMechanisms:['AR_AGONISM','CYP3A4_METABOLISM','GLYCOGEN_SYNTHESIS'], linkedRisks:[{system:'hepatic',direction:'up',strength:0.9},{system:'cardio',direction:'up',strength:0.5},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'constrict',thrombosisRisk:'high',cnsLoad:'low'} },
  anadrol:   { id:'anadrol', name:'Оксиметолон (Анаполон)', class:'oral_17aa', pk:{ka:0.85,k10:0.055,k12:0.028,k21:0.02,Vd:32,bioavailability:0.8,halfLifeHours:10}, pd:{AR_affinity:0.9,aromatization:0.4,five_alpha_reduction:0.3,progestogenic:0.1,hepatotoxicity:3.2,lipid_impact:-0.8,hct_impact:5,neuro_toxicity:0.1}, ec50:80,n_hill:2.0,maxEffect:1, targetSystems:['hepatic','cardio','endocrine','reproductive','skin'], targetMechanisms:['AR_AGONISM','CYP3A4_METABOLISM','GLYCOGEN_SYNTHESIS'], linkedRisks:[{system:'hepatic',direction:'up',strength:0.9},{system:'cardio',direction:'up',strength:0.5},{system:'endocrine',direction:'down',strength:0.7}], cvProfile:{bloodPressure:'up',heartRate:'neutral',vascularTone:'constrict',thrombosisRisk:'high',cnsLoad:'low'} },
  mesterolone:{ id:'mesterolone', name:'Местеролон (Провирон)', class:'dht_derivative', pk:{ka:0.85,k10:0.07,k12:0.03,k21:0.025,Vd:25,bioavailability:0.3,halfLifeHours:12}, pd:{AR_affinity:1.1,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0.5,lipid_impact:-0.1,hct_impact:0.5,neuro_toxicity:0}, ec50:150,n_hill:2.0,maxEffect:0.7, targetSystems:['endocrine','prostate','skin'], targetMechanisms:['AR_AGONISM','SHBG_BINDING'], linkedRisks:[{system:'prostate',direction:'up',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  hcg:       { id:'hcg', name:'ХГЧ (хорионический гонадотропин)', class:'pct_gonadotropin', pk:{ka:0.3,k10:0.02,k12:0.01,k21:0.008,Vd:3,bioavailability:0.75,halfLifeHours:36}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:80,n_hill:2.0,maxEffect:1, targetSystems:['endocrine','reproductive'], targetMechanisms:['LH_MIMETIC','TESTOSTERONE_PRODUCTION'], linkedRisks:[{system:'endocrine',direction:'up',strength:0.4},{system:'reproductive',direction:'up',strength:0.5}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  vitamin_d3:{ id:'vitamin_d3', name:'Витамин D3', class:'support', pk:{ka:0.15,k10:0.005,k12:0.002,k21:0.001,Vd:200,bioavailability:0.6,halfLifeHours:720}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-0.1,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.05}, ec50:500,n_hill:1.7,maxEffect:1, targetSystems:['endocrine','immune','musculoskeletal'], targetMechanisms:['VDR_AGONISM','CALCIUM_ABSORPTION','IMMUNE_MODULATION'], linkedRisks:[{system:'endocrine',direction:'down',strength:0.2},{system:'immunity',direction:'down',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  vitamin_k2:{ id:'vitamin_k2', name:'Витамин K2 (МК-7)', class:'support', pk:{ka:0.2,k10:0.008,k12:0.003,k21:0.002,Vd:80,bioavailability:0.7,halfLifeHours:96}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.08,hct_impact:0,neuro_toxicity:0}, ec50:400,n_hill:1.8,maxEffect:1, targetSystems:['cardio','musculoskeletal'], targetMechanisms:['GLA_PROTEIN_ACTIVATION','CALCIUM_REGULATION'], linkedRisks:[{system:'cardio',direction:'down',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  zinc_sup:  { id:'zinc_sup', name:'Цинк пиколинат', class:'support', pk:{ka:0.5,k10:0.04,k12:0.02,k21:0.015,Vd:20,bioavailability:0.65,halfLifeHours:24}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-0.05,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.03}, ec50:300,n_hill:1.9,maxEffect:1, targetSystems:['endocrine','immune','reproductive','skin'], targetMechanisms:['ZINC_COFACTOR','ANTIOXIDANT','AROMATASE_INHIBITION'], linkedRisks:[{system:'endocrine',direction:'up',strength:0.3},{system:'immunity',direction:'down',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  boron:     { id:'boron', name:'Бор', class:'support', pk:{ka:0.5,k10:0.05,k12:0.02,k21:0.015,Vd:15,bioavailability:0.7,halfLifeHours:28}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:300,n_hill:1.9,maxEffect:1, targetSystems:['endocrine','musculoskeletal'], targetMechanisms:['SHBG_REGULATION','TESTOSTERONE_UP'], linkedRisks:[{system:'endocrine',direction:'up',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  selenium_sup:{ id:'selenium_sup', name:'Селен (селексен)', class:'support', pk:{ka:0.45,k10:0.04,k12:0.018,k21:0.012,Vd:12,bioavailability:0.8,halfLifeHours:24}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-0.1,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:350,n_hill:1.8,maxEffect:1, targetSystems:['endocrine','immune','thyroid'], targetMechanisms:['SELENOPROTEIN_SYNTHESIS','ANTIOXIDANT','THYROID_HORMONE_METABOLISM'], linkedRisks:[{system:'thyroid',direction:'down',strength:0.3},{system:'immunity',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  vitamin_b6:{ id:'vitamin_b6', name:'Витамин B6 (P5P)', class:'support', pk:{ka:0.6,k10:0.06,k12:0.025,k21:0.018,Vd:12,bioavailability:0.8,halfLifeHours:14}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.1}, ec50:250,n_hill:1.9,maxEffect:1, targetSystems:['neuro','endocrine'], targetMechanisms:['NEUROTRANSMITTER_SYNTHESIS','DOPAMINE_PRECURSOR','PROLACTIN_REGULATION'], linkedRisks:[{system:'neuro',direction:'down',strength:0.3},{system:'endocrine',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  vitamin_b12:{ id:'vitamin_b12', name:'Витамин B12 (метилкобаламин)', class:'support', pk:{ka:0.5,k10:0.04,k12:0.02,k21:0.015,Vd:10,bioavailability:0.75,halfLifeHours:18}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-0.05,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:300,n_hill:1.85,maxEffect:1, targetSystems:['neuro','hematologic'], targetMechanisms:['METHYLATION_CYCLE','MYELIN_SYNTHESIS','HOMOCYSTEINE_REGULATION'], linkedRisks:[{system:'neuro',direction:'down',strength:0.2},{system:'hematologic',direction:'down',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  folate:    { id:'folate', name:'Метилфолат', class:'support', pk:{ka:0.6,k10:0.05,k12:0.02,k21:0.015,Vd:8,bioavailability:0.85,halfLifeHours:12}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:250,n_hill:1.9,maxEffect:1, targetSystems:['neuro','hematologic'], targetMechanisms:['METHYLATION_CYCLE','DNA_SYNTHESIS','HOMOCYSTEINE_REGULATION'], linkedRisks:[{system:'neuro',direction:'down',strength:0.2},{system:'hematologic',direction:'down',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  coq10:     { id:'coq10', name:'Коэнзим Q10', class:'support', pk:{ka:0.3,k10:0.02,k12:0.01,k21:0.007,Vd:60,bioavailability:0.4,halfLifeHours:48}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.1,hct_impact:0,neuro_toxicity:-0.1}, ec50:600,n_hill:1.8,maxEffect:1, targetSystems:['cardio','neuro'], targetMechanisms:['MITOCHONDRIAL_ENERGY','ANTIOXIDANT','COENZYME_ELECTRON_TRANSPORT'], linkedRisks:[{system:'cardio',direction:'down',strength:0.3},{system:'neuro',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  alpha_lipoic:{ id:'alpha_lipoic', name:'Альфа-липоевая кислота', class:'support', pk:{ka:0.55,k10:0.06,k12:0.025,k21:0.018,Vd:18,bioavailability:0.6,halfLifeHours:6}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-0.2,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.25}, ec50:400,n_hill:1.8,maxEffect:1, targetSystems:['hepatic','neuro','metabolic'], targetMechanisms:['ANTIOXIDANT','GLUTATHIONE_UP','INSULIN_SENSITIVITY'], linkedRisks:[{system:'hepatic',direction:'down',strength:0.3},{system:'neuro',direction:'down',strength:0.3},{system:'metabolic',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  milk_thistle:{ id:'milk_thistle', name:'Расторопша (силимарин)', class:'support', pk:{ka:0.5,k10:0.06,k12:0.025,k21:0.018,Vd:30,bioavailability:0.5,halfLifeHours:12}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-1.0,lipid_impact:0.05,hct_impact:0,neuro_toxicity:0}, ec50:500,n_hill:1.8,maxEffect:1, targetSystems:['hepatic'], targetMechanisms:['ANTIOXIDANT','LIVER_REGENERATION','CYP450_MODULATION'], linkedRisks:[{system:'hepatic',direction:'down',strength:0.4}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  curcumin_sup:{ id:'curcumin_sup', name:'Куркумин с пиперином', class:'support', pk:{ka:0.35,k10:0.03,k12:0.012,k21:0.008,Vd:50,bioavailability:0.5,halfLifeHours:36}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-0.3,lipid_impact:0.1,hct_impact:0,neuro_toxicity:-0.08}, ec50:500,n_hill:1.75,maxEffect:1, targetSystems:['cardio','neuro','hepatic'], targetMechanisms:['ANTIINFLAMMATORY','ANTIOXIDANT','NFKB_INHIBITION'], linkedRisks:[{system:'cardio',direction:'down',strength:0.3},{system:'neuro',direction:'down',strength:0.2},{system:'hepatic',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  phosphatidylcholine:{ id:'phosphatidylcholine', name:'Фосфатидилхолин', class:'support', pk:{ka:0.4,k10:0.035,k12:0.015,k21:0.01,Vd:40,bioavailability:0.6,halfLifeHours:24}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-0.4,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:450,n_hill:1.8,maxEffect:1, targetSystems:['hepatic','neuro'], targetMechanisms:['MEMBRANE_PHOSPHOLIPID','LIVER_LIPID_METABOLISM','CHOLINE_DONOR'], linkedRisks:[{system:'hepatic',direction:'down',strength:0.3},{system:'neuro',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  ashwagandha:{ id:'ashwagandha', name:'Ашваганда KSM-66', class:'support', pk:{ka:0.4,k10:0.03,k12:0.015,k21:0.01,Vd:40,bioavailability:0.6,halfLifeHours:36}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-0.1,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.25}, ec50:350,n_hill:1.85,maxEffect:1, targetSystems:['neuro','endocrine'], targetMechanisms:['CORTISOL_REGULATION','GABA_MOD','THYROID_STIMULATION'], linkedRisks:[{system:'neuro',direction:'down',strength:0.4},{system:'endocrine',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'down',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  tongkat_ali:{ id:'tongkat_ali', name:'Тонгкат Али (Эврикома длиннолистная)', class:'support', pk:{ka:0.35,k10:0.03,k12:0.015,k21:0.01,Vd:45,bioavailability:0.55,halfLifeHours:24}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.05}, ec50:400,n_hill:1.8,maxEffect:1, targetSystems:['endocrine','musculoskeletal'], targetMechanisms:['TESTOSTERONE_UP','CORTISOL_REGULATION','SHBG_REGULATION'], linkedRisks:[{system:'endocrine',direction:'up',strength:0.3}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  fadogia:   { id:'fadogia', name:'Фадогия агрестис', class:'support', pk:{ka:0.4,k10:0.035,k12:0.015,k21:0.01,Vd:35,bioavailability:0.5,halfLifeHours:18}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:350,n_hill:1.85,maxEffect:1, targetSystems:['endocrine'], targetMechanisms:['TESTOSTERONE_UP','LH_UP'], linkedRisks:[{system:'endocrine',direction:'up',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  shilajit:  { id:'shilajit', name:'Мумиё', class:'support', pk:{ka:0.45,k10:0.04,k12:0.02,k21:0.012,Vd:30,bioavailability:0.6,halfLifeHours:20}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.05,hct_impact:0,neuro_toxicity:-0.05}, ec50:450,n_hill:1.75,maxEffect:1, targetSystems:['neuro','endocrine'], targetMechanisms:['FULVIC_ACID','ANTIOXIDANT','MITOCHONDRIAL_ENERGY'], linkedRisks:[{system:'neuro',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  ginseng_sup:{ id:'ginseng_sup', name:'Женьшень (Panax ginseng)', class:'support', pk:{ka:0.4,k10:0.03,k12:0.015,k21:0.01,Vd:35,bioavailability:0.55,halfLifeHours:20}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.08}, ec50:400,n_hill:1.8,maxEffect:1, targetSystems:['neuro','endocrine','immune'], targetMechanisms:['ADAPTOGEN','NO_UP','CORTISOL_REGULATION'], linkedRisks:[{system:'neuro',direction:'down',strength:0.3},{system:'endocrine',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  saw_palmetto:{ id:'saw_palmetto', name:'Сереноа ползучая', class:'support', pk:{ka:0.4,k10:0.03,k12:0.015,k21:0.01,Vd:50,bioavailability:0.55,halfLifeHours:48}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:350,n_hill:1.85,maxEffect:1, targetSystems:['prostate','endocrine'], targetMechanisms:['5AR_INHIBITION','DHT_BLOCKADE','ANTIANDROGEN'], linkedRisks:[{system:'prostate',direction:'down',strength:0.4},{system:'endocrine',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  probiotics_sup:{ id:'probiotics_sup', name:'Пробиотики (Lactobacillus/Bifidobacterium)', class:'support', pk:{ka:0.2,k10:0.01,k12:0.005,k21:0.003,Vd:5,bioavailability:0.3,halfLifeHours:12}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:-0.15,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:800,n_hill:1.6,maxEffect:1, targetSystems:['immunity','metabolic'], targetMechanisms:['GUT_FLORA_MODULATION','IMMUNE_MODULATION','SHORT_CHAIN_FATTY_ACIDS'], linkedRisks:[{system:'immunity',direction:'down',strength:0.3},{system:'metabolic',direction:'down',strength:0.2}], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  taurine_sup:{ id:'taurine_sup', name:'Таурин', class:'support', pk:{ka:0.6,k10:0.05,k12:0.022,k21:0.015,Vd:30,bioavailability:0.8,halfLifeHours:10}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0.05,hct_impact:0,neuro_toxicity:-0.12}, ec50:300,n_hill:1.85,maxEffect:1, targetSystems:['cardio','neuro','musculoskeletal'], targetMechanisms:['GABA_MOD','CALCIUM_REGULATION','ANTIOXIDANT','OSMOREGULATION'], linkedRisks:[{system:'cardio',direction:'down',strength:0.3},{system:'neuro',direction:'down',strength:0.3}], cvProfile:{bloodPressure:'down',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'} },
  ghk_cu:     { id:'ghk_cu', name:'GHK-Cu (Медь-пептид)', class:'peptide_regenerative', pk:{ka:0.5,k10:0.04,k12:0.018,k21:0.012,Vd:15,bioavailability:0.4,halfLifeHours:2}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:100,n_hill:1.5,maxEffect:1.0, targetSystems:['musculoskeletal','skin'], targetMechanisms:['TISSUE_REPAIR','COLLAGEN_SYNTHESIS','ANTIOXIDANT'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'}, description:'Медь-связывающий трипептид Gly-His-Lys с медным ионом. Стимулирует синтез коллагена I и III, эластина, гликозаминогликанов. Антиоксидант, антивозрастной.' },
  dsip:       { id:'dsip', name:'DSIP (Дельта-сон-индуцирующий пептид)', class:'peptide_nootropic', pk:{ka:0.45,k10:0.03,k12:0.015,k21:0.008,Vd:20,bioavailability:0.3,halfLifeHours:3}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:-0.15}, ec50:200,n_hill:1.4,maxEffect:0.9, targetSystems:['neuro'], targetMechanisms:['NEUROPEPTIDE_MOD','GABA_MOD'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'}, description:'Эндогенный нонапептид, индуцирующий дельта-сон. Нормализует циклы сна, снижает кортизол, модулирует ГАМК-рецепторы.' },
  melanotan2: { id:'melanotan2', name:'Меланотан II', class:'peptide_other', pk:{ka:0.5,k10:0.035,k12:0.015,k21:0.01,Vd:25,bioavailability:0.3,halfLifeHours:4}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:50,n_hill:1.6,maxEffect:0.95, targetSystems:['endocrine'], targetMechanisms:['PEPTIDE_MOD'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'}, description:'Циклический α-MSH аналог. Агонист MC1R (меланогенез) и MC4R (либидо, аппетит). Индуцирует загар без УФ, подавляет аппетит, ↑ либидо.' },
  aod9604:    { id:'aod9604', name:'AOD-9604', class:'peptide_fat_loss', pk:{ka:0.4,k10:0.03,k12:0.012,k21:0.008,Vd:18,bioavailability:0.25,halfLifeHours:3}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.2,hct_impact:0,neuro_toxicity:0}, ec50:100,n_hill:1.4,maxEffect:0.85, targetSystems:['metabolic'], targetMechanisms:['LIPOLYSIS_ACTIVATION','HSL_STIMULATION'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'}, description:'Модифицированный фрагмент гормона роста (аминокислоты 177-191). Стимулирует липолиз и ингибирует липогенез без влияния на рост и уровень глюкозы.' },
  mots_c:     { id:'mots_c', name:'MOTS-C', class:'peptide_nootropic', pk:{ka:0.45,k10:0.035,k12:0.015,k21:0.01,Vd:22,bioavailability:0.35,halfLifeHours:4}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.15,hct_impact:0,neuro_toxicity:0}, ec50:150,n_hill:1.5,maxEffect:0.9, targetSystems:['neuro'], targetMechanisms:['NEUROPEPTIDE_MOD','GABA_MOD'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'}, description:'Митохондриально-производный пептид (16 аа). Регулирует метаболизм через AMPK-активацию, ↑ чувствительность к инсулину, ↑ glucagon-like эффект. Противовозрастной.' },
  ss31:       { id:'ss31', name:'SS-31 (Elamipretide)', class:'peptide_regenerative', pk:{ka:0.4,k10:0.03,k12:0.012,k21:0.008,Vd:20,bioavailability:0.25,halfLifeHours:3}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:200,n_hill:1.5,maxEffect:0.95, targetSystems:['musculoskeletal','cardio'], targetMechanisms:['TISSUE_REPAIR','COLLAGEN_SYNTHESIS','MITOCHONDRIAL_PROTECTION'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'}, description:'Тетрапептид, нацеленный на внутреннюю митохондриальную мембрану. Стабилизирует кардиолипин, ↓ ROS-продукцию, ↑ АТФ-синтез. Кардиопротектор, нейропротектор.' },
  foxo4_dri:  { id:'foxo4_dri', name:'FOXO4-DRI', class:'peptide_other', pk:{ka:0.35,k10:0.02,k12:0.01,k21:0.007,Vd:25,bioavailability:0.2,halfLifeHours:5}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:0,hct_impact:0,neuro_toxicity:0}, ec50:300,n_hill:1.4,maxEffect:0.85, targetSystems:['endocrine'], targetMechanisms:['PEPTIDE_MOD'], linkedRisks:[], cvProfile:{bloodPressure:'neutral',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'}, description:'Сенолитический пептид — ингибирует взаимодействие FOXO4-p53, вызывая апоптоз стареющих (SEN) клеток. Противовозрастной, улучшение функции тканей.' },

  // === GLP-1 АГОНИСТЫ ===
  semaglutide:{ id:'semaglutide', name:'Семаглутид (Оземпик)', class:'glp1', pk:{ka:0.3,k10:0.02,k12:0.01,k21:0.008,Vd:12,bioavailability:0.7,halfLifeHours:168}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.2,hct_impact:0,neuro_toxicity:0}, ec50:50,n_hill:2.0,maxEffect:1, targetSystems:['metabolic','ins_axis','cardio'], targetMechanisms:['GLP1_AGONISM','GIP_AGONISM'], linkedRisks:[{system:'metabolic',direction:'down',strength:0.5},{system:'cardio',direction:'down',strength:0.3}], cvProfile:{bloodPressure:'down',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'}, description:'Агонист GLP-1 рецепторов (Оземпик, Wegovy). Замедляет опорожнение желудка, снижает аппетит, стимулирует инсулин глюкозозависимо. Подавляет глюкагон. Т½ ~7 дней — 1 инъекция/нед.' },
  tirzepatide:{ id:'tirzepatide', name:'Тирзепатид (Мунджаро)', class:'glp1', pk:{ka:0.28,k10:0.018,k12:0.009,k21:0.007,Vd:14,bioavailability:0.72,halfLifeHours:168}, pd:{AR_affinity:0,aromatization:0,five_alpha_reduction:0,progestogenic:0,hepatotoxicity:0,lipid_impact:-0.3,hct_impact:0,neuro_toxicity:0}, ec50:40,n_hill:2.1,maxEffect:1.2, targetSystems:['metabolic','ins_axis','cardio'], targetMechanisms:['GLP1_AGONISM','GIP_AGONISM'], linkedRisks:[{system:'metabolic',direction:'down',strength:0.5},{system:'cardio',direction:'down',strength:0.3}], cvProfile:{bloodPressure:'down',heartRate:'neutral',vascularTone:'neutral',thrombosisRisk:'low',cnsLoad:'low'}, description:'Двойной агонист GLP-1/GIP рецепторов (Мунджаро, Zepbound). Эффективнее семаглутида: ~20% vs ~15% снижения веса. Стимулирует инсулин, подавляет глюкагон, замедляет моторику ЖКТ. Т½ ~5 дней — 1 инъекция/нед.' },
};

const CLASS_DEFAULTS: Record<string, Partial<PharmaSubstance>> = {
  testosterone:{ description:'Эндогенный андрогенный гормон и его эфиры — фундамент любого ААС курса. Связывается с андрогенными рецепторами (AR) в мышечной ткани, костях, ЦНС, вызывая активацию транскрипции генов белкового синтеза (mTOR-путь). Ароматизируется в эстрадиол (E2) через CYP19A1, что даёт нейропротекцию, либидо и минерализацию костей, но при избытке вызывает гинекомастию и задержку жидкости. 5α-редуцируется в ДГТ — мощный андроген для кожи, простаты и ЦНС. Стимулирует эритропоэз через эритропоэтин — повышает гематокрит (HCT). Подавляет ось HPTA (GnRH→LH/FSH↓). Терапевтически применяется при гипогонадизме, саркопении, остеопорозе, анемии. На курсе требует контроля E2 (ингибиторы ароматазы), HCT, липидного профиля.', mechanisms:['AR_AGONISM','mTOR_UP','PROTEIN_SYNTHESIS','NITROGEN_RETENTION','ERYTHROPOIESIS','IGF1_UPREGULATION','5AR_REDUCTION','AROMATIZATION'], sideEffects:[{effect:'Эстрогенные — гинекомастия, задержка воды, гипертензия, эмоциональная лабильность',frequency:'common'},{effect:'Андрогенные — акне, алопеция (при генетической предрасположенности), гипертрофия простаты',frequency:'common'},{effect:'Подавление HPTA — снижение ЛГ/ФСГ, атрофия яичек, падение эндогенного тестостерона',frequency:'common'},{effect:'Дислипидемия — снижение ЛПВП, повышение ЛПНП, повышение ApoB',frequency:'common'},{effect:'Полицитемия — повышение HCT >50%, риск тромбоза',frequency:'common'},{effect:'Гипертензия — за счёт задержки натрия и воды',frequency:'common'}], contraindications:['Рак простаты','Рак молочной железы (мужчины)','Тромбофилия','Полицитемия (HCT>54%)','Обструктивная гипертрофия простаты','Тяжёлая сердечная недостаточность (NYHA III-IV)','Нелеченная гипертензия','Беременность (кат. X)'], dosageRange:{min:250,max:1000,unit:'mg/wk',frequency:'2x/week'} },
  trenbolone:{ description:'Производное 19-нортестостерона (тренболон) — один из мощнейших ААС, превосходящий тестостерон по аффинности к AR в 3-5 раз. Не ароматизируется (нет эстрогенных побочек), но имеет прогестогенную активность через PR, что вызывает пролактин-опосредованные эффекты. Мощно подавляет кортизол через блокаду GR, создавая выраженный антикатаболический эффект. Высокая нейротоксичность — агрессия, бессонница, тревожность, когнитивные нарушения за счёт модуляции дофаминовых D2-рецепторов и ГАМК-ергической передачи. Гепатотоксичен даже в инъекционной форме за счёт метаболизма через CYP3A4 с образованием токсичных метаболитов. Вызывает "трен-кашель" (бронхоспазм). Категорически не рекомендуется для первых курсов и использования соло.', mechanisms:['AR_AGONISM (3-5x stronger)','PR_AGONISM','GR_ANTAGONISM','CORTISOL_SUPPRESSION','IGF1_UPREGULATION','DOPAMINE_MODULATION','GABA_MODULATION','CYP3A4_METABOLISM'], sideEffects:[{effect:'Нейротоксичность — агрессия, импульсивность, бессонница, кошмары, тревожность, паранойя',frequency:'common'},{effect:'Гепатотоксичность — АЛТ/АСТ↑, ГГТ↑, холестаз, повреждение гепатоцитов',frequency:'common'},{effect:'Прогестиновые — пролактин↑, снижение либидо, аноргазмия, лактация',frequency:'common'},{effect:'Сильное подавление HPTA — полное выключение оси за 2-4 недели',frequency:'common'},{effect:'Трен-кашель — бронхоспазм после инъекции',frequency:'common'},{effect:'Дислипидемия — ЛПВП↓↓, ЛПНП↑↑, ApoB↑',frequency:'common'},{effect:'Кардиотоксичность — гипертрофия ЛЖ, фиброз миокарда',frequency:'rare'},{effect:'Нефротоксичность — протеинурия, повышение креатинина',frequency:'rare'}], contraindications:['Психиатрические заболевания (биполярное, шизофрения, тяжёлая депрессия)','Заболевания печени (гепатит, цирроз)','Тяжёлая гипертензия','ИБС, сердечная недостаточность','ХБП (ClCr<60)','Эпилепсия','Беременность/лактация'], dosageRange:{min:150,max:400,unit:'mg/wk',frequency:'2-3x/week'} },
  nandrolone:{ description:'19-нортестостерон (нандролон) — ААС с уникальным анаболическим индексом ~12:1 и минимальной андрогенностью. Связывается с AR (аффинность 90% от тестостерона) и PR (выраженная прогестогенная активность). Ключевое отличие: стимулирует синтез коллагена I/III типов и минерализацию костной ткани — клинически применяется при остеопорозе, ожогах, анемии. Ароматизируется слабо (20% от тестостерона), но через PR-путь может вызывать гинекомастию (МПК-опосредованная). Подавляет HPTA умеренно. NPP (фенилпропионат) — короткий эфир (T½=4 дня), Дека (деканоат) — длинный (T½=14 дней). Хорошо комбинируется с тестостероном как база массонаборного курса.', mechanisms:['AR_AGONISM','PR_AGONISM','COLLAGEN_SYNTHESIS','BONE_MINERALIZATION','NITROGEN_RETENTION','ERYTHROPOIESIS','PROGESTIN_ACTIVITY','AROMATIZATION (20%)'], sideEffects:[{effect:'Прогестиновые — пролактин↑, гинекомастия (МПК-путь), снижение либидо',frequency:'common'},{effect:'Подавление HPTA — ЛГ/ФСГ↓, подавление сперматогенеза',frequency:'common'},{effect:'Дислипидемия — ЛПВП↓, умеренное',frequency:'common'},{effect:'Андрогенные — акне, жирность кожи (слабее тестостерона)',frequency:'rare'},{effect:'Гепатотоксичность — минимальная для инъекционных эфиров',frequency:'very_rare'}], contraindications:['Рак простаты','Рак молочной железы','Тяжёлая гиперкальциемия','Беременность','Тяжёлые заболевания печени'], dosageRange:{min:200,max:600,unit:'mg/wk',frequency:'1-2x/week'} },
  boldenone:{ description:'Болденон (Equipoise). Увеличивает эритропоэтин, HCT. Дозозависимая гепатотоксичность.', mechanisms:['AR_AGONISM','ERYTHROPOIESIS','PROTEIN_SYNTHESIS'], sideEffects:[{effect:'Полицитемия',frequency:'common'},{effect:'Эстрогенные — ароматизация 50%',frequency:'common'},{effect:'Гепатотоксичность при высоких дозах',frequency:'rare'}], contraindications:['Полицитемия','Рак простаты'], dosageRange:{min:300,max:800,unit:'mg/wk',frequency:'2x/week'} },
  primobolan:{ description:'Метенолон. Не ароматизируется. Минимальная гепатотоксичность. Сохраняет мышцы при дефиците калорий.', mechanisms:['AR_AGONISM','ANTI_CATABOLIC'], sideEffects:[{effect:'Андрогенные — акне, алопеция',frequency:'rare'},{effect:'Подавление HPTA',frequency:'common'}], contraindications:['Рак простаты'], dosageRange:{min:400,max:800,unit:'mg/wk',frequency:'2x/week'} },
  oral_17aa:{ description:'Оральный 17-α-алкилированный ААС. Высокая гепатотоксичность. Короткий период действия (4-16 ч).', mechanisms:['AR_AGONISM','GLYCOGEN_SYNTHESIS'], sideEffects:[{effect:'Гепатотоксичность — АЛТ/АСТ↑↑',frequency:'common'},{effect:'Дислипидемия — ЛПВП↓↓',frequency:'common'},{effect:'Подавление HPTA',frequency:'common'}], contraindications:['Заболевания печени','Гепатит','Беременность'], dosageRange:{min:20,max:100,unit:'mg/d',frequency:'1-3x/d'} },
  sarm:{ description:'Селективный модулятор андрогенных рецепторов. Анаболический эффект без воздействия на простату.', mechanisms:['AR_SELECTIVE_AGONISM'], sideEffects:[{effect:'Подавление LH/FSH',frequency:'common'},{effect:'Дислипидемия',frequency:'common'},{effect:'Гепатотоксичность при высоких дозах',frequency:'rare'}], contraindications:['Рак простаты','Беременность'], dosageRange:{min:5,max:30,unit:'mg/d',frequency:'1x/d'} },
  drostanolone:{ description:'Дростанолон (мастерон). Производное ДГТ. Не ароматизируется. Антиэстроген.', mechanisms:['AR_AGONISM','AROMATASE_INHIBITION','ANTI_ESTROGENIC'], sideEffects:[{effect:'Андрогенные — акне, алопеция',frequency:'common'},{effect:'Подавление HPTA',frequency:'common'}], contraindications:['Рак простаты'], dosageRange:{min:300,max:600,unit:'mg/wk',frequency:'2x/week'} },
  dht_derivative:{ description:'Производное дигидротестостерона. Не ароматизируется. Конкурирует за SHBG.', mechanisms:['AR_AGONISM','SHBG_BINDING'], sideEffects:[{effect:'Андрогенные — акне, алопеция',frequency:'common'}], contraindications:['Рак простаты'], dosageRange:{min:25,max:100,unit:'mg/d',frequency:'1-2x/d'} },
  peptide_ghrh:{ description:'Аналог GHRH. Стимулирует ГР из гипофиза → IGF-1↑.', mechanisms:['GHSR_AGONISM','GH_RELEASE','IGF1_UP'], sideEffects:[{effect:'Повышение аппетита',frequency:'common'},{effect:'Пролактин↑',frequency:'rare'},{effect:'Отёки',frequency:'rare'}], contraindications:['Активный рак','Диабетическая ретинопатия'] },
  peptide_ghrp:{ description:'Грелин-миметик. Стимулирует ГР через GHS-R. Комбинируется с GHRH.', mechanisms:['GHSR_AGONISM','GH_RELEASE'], sideEffects:[{effect:'Повышение аппетита',frequency:'common'},{effect:'Кортизол/пролактин↑',frequency:'rare'}], contraindications:['Активный рак','Беременность'] },
  peptide_nootropic:{ description:'Нейротропный пептид. Улучшает когнитивные функции, снижает тревожность.', mechanisms:['NEUROPEPTIDE_MOD','GABA_MOD'], sideEffects:[], contraindications:['Индивидуальная непереносимость'] },
  peptide_regenerative:{ description:'Регенеративный пептид. Стимулирует восстановление тканей, синтез коллагена.', mechanisms:['TISSUE_REPAIR','COLLAGEN_SYNTHESIS'], sideEffects:[], contraindications:['Активный рак'] },
  peptide_fat_loss:{ description:'Липолитический пептид. Стимулирует расщепление жировой ткани через HSL.', mechanisms:['LIPOLYSIS_ACTIVATION','HSL_STIMULATION'], sideEffects:[], contraindications:['Беременность'] },
  peptide_other:{ description:'Специализированный пептид — загар, сенолиз, метаболическая регуляция.', mechanisms:['PEPTIDE_MOD'], sideEffects:[], contraindications:['По назначению'] },
  pct_serm:{ description:'SERM — блокирует ER в гипоталамусе. Стимулирует ГнРГ для восстановления HPTA.', mechanisms:['ER_ANTAGONISM','GNRH_UP','LH_UP'], sideEffects:[{effect:'Приливы',frequency:'common'},{effect:'Зрительные нарушения (редко)',frequency:'very_rare'}], contraindications:['Тромбоэмболия','Тяжёлые заболевания печени'] },
  pct_aromatase:{ description:'Ингибитор ароматазы. Подавляет конверсию тестостерона → эстрадиол.', mechanisms:['AROMATASE_INHIBITION','E2_SUPPRESSION'], sideEffects:[{effect:'Боли в суставах',frequency:'common'},{effect:'Дислипидемия',frequency:'common'}], contraindications:['Беременность','Остеопороз'] },
  pct_dopamine:{ description:'Агонист дофамина D2. Снижает пролактин.', mechanisms:['D2_AGONISM','PROLACTIN_SUPPRESSION'], sideEffects:[{effect:'Тошнота',frequency:'common'},{effect:'Ортостатическая гипотензия',frequency:'rare'}], contraindications:['Психозы','Тяжёлая гипертензия'] },
  pct_gonadotropin:{ description:'ХГЧ — аналог ЛГ. Стимулирует клетки Лейдига → тестостерон.', mechanisms:['LH_MIMETIC','TESTOSTERONE_PRODUCTION'], sideEffects:[{effect:'Эстрогенные',frequency:'common'},{effect:'Подавление HPTA при высоких дозах',frequency:'rare'}], contraindications:['Рак простаты','Рак яичка'] },
  peptide_gnrh:{ description:'Аналог ГнРГ. Стимулирует ЛГ и ФСГ. Восстанавливает HPTA.', mechanisms:['GNRH_AGONISM','LH_UP','FSH_UP'], sideEffects:[], contraindications:['Рак простаты (flare)'] },
  igf1:{ description:'IGF-1 — анаболический гормон. Стимулирует пролиферацию клеток, гиперплазию мышц.', mechanisms:['IGF1R_AGONISM','CELL_PROLIFERATION'], sideEffects:[{effect:'Гипогликемия',frequency:'common'},{effect:'Гиперплазия органов',frequency:'rare'}], contraindications:['Активный рак','Беременность'] },
  mgf:{ description:'MGF — активирует сателлитные клетки. Вызывает гиперплазию мышц после нагрузки.', mechanisms:['SATELLITE_CELL_ACTIVATION'], sideEffects:[], contraindications:['Активный рак'] },
  insulin:{ description:'Инсулин — анаболический гормон. Мощный но опасный анаболик.', mechanisms:['GLUCOSE_TRANSPORT','AMINO_ACID_UPTAKE','GLYCOGEN_SYNTHESIS'], sideEffects:[{effect:'Гипогликемия — смертельно опасна',frequency:'common'},{effect:'Жиронакопление',frequency:'common'}], contraindications:['Без надзора — смертельно'] },
  glp1:{ description:'Агонист GLP-1/GIP рецепторов. Мощный контроль аппетита и снижение веса.', mechanisms:['GLP1_AGONISM','GIP_AGONISM','INSULIN_STIMULATION','GLUCAGON_SUPPRESSION','GASTRIC_EMPTYING_DELAY'], sideEffects:[{effect:'Тошнота, рвота, диарея',frequency:'common'},{effect:'Замедление опорожнения желудка',frequency:'common'},{effect:'Гипогликемия (редко, при комбинации с инсулином)',frequency:'rare'}], contraindications:['Медуллярный рак щитовидной железы (в анамнезе)','Семейная MEN-2','Тяжёлые гастропарезы','Панкреатит (острый, в анамнезе)','Непроходимость кишечника'] },
  support:{ description:'Нутрицевтик для поддержки здоровья и восполнения дефицитов.', mechanisms:['NUTRITIONAL_SUPPORT'], sideEffects:[], contraindications:['Индивидуальная непереносимость'] },
};

export function getPharmaDetail(id: string): PharmaSubstance | null {
  const raw = PHARMA_DB[id];
  if (!raw) return null;
  const defaults = CLASS_DEFAULTS[raw.class];
  if (!defaults) return raw;
  return {
    ...defaults,
    ...raw,
    mechanisms: raw.mechanisms || defaults.mechanisms,
    sideEffects: raw.sideEffects || defaults.sideEffects,
    contraindications: raw.contraindications || defaults.contraindications,
    description: raw.description || defaults.description,
    dosageRange: raw.dosageRange || defaults.dosageRange,
  };
}

export const SUBSTANCE_LIST = Object.values(PHARMA_DB);
export const SUBSTANCES_BY_CLASS: Record<string, PharmaSubstance[]> = {};
SUBSTANCE_LIST.forEach(s => {
  if(!SUBSTANCES_BY_CLASS[s.class]) SUBSTANCES_BY_CLASS[s.class] = [];
  SUBSTANCES_BY_CLASS[s.class].push(s);
});

export const PHARMA_CLASSES = [
  'testosterone', 'trenbolone', 'nandrolone', 'boldenone', 'primobolan', 'oral_17aa',
  'sarm', 'peptide_ghrh', 'peptide_ghrp', 'igf1', 'mgf', 'glp1', 'insulin',
  'drostanolone', 'peptide_gnrh',
  'peptide_fat_loss', 'peptide_other'
] as const;

type PharmaClass = typeof PHARMA_CLASSES[number];
