import puppeteer from 'puppeteer-core';
const CHROME='C:/Program Files/Google/Chrome/Application/chrome.exe'; const pe=[];
const browser=await puppeteer.launch({executablePath:CHROME,headless:'new',args:['--no-sandbox','--disable-gpu','--window-size=420,860'],defaultViewport:{width:420,height:860}});
const page=await browser.newPage(); page.on('pageerror',e=>pe.push(e.message));
await page.goto('http://localhost:4174/',{waitUntil:'networkidle2',timeout:45000});
await page.waitForFunction(()=>!document.querySelector('.screen-loading'),{timeout:30000}).catch(()=>{});
await new Promise(r=>setTimeout(r,2000));
const clickText=async(t)=>{try{const el=await page.evaluateHandle((x)=>{const a=[...document.querySelectorAll('button,a,div[role=button],li,h2,h3')];return a.find(e=>(e.innerText||'').includes(x))||null;},t);const n=el.asElement();if(n){await n.click();return true;}}catch(e){}return false;};
const clickBtn=async(re)=>{try{return await page.evaluate((r)=>{const b=[...document.querySelectorAll('button')].find(x=>new RegExp(r).test(x.innerText));if(b){b.click();return b.innerText;}return null;},re);}catch(e){return null;}};
const body=async(n=900)=>(await page.evaluate(()=>document.body.innerText)).replace(/\n{2,}/g,'\n').slice(0,n);

await clickText('Тренинг');await new Promise(r=>setTimeout(r,1000));
await clickText('Планирование');await new Promise(r=>setTimeout(r,1500));
await clickBtn('🛠 Ручной сбор');await new Promise(r=>setTimeout(r,1500));
await clickBtn('📋 План');await new Promise(r=>setTimeout(r,1500));
// generate (find the generate button — might be "Сгенерировать" or a specific label)
await page.evaluate(()=>{ const b=[...document.querySelectorAll('button')].find(x=>/Сгенерировать|▶|План|Generate/.test(x.innerText)); if(b)b.click(); });
await new Promise(r=>setTimeout(r,2500));
await page.evaluate(()=>window.scrollTo(0,500));
await new Promise(r=>setTimeout(r,1000));
const t=await body(900);
console.log('=== Manual План output ===');
console.log(t);
console.log('has split name:', /split|сплит|Фулбоди|Верх|Низ|PPL|Push|Pull|Legs|бро/i.test(t));
console.log('has exercises:', /\d+×\d+|ОСН|ДОП|АКС/.test(t));
console.log('has RIR:', /RIR\d/.test(t));
console.log('has volume:', /объём|сет|групп/i.test(t));
await page.screenshot({path:'scripts/render-25-manual-plan.png'});
await browser.close();
console.log('PE:',pe.length,pe.length===0?'✅':'❌');
console.log('M1_CHECK_DONE');
