import puppeteer from 'puppeteer-core';
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const pe = [];
const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox','--disable-gpu','--window-size=420,860'], defaultViewport: { width: 420, height: 860 } });
const page = await browser.newPage();
page.on('pageerror', e => pe.push(e.message + " || " + (e.stack||'').slice(0,250)));
await page.goto('http://localhost:4174/', { waitUntil: 'networkidle2', timeout: 45000 });
await page.waitForFunction(() => !document.querySelector('.screen-loading'), { timeout: 30000 }).catch(()=>{});
await new Promise(r=>setTimeout(r,2000));
const clickText = async (t)=>{ try{ const el=await page.evaluateHandle((x)=>{const a=[...document.querySelectorAll('button,a,div[role=button],li,h2,h3')];return a.find(e=>(e.innerText||'').includes(x))||null;},t); const n=el.asElement(); if(n){await n.click();return true;} }catch(e){} return false; };
const clickBtn = async (re)=>{ try{ return await page.evaluate((r)=>{const b=[...document.querySelectorAll('button')].find(x=>new RegExp(r).test(x.innerText));if(b){b.click();return b.innerText;}return null;},re);}catch(e){return null;} };
await clickText('Тренинг'); await new Promise(r=>setTimeout(r,1000));
await clickText('Планирование'); await new Promise(r=>setTimeout(r,1200));
const c = await clickBtn('📈 Аналитика');
console.log('clicked Аналитика:', c);
await new Promise(r=>setTimeout(r,2500));
const full = await page.evaluate(()=>document.body.innerText);
console.log('body len:', full.length);
console.log('has Аналит/История/Нет данных:', /Аналит|История|Нет данных|визуал|трениров|прогресс/i.test(full));
const idx = full.indexOf('График');
console.log('after-nav snippet:', full.slice(idx, idx+400));
await browser.close();
console.log('=== PAGE ERRORS ===');
[...new Set(pe)].filter(e=>!/supabase|websocket|ERR_NAME_NOT_RESOLVED|realtime|GoTrue/i.test(e)).slice(0,5).forEach(e=>console.log('  -', e.slice(0,260)));
console.log('U8_RECHECK_DONE');
