import puppeteer from 'puppeteer-core';
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox','--disable-gpu','--window-size=420,860'], defaultViewport: { width: 420, height: 860 } });
const page = await browser.newPage();
await page.goto('http://localhost:4174/', { waitUntil: 'networkidle2', timeout: 45000 });
await page.waitForFunction(() => !document.querySelector('.screen-loading'), { timeout: 30000 }).catch(()=>{});
await new Promise(r=>setTimeout(r,2000));
const clickText = async (t)=>{ try{ const el=await page.evaluateHandle((x)=>{const a=[...document.querySelectorAll('button,a,div[role=button],li,h2,h3')];return a.find(e=>(e.innerText||'').includes(x))||null;},t); const n=el.asElement(); if(n){await n.click();return true;} }catch(e){} return false; };
const clickBtn = async (re)=>{ try{ return await page.evaluate((r)=>{const b=[...document.querySelectorAll('button')].find(x=>new RegExp(r).test(x.innerText));if(b){b.click();return b.innerText;}return null;},re);}catch(e){return null;} };
await clickText('Тренинг'); await new Promise(r=>setTimeout(r,1000));
await clickText('Планирование'); await new Promise(r=>setTimeout(r,1200));
await clickBtn('Сгенерировать план'); await new Promise(r=>setTimeout(r,2500));
await clickBtn('✏️ Правка плана'); await new Promise(r=>setTimeout(r,1000));
await page.evaluate(()=>{ const b=[...document.querySelectorAll('button')].find(x=>/Добавить упражнение из каталога/.test(x.innerText)); if(b)b.click(); });
await new Promise(r=>setTimeout(r,900));
await clickBtn('Грудь'); await new Promise(r=>setTimeout(r,700));
const pickedName = await page.evaluate(()=>{ const sel=[...document.querySelectorAll('select')].pop(); if(sel && sel.options.length>1){ sel.value=sel.options[1].value; sel.dispatchEvent(new Event('change',{bubbles:true})); return sel.value; } return null; });
console.log('picked exercise:', pickedName);
await new Promise(r=>setTimeout(r,700));
await clickBtn('Добавить в день'); await new Promise(r=>setTimeout(r,1200));
await clickBtn('✓ Готово'); await new Promise(r=>setTimeout(r,1000));
await clickBtn('▶ Выполнение'); await new Promise(r=>setTimeout(r,1200));
await clickBtn('Начать тренировку'); await new Promise(r=>setTimeout(r,1500));
const run = await page.evaluate(()=>document.body.innerText);
console.log('added exercise in session:', pickedName && run.includes(pickedName));
console.log('session has added name:', pickedName ? new RegExp(pickedName.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).test(run) : false);
const lines = run.split('\n').filter(l=>pickedName && l.includes(pickedName)).slice(0,2);
console.log('matching lines:', lines);
await browser.close();
console.log('U5_PROP_DONE');
