import puppeteer from 'puppeteer-core';
const CHROME='C:/Program Files/Google/Chrome/Application/chrome.exe'; const pe=[];
const browser=await puppeteer.launch({executablePath:CHROME,headless:'new',args:['--no-sandbox','--disable-gpu','--window-size=420,860'],defaultViewport:{width:420,height:860}});
const page=await browser.newPage(); page.on('pageerror',e=>pe.push(e.message));
await page.goto('http://localhost:4174/',{waitUntil:'networkidle2',timeout:45000});
await page.waitForFunction(()=>!document.querySelector('.screen-loading'),{timeout:30000}).catch(()=>{});
await new Promise(r=>setTimeout(r,2000));
const clickText=async(t)=>{try{const el=await page.evaluateHandle((x)=>{const a=[...document.querySelectorAll('button,a,div[role=button],li,h2,h3')];return a.find(e=>(e.innerText||'').includes(x))||null;},t);const n=el.asElement();if(n){await n.click();return true;}}catch(e){}return false;};
await clickText('Тренинг');await new Promise(r=>setTimeout(r,1000));
await clickText('Планирование');await new Promise(r=>setTimeout(r,1500));
await page.evaluate(()=>{ const b=[...document.querySelectorAll('button')].find(x=>/🛠 Ручной сбор/.test(x.innerText)); if(b)b.click(); });
await new Promise(r=>setTimeout(r,1500));
await page.evaluate(()=>{ const b=[...document.querySelectorAll('button')].find(x=>x.innerText.trim()==='📋 План'); if(b)b.click(); });
await new Promise(r=>setTimeout(r,1500));
await page.evaluate(()=>{ const b=[...document.querySelectorAll('button')].find(x=>x.innerText.includes('Сгенерировать план')); if(b)b.click(); });
await new Promise(r=>setTimeout(r,3000));
// scroll to bottom gradually, capture full
await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
await new Promise(r=>setTimeout(r,1000));
const full=await page.evaluate(()=>document.body.innerText);
console.log('body len:', full.length);
console.log('has ОСН/ДОП/АКС:', /ОСН|ДОП|АКС/.test(full));
console.log('has exercise rows:', /\d+×\d+/.test(full));
const exMatch = full.match(/ОСН[\s\S]{0,200}/);
console.log('exercise sample:', exMatch ? exMatch[0].slice(0,200) : 'no ОСН found');
// check for day labels
console.log('has day labels:', /День|Day|Неделя/.test(full));
await browser.close();
console.log('PE:',pe.length,pe.length===0?'✅':'❌');
console.log('M1_FULL_DONE');
