import puppeteer from 'puppeteer-core';
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox','--disable-gpu','--window-size=420,860'], defaultViewport: { width: 420, height: 860 } });
const page = await browser.newPage();
await page.goto('http://localhost:4174/', { waitUntil: 'networkidle2', timeout: 45000 });
await page.waitForFunction(() => !document.querySelector('.screen-loading'), { timeout: 30000 }).catch(()=>{});
await new Promise(r=>setTimeout(r,2000));
const clickText = async (t)=>{ try{ const el=await page.evaluateHandle((x)=>{const a=[...document.querySelectorAll('button,a,div[role=button],li,h2,h3')];return a.find(e=>(e.innerText||'').includes(x))||null;},t); const n=el.asElement(); if(n){await n.click();return true;} }catch(e){} return false; };
const clickBtn = async (re)=>{ try{ return await page.evaluate((r)=>{const b=[...document.querySelectorAll('button')].find(x=>new RegExp(r).test(x.innerText));if(b){b.click();return b.innerText;}return null;},re);}catch(e){return null;} };
await clickText('Тренинг'); await new Promise(r=>setTimeout(r,1000));
await clickText('Планирование'); await new Promise(r=>setTimeout(r,1200));
await clickBtn('Сгенерировать план'); await new Promise(r=>setTimeout(r,2500));
await clickBtn('✏️ Правка плана'); await new Promise(r=>setTimeout(r,1000));
const n = await page.evaluate(()=>{ const inp=document.querySelector('input[type=number][aria-label="вес"]'); if(!inp)return 0; const s=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,'value').set; s.call(inp,'95'); inp.dispatchEvent(new Event('input',{bubbles:true})); return 1; });
await new Promise(r=>setTimeout(r,900));
await clickBtn('✓ Готово'); await new Promise(r=>setTimeout(r,1000));
await clickBtn('▶ Выполнение'); await new Promise(r=>setTimeout(r,1200));
await clickBtn('Начать тренировку'); await new Promise(r=>setTimeout(r,1500));
const lines = await page.evaluate(()=>document.body.innerText.split('\n').filter(l=>/цель/.test(l)).slice(0,5));
console.log('=== target lines after edit+start ==='); lines.forEach(l=>console.log('  ',l.trim()));
console.log('propagated 95:', lines.some(l=>/95кг/.test(l)));
await browser.close();
console.log('U4_PROP2_DONE');
