import puppeteer from 'puppeteer-core';
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const pe = [];
const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox','--disable-gpu','--window-size=420,860'], defaultViewport: { width: 420, height: 860 } });
const page = await browser.newPage();
page.on('pageerror', e => pe.push(e.message + ' || ' + (e.stack||'').slice(0,300)));
page.on('console', m => { if (m.type()==='error') pe.push('CONSOLE: ' + m.text()); });
await page.goto('http://localhost:4174/', { waitUntil: 'networkidle2', timeout: 45000 });
await page.waitForFunction(() => !document.querySelector('.screen-loading'), { timeout: 30000 }).catch(()=>{});
await new Promise(r=>setTimeout(r,2000));
const clickText = async (t)=>{ try{ const el=await page.evaluateHandle((x)=>{const a=[...document.querySelectorAll('button,a,div[role=button],li,h2,h3')];return a.find(e=>(e.innerText||'').includes(x))||null;},t); const n=el.asElement(); if(n){await n.click();return true;} }catch(e){} return false; };
const clickBtn = async (re)=>{ try{ return await page.evaluate((r)=>{const b=[...document.querySelectorAll('button')].find(x=>new RegExp(r).test(x.innerText));if(b){b.click();return b.innerText;}return null;},re);}catch(e){return null;} };
await clickText('Тренинг'); await new Promise(r=>setTimeout(r,1000));
await clickText('Планирование'); await new Promise(r=>setTimeout(r,1200));
const c = await clickBtn('🧠 Методики');
console.log('clicked Методики:', c);
await new Promise(r=>setTimeout(r,2000));
const full = await page.evaluate(()=>document.body.innerText);
console.log('has Композиция:', /Композиция методик/.test(full));
console.log('has Библиотека:', /Библиотека методик/.test(full));
console.log('has Периодизация:', /Периодизация/.test(full));
console.log('body len:', full.length);
await page.screenshot({path:'scripts/render-17-methods-unified.png'});
await browser.close();
console.log('=== ERRORS ===');
[...new Set(pe)].filter(e=>!/supabase|websocket|ERR_NAME_NOT_RESOLVED|realtime|GoTrue/i.test(e)).slice(0,8).forEach(e=>console.log('  -', e.slice(0,300)));
console.log('METHODS_UNIFIED_DONE');
