/**
 * pl-correction-exercises.ts — РЕЕСТР ПЛ-КОРРЕКЦИЙ УЧАСТКОВ АМПЛИТУДЫ (NEW).
 *
 * Реальные корректирующие упражнения по участкам движения (Westside/Sheiko/СРЦ),
 * которых нет в общем EXERCISE_CATALOG. Вынесены в ОТДЕЛЬНЫЙ реестр намеренно:
 * добавление в общий каталог меняло бы пулы слабых групп и планы ББ-авто.
 * Калькулятор лимитирующих факторов резолвит по EXERCISE_CATALOG + ЭТОТ реестр.
 *
 * Каждое упражнение — полная запись (техника/оборудование/паттерн), как в каталоге.
 * Подтверждены практикой: Westside Conjugate (Simmons), Sheiko, BarBend, СРЦ.
 */
import type { Exercise } from '../../core/types';

export const PL_CORRECTION_EXERCISES: Exercise[] = [
  { id:'pl_board_3', name:'Дожим с 3 см', group:'chest', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'med', fatigueCost:5, targetMuscle:'Трицепс (локаут)', order:2, substitutionGroup:'hor_push', movementPattern:'horizontal_push', canReplace:['pl_board_5'], cannotReplace:['cable_fly','fly_db'], technique:'Дожимы с плинтов 3 см — изоляция верхней трети жима. Взрывной дожим.', pauseSeconds:1, peakContraction:false, stretchPhase:false, comments:'ПЛ-коррекция дожима: перегрузка трицепса в локауте (Westside board press).' },
  { id:'pl_board_5', name:'Дожим с 5 см', group:'chest', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'med', fatigueCost:5, targetMuscle:'Трицепс (локаут)', order:2, substitutionGroup:'hor_push', movementPattern:'horizontal_push', canReplace:['pl_board_8'], cannotReplace:['cable_fly','fly_db'], technique:'Дожимы с плинтов 5 см — изоляция верхней трети жима. Взрывной дожим.', pauseSeconds:1, peakContraction:false, stretchPhase:false, comments:'ПЛ-коррекция дожима: перегрузка трицепса в локауте (Westside board press).' },
  { id:'pl_board_8', name:'Дожим с 8 см', group:'chest', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'med', fatigueCost:5, targetMuscle:'Трицепс (локаут)', order:2, substitutionGroup:'hor_push', movementPattern:'horizontal_push', canReplace:['pl_board_10'], cannotReplace:['cable_fly','fly_db'], technique:'Дожимы с плинтов 8 см — изоляция верхней трети жима. Взрывной дожим.', pauseSeconds:1, peakContraction:false, stretchPhase:false, comments:'ПЛ-коррекция дожима: перегрузка трицепса в локауте (Westside board press).' },
  { id:'pl_board_10', name:'Дожим с 10 см', group:'chest', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'med', fatigueCost:5, targetMuscle:'Трицепс (локаут)', order:2, substitutionGroup:'hor_push', movementPattern:'horizontal_push', canReplace:['pl_board_8'], cannotReplace:['cable_fly','fly_db'], technique:'Дожимы с плинтов 10 см — максимальная изоляция локаута жима.', pauseSeconds:1, peakContraction:false, stretchPhase:false, comments:'ПЛ-коррекция дожима: самая короткая амплитуда (Westside board press).' },
  { id:'pl_ohp', name:'Армейский жим', group:'shoulders', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:6, targetMuscle:'Дельты (передние), трицепс, верх груди', order:1, substitutionGroup:'shoulder_press', movementPattern:'horizontal_push', canReplace:['ohp_bar','ohp_seated_bar'], cannotReplace:['lateral_raise','rear_delt_fly'], technique:'Жим с плеч стоя, кор жёсткий, ягодицы напряжены. Старт с ключиц без читинга.', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Основной жим стоя — старт с ключиц и стабильность плечевого пояса.' },
  { id:'pl_bench_db', name:'Жим гантелей', group:'chest', type:'compound', equipment:'dumbbell', difficulty:'intermediate', jointStress:'low', fatigueCost:6, targetMuscle:'Грудные', order:1, substitutionGroup:'hor_push', movementPattern:'horizontal_push', canReplace:['bench_db'], cannotReplace:['cable_fly','pec_deck'], technique:'Гантели от уровня плеч, сведение вверху. Контроль опускания.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Объём грудных + симметрия сторон (унилатерально-контролируемое).' },
  { id:'pl_wide_squat', name:'Присед в широкой постановке', group:'legs', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Квадрицепсы, приводящие, ягодицы', order:2, substitutionGroup:'glute_squat', movementPattern:'squat', canReplace:['squat_box'], cannotReplace:['leg_ext','leg_curl'], technique:'Ноги шире плеч, носки наружу. Глубокий сед. Ягодицы и приводящие.', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Коррекция дожима и срыва сумо: ягодицы/приводящие в широких углах.' },
  { id:'pl_stiff_leg', name:'Тяга на прямых ногах', group:'back', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Бицепс бедра, разгибатели спины', order:2, substitutionGroup:'hip_hinge', movementPattern:'hinge', canReplace:['rdl','deadlift_stiff_leg'], cannotReplace:['pulldown','seated_row'], technique:'Почти прямые ноги, наклон таза назад. Штанга скользит по ногам.', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Задняя цепь: дожим приседа и середина/срыв тяги.' },
  { id:'pl_hyperext', name:'Гиперэкстензия', group:'back', type:'isolation', equipment:'bodyweight', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Разгибатели спины, ягодицы', order:3, substitutionGroup:'hip_hinge', movementPattern:'hinge', canReplace:['banded_good_morning'], cannotReplace:['deadlift','squat'], technique:'Наклон вперёд, подъём корпуса до прямой линии. Без переразгибания.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Жёсткость поясницы — удержание спины в тяге и приседе.' },
  { id:'pl_sldl_start', name:'Тяга с подчеркнутым стартом', group:'back', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'med', fatigueCost:8, targetMuscle:'Разгибатели, стартовая сила', order:2, substitutionGroup:'hip_hinge', movementPattern:'hinge', canReplace:['deadlift'], cannotReplace:['pulldown','seated_row'], technique:'Контроль стартовой позиции: нейтральный позвоночник, пауза при отрыве.', pauseSeconds:2, peakContraction:false, stretchPhase:false, comments:'Коррекция срыва тяги: удержание нейтральной спины при отрыве (СРЦ).' },
  { id:'pl_rack_dead', name:'Становая тяга с плинтов', group:'back', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'med', fatigueCost:7, targetMuscle:'Разгибатели, трапеции (локаут)', order:2, substitutionGroup:'hip_hinge', movementPattern:'hinge', canReplace:['rack_pull'], cannotReplace:['pulldown','seated_row'], technique:'Тяга с плинтов выше колен — изоляция локаута тяги.', pauseSeconds:1, peakContraction:false, stretchPhase:false, comments:'Коррекция дожима/локаута тяги (Westside rack pull).' },
  { id:'pl_ecc_deadlift', name:'Тяга уступающая', group:'back', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'high', fatigueCost:8, targetMuscle:'Задняя цепь (эксцентрика)', order:2, substitutionGroup:'hip_hinge', movementPattern:'hinge', canReplace:['deadlift'], cannotReplace:['pulldown','seated_row'], technique:'Опускание 5-7с — контроль уступающей фазы, взрывной подъём.', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Эксцентрический контроль тяги — позиция и задняя цепь (СРЦ).' },
];

/** Поиск по реестру ПЛ-коррекций (для резолвера калькулятора). */
export function findPlCorrection(name: string): Exercise | undefined {
  const n = name.toLowerCase().replace(/ё/g, 'е').trim();
  return PL_CORRECTION_EXERCISES.find(e => e.name.toLowerCase().replace(/ё/g, 'е') === n);
}
